.travis.yml
PythonClient/.pylintrc
PythonClient/carla/client.py
PythonClient/carla/planner/map.py
PythonClient/manual_control.py
PythonClient/requirements.txt

Adding pylint continuous integration for the "carla" Python API and the examples.

 Travis-ci support

---

.travis.yml
Docs/CONTRIBUTING.md
PythonClient/.pylintrc
PythonClient/carla/client.py
PythonClient/carla/planner/map.py
PythonClient/carla/sensor.py
PythonClient/carla/settings.py
PythonClient/carla/tcp.py
PythonClient/carla/util.py
PythonClient/client_example.py
PythonClient/manual_control.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/MapGen/CityMapMeshHolder.h
Util/ImageConverter/Makefile
Util/ImageConverter/README.md

Now Python code will need to pass [Pylint](https://www.pylint.org/) clean of **errors and warnings** in Python 2.7, 3.5 and 3.6.
I also added a [Cppcheck](http://cppcheck.sourceforge.net/) static analyser test for the C++ code that may catch some issues.

Stricter continuous integration tests

---

Docs/map_customization.md

Added a basic description for creating a new map based on the info posted in issue #110.
Related to #142
* **Unreal Engine version(s):** 4.17.2
It is only a starting point, not an extensive addition.

Added a basic description for creating a new map

---

Docs/how_to_build_on_linux.md
Unreal/CarlaUE4/.gitignore
Unreal/CarlaUE4/CarlaUE4.uproject
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/CityMapGenerator.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/DynamicWeather.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/SceneCaptureToDiskCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.cpp

Upgrade to Unreal Engine 4.18

---

PythonClient/manual_control.py

Added an option to toggle autopilot mode in the `manual_control.py` Python example.
It can be enabled when launching the script with the `-a` or `--autopilot` switches (as the other examples)
$ ./manual_control.py -a
Once in game can be toggled pressing `P`, just like in the server window in no-networking mode.
Fixes #282.

Add autopilot mode to manual control example

---

Docs/Example.CarlaSettings.ini
Docs/cameras_and_sensors.md
PythonClient/carla/carla_server_pb2.py
PythonClient/carla/client.py
PythonClient/carla/sensor.py
README.md
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Lidar.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SensorFactory.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaEncoder.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.cpp
Util/CarlaServer/include/carla/carla_server.h
Util/CarlaServer/source/carla/server/CarlaEncoder.cpp
Util/Proto/carla_server.proto

Just renamed all the occurrences of Lidar for consistency.

Rename LiDAR ray-trace to Lidar ray-cast

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp

Fixes #303 by forcing a reset on the static quality level even if the we are not playing in editor.
Please @juaxix make sure this doesn't have any nasty drawback.

Reset cached quality level not only in editor, but also in release

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaEncoder.cpp

Some of the measurements were not converted when I did #273.
Fixes #322.

Fix some measurements sent with the wrong units

---

Docs/connecting_the_client.md
PythonClient/view_start_positions.py

Adding a new simple and useful example to plot all the possible start
positions for a city
Fixes #311
Carla 0.8
ubuntu 16.04
python 2.7 and 3.5
None

Showing all the start positions.

---

Unreal/CarlaUE4/Config/CarlaWeather.Town01.ini
Unreal/CarlaUE4/Config/CarlaWeather.ini
Util/ContentVersions.txt

Made the sun azimuth editable from the CarlaWeadther.ini files
Fixes #338

Updated weather configuration

---

Util/ContentVersions.txt

Updates the link with the latest version of the assets.
* Fixes #349 Lighting error on road meshes
* Fixes #364 Illegal character on asset name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/365)

Update assets link

---

PythonClient/manual_control.py

Missing unit conversion for manual control map.
0.8.2
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/368)

 Fixing conversion problem on manual control

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/VehicleSpawnerBase.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/VehicleSpawnerBase.h

Improved the way the vehicle spawner works, now it will check each spawn instead of the sum of all the attempts and will use the counter to re-spawn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/375)

Changes in the vehicles spawning algorithm

---

Docs/configuring_the_simulation.md
Docs/faq.md
Docs/measurements.md

* Documented sync vs async modes.
* Updated FAQ with the Package script option for building a release.
* Documented bounding box in player measurements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/454)

Some documentation improvements

---

Util/ContentVersions.txt

Uploaded the latest version of the assets
* Fix #477 Adding two-wheeled vehicles
* Fix #479 Art optimizations
* Fix #395 NissanMicra slightly turning left when going forward
* Fix #192 Improved the performance of trees
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/484)

Update assets link for 0.8.3

---

Docs/how_to_build_on_windows.md

Thit PR closes #488.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/490)

Documentation about automatizing building for windows

---

Docs/Example.CarlaSettings.ini
PythonClient/carla/settings.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.h

Added an option to the _"CarlaSettings.ini"_ to disable bikes and motorbikes
**This PR only adds the option, it won't have any effect until the blueprints are changed**
Closes #497.
You can access the variable like this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/499)

Add option to disable two-wheeled vehicles

---

Docs/simulator_keyboard_input.md

Added new key "T" description to documentation.
Fixes #486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/508)

Added new key "T" description to documentation

---

Util/ContentVersions.txt

Update assets with the latest changes for version 0.8.4.
* Fixes #491 player vehicle missing collision info.
* Fixes some issues with two-wheeled vehicles of #496.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/509)

Update assets for 0.8.4

---

carla_ros_bridge/src/carla_ros_bridge/markers.py
carla_ros_bridge/src/carla_ros_bridge/sensors.py

This pull request fixing several bugs in the ros bridge:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/527)

Ros bridge fixes

---

.gitignore
carla_ros_bridge/client.launch
carla_ros_bridge/config/settings.yaml
carla_ros_bridge/src/carla_ros_bridge/bridge.py
carla_ros_bridge/src/carla_ros_bridge/bridge_with_rosbag.py
carla_ros_bridge/src/carla_ros_bridge/client.py

- episodes & framesperepisode added for rosbag recording
- writing control inputs to bag
@laurent-george - Hi - I added episodes to the existing ros bridge. Please review the changes ! 
Fixes #  
* **Unreal Engine version(s):** 4.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/536)

Adding episodes to rosbridge:

---

Docs/carla_server.md
Docs/how_to_build_on_windows.md
README.md
Rebuild.bat
Setup.bat

* Add missing frame counter to protocol documentation.
* Corrections to _How to build on Windows_.
* Change Discord links so they go directly to the relevant channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/539)

Few documentation fixes

---

Docs/connecting_the_client.md
Docs/download.md
Docs/how_to_build_on_linux.md
README.md

Changed information about the latest stable branch, to help to choose which branch you want to download.
Fixes #622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/686)

Added stable branch to documentation

---

Docs/how_to_model_vehicles.md
Docs/index.md
mkdocs.yml

Art Guidelines about how to model vehicles of 4 wheels.
-Modeling
-Materials
-Textures
-Nomenclature
-Rig
-LOD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/633)

Documentation on how to model vehicles

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/VehicleControl.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.h

Made info about vehicle behaviour public to unreal in order to make reviewing vehicles easier (related to #496)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/834)

Increased waypoint acceptance area, and expose debug info to blueprints

---

LibCarla/source/carla/geom/Math.h
LibCarla/source/carla/opendrive/OpenDrive.cpp
LibCarla/source/carla/road/MapBuilder.cpp
LibCarla/source/carla/road/element/Geometry.h
LibCarla/source/carla/road/element/RoadInfo.h
LibCarla/source/carla/road/element/RoadSegment.h
LibCarla/source/carla/road/element/Waypoint.cpp

Roads are connected between directly or using junctions. The lane connection between roads was wrong in some cases, some time the information was missing and other times was points to wrong or non-existent lane.
Need more testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/958)

Fix prev next lane

---

Docs/python_api.md
LibCarla/source/carla/client/TrafficLight.cpp
LibCarla/source/carla/client/TrafficLight.h
LibCarla/source/carla/client/Vehicle.cpp
LibCarla/source/carla/client/Vehicle.h
LibCarla/source/carla/client/detail/EpisodeState.h
LibCarla/source/carla/rpc/TrafficLightState.h
LibCarla/source/carla/sensor/data/ActorDynamicState.h
PythonAPI/manual_control.py
PythonAPI/source/libcarla/Actor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorRegistry.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorView.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DepthCamera.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficSignBase.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h

Added a HUD with info to `manual_control.py`.
Requires #954.
Might be annoying to have that on the screen for driving, but it can be hidden with F1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/955)

Manual control HUD

---

LibCarla/source/carla/rpc/WeatherParameters.cpp

Moved from 0 to 15 (subtle clouds over the horizon)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/950)

Tweak weather parameters

---

LibCarla/source/carla/geom/Vector3D.h

Fixes a small but annoying spelling error in `Length`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/965)

Spelling error

---

LibCarla/source/carla/geom/Location.h
LibCarla/source/carla/geom/Math.cpp
LibCarla/source/carla/geom/Math.h
LibCarla/source/carla/geom/Vector3D.h
LibCarla/source/carla/opendrive/OpenDrive.cpp
LibCarla/source/carla/road/Map.cpp
LibCarla/source/carla/road/MapBuilder.cpp
LibCarla/source/carla/road/MapBuilder.h
LibCarla/source/carla/road/element/Geometry.h
LibCarla/source/carla/road/element/RoadSegment.h
LibCarla/source/carla/road/element/Waypoint.cpp
LibCarla/source/test/test_vector3D.cpp
PythonAPI/source/libcarla/Geom.cpp

Now `GetWaypoint(Location &)` function from LibCarla works correctly, it returns an optional Waypoint if the given location is inside the road.
Performance, because this function uses distance calculation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/966)

GetWaypoint() function working + some unused printfs deleted

---

Docs/python_api_tutorial.md

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1078)

Minor changes to python_api_tutorial.md

---

CHANGELOG.md
Docs/cameras_and_sensors.md
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h

A tick_interval property is added for sensors. We can specify the interval in seconds that we want to tick the sensor. By default the interval is of 0 seconds, so as fast as possible.
Fixes #1057 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1116)

Adding 'tick_interval' property  for sensors

---

CHANGELOG.md
PythonAPI/agents/navigation/global_route_planner.py

This is an alternative branch of PR #1146 
Fixed GlobalRoutePlanner
Description
Fixes #
fixed turn decisions at junctions
removed redundant follow lane decisions
Where has this been tested?
Platform(s): Ubuntu 18.04
Python version(s): 2.7
Unreal Engine version(s): UE4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1197)

Pravinblaze global routing

---

CHANGELOG.md
PythonAPI/agents/navigation/basic_agent.py
PythonAPI/agents/navigation/global_route_planner.py
PythonAPI/agents/navigation/local_planner.py
PythonAPI/agents/tools/misc.py

Description
Modified basic agent to use global router
Fixes #
Fixed local planner
Where has this been tested?
Platform(s): Ubuntu 18.04
Python version(s): 2.7
Unreal Engine version(s): 4.21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1198)

Pravinblaze agent

---

PythonAPI/agents/navigation/global_route_planner.py
PythonAPI/automatic_control.py

Small fix for 1211 
Fixes #1211 
* **Platform(s):**  Ubunty 16.04
* **Python version(s):** 3.5.5
* **Unreal Engine version(s):** NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1248)

fix for 1211

---

CHANGELOG.md
PythonAPI/manual_control_steeringwheel.py
wheel_config.ini

Added support for Logitech G29 steering wheel and a new manual controller
Fixes #  
* **Platform(s):** 16.04
* **Python version(s):** 3.5.5
* **Unreal Engine version(s): NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1250)

added steering wheel control example

---

LibCarla/source/carla/road/element/RoadElevationInfo.h
LibCarla/source/carla/road/element/RoadInfo.h
LibCarla/source/carla/road/element/RoadInfoLaneWidth.h
LibCarla/source/carla/road/element/RoadInfoMarkRecord.h
LibCarla/source/carla/road/element/RoadInfoVelocity.h

Modified  existing classes for storing parsed open drive data.
* **Python version(s):**..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1378)

Open Drive Data Class Changes

---

CHANGELOG.md
PythonAPI/util/scene_layout.py

Adding the scene_layout.py script that is used to build
the full scene representation as a graph. It translate the CARLA
waypoint api to a single static graph.
Developed by  @manishthani
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1411)

Describe the full map,  scene_layout.py 

---

Docs/python_api.md

Add missing elements to Python API documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1421)

Documentation: Add missing attributes to VehicleControl

---

CHANGELOG.md
Util/ContentVersions.txt

- New Town07 - Inspired by a rural environment
- New Narrow Roads
- New Road
- Added new pack of assets
- WindMill
- Farm mid House
- Farm Big House
- Farm add house
- Silo
- Plant Corn
- Floor Corn
- Plant Grass
- Plant teeth of the lion
- Plant poppy
- Traffic Sign Yeld
- Added modular buildings NewYork Style
- Block 12 - 4 variations with their 3 Lods
- Block 13 - 
- Block 14 - 4 variations with thier 3 Lods
- Ladder
- Improve the performance in Town01 and Town02
- Fixed Semantic Segmentation in Town04, Town05, Town06.
- Changed yellow marking lane from Town01 and Town02 to dashed yellow marking lane
- Fixed Tree collision in Town 01
- Fixed VheicleSpawnPoint in Town01
- Fixed Geo-reference of Town01 and Town07
- Fixed floating pillars in Town04
- Add marking lanes in Town03
- Fixed …

Update content link

---

CHANGELOG.md
LibCarla/source/carla/road/element/LaneCrossingCalculator.cpp
LibCarla/source/carla/road/element/LaneMarking.cpp
LibCarla/source/carla/road/element/LaneMarking.h

The lane cross detector now has more information about the lane that is crossing.
The detection is really simple but enough for our driving cases.
* **Python version(s):** 2 and 3
Now it is purely based on OpenDrive, so expect different results from the previous one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1481)

Update lane cross detection

---

CHANGELOG.md
PythonAPI/carla/agents/tools/misc.py

Checklist:
Title says all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1483)

Fix division by zero in is_within_distance_ahead()

---

CHANGELOG.md
PythonAPI/carla/agents/tools/misc.py

Added eps
Fixes #  
* **Platform(s):** Ubunty 16.04
* **Python version(s):** 3.5.5 and 2.7.11
* **Unreal Engine version(s):** NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1492)

Fix: Problem divided by  small numbers in PythonAPI/navigation/misc.py

---

PythonAPI/carla/agents/navigation/global_route_planner.py

Fix tested in town 6 with new .xodr file from https://app.asana.com/0/916295602875190/1116020222248674
Fixes #  
* Localization now also using section id
* Added _find_loose_end method to resolve issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1511)

Fixed dangling segment issue

---

PythonAPI/carla/agents/navigation/global_route_planner.py

Added check to handle dangling edges with infinitesimally short paths
Fixes #  
* Checking for non zero path length before adding to graph representation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1512)

Added check for dangling edge with infinitesimal path

---

CHANGELOG.md
PythonAPI/examples/manual_control.py

Fixes #1530 about lidar effectiveness.
* **Platform(s):** windows 10 & ubuntu 16.04 LTS
* **Python version(s):** 3.7.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1531)

Fix bug about lidar effectiveness

---

PythonAPI/carla/agents/navigation/global_route_planner.py

Fixes #  
Added functionality to move past short intersection segment to
accurately calculate turn decisions for route plan.
* **Python version(s):** 3.5
* **Unreal Engine version(s):** 4.12
More testing the better
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1539)

Fix for route plan turn decisions

---

PythonAPI/carla/agents/navigation/basic_agent.py

The debug for the local planner was always on.
* **Python version(s):** 3.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1602)

 Adding the flag correctly

---

Docs/how_to_make_a_new_map.md

Fixes #  
* **Platform(s):Ubuntu 18.04/Windows 10
* **Python version(s):3.6/3.7.1/3.5
* **Unreal Engine version(s):4.19
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1624)

spelling mistakes

---

Docs/define_custom_props.md
Docs/index.md
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaBlueprintRegistry.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
mkdocs.yml

Added documentation on `How to add custom props and define them in Carla Blueprint Library` and fixed Windows compile errors.
Fixes: Windows compile errors
* **Platform(s):** Ubuntu 16.04LTS and Windows 10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1675)

Load props fixes for windows and documentation

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Util/ContentVersions.txt

Updates Carla content link and solves a bug and a linking error with PhysX for Windows.
Fixes: Windows bug and linking error with PhysX
* **Platform(s):** Windows 10 and Ubuntu 16.04TLS
* **Python version(s):** 2.7.12 and 3.5.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1698)

Update content link and Windows fixes

---

CHANGELOG.md
PythonAPI/carla/source/libcarla/Blueprint.cpp
PythonAPI/carla/source/libcarla/Control.cpp
PythonAPI/carla/source/libcarla/Geom.cpp
PythonAPI/carla/source/libcarla/Weather.cpp
PythonAPI/carla/source/libcarla/World.cpp
PythonAPI/test/unit/test_transform.py

Solve the problem of `RuntimeError: std::bad_cast` described here: https://github.com/carla-simulator/carla/issues/1125#issuecomment-500085292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1730)

update python __str__ wrapper

---

Unreal/CarlaUE4/Config/DefaultEngine.ini

Generate mesh distance fields set into DefaultEngine.ini
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1740)

Set mesh distance fields to true.

---

PythonAPI/examples/manual_control.py
PythonAPI/examples/spawn_npc.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/PedestrianParameters.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/VehicleParameters.h

* Add age to pedestrian blueprints.
* Add driver to vehicle blueprints (when supported).
* Randomize drivers on our Python examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1749)

Add more options to walker parameters

---

CHANGELOG.md
Docs/python_api.md
LibCarla/source/carla/rpc/WeatherParameters.cpp
LibCarla/source/carla/rpc/WeatherParameters.h
PythonAPI/carla/source/libcarla/Weather.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
Util/ContentVersions.txt

Added defaults to weather parameters that they trigger an special weather tailor-made for each town. This is done in UE4 blueprints, so I had to update content to latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1753)

New weather defaults

---

Docs/how_to_make_a_release.md
Docs/how_to_upgrade_content.md
Docs/index.md
mkdocs.yml

A couple of documents explaining how to upgrade content link and make a release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1767)

Documentation for upgrading content and making a release

---

LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.h
LibCarla/source/carla/geom/Location.h
LibCarla/source/carla/rpc/Actor.h
LibCarla/source/carla/streaming/detail/Dispatcher.h
PythonAPI/examples/start_recording.py

Went through the list of todos and removed some that are outdated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1757)

Remove some outdated todos in the code

---

CHANGELOG.md
PythonAPI/examples/manual_control.py

Added new command-line argument to `manual_control.py` to control the gamma correction of the RGB camera.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1861)

Added gamma correction as command-line argument to manual_control.py

---

CHANGELOG.md
PythonAPI/examples/manual_control.py

We improved the vehicle steering in manual control.
Now it turns faster when going from left to right or right to left.
* **Python version(s):** 2 and 3
* **Unreal Engine version(s):** 4.22.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1957)

Better steering for manual control

---

CHANGELOG.md
PythonAPI/examples/client_bounding_boxes.py

The example Python script called `client_bounding_boxes` was not working because the path to the egg file of carla was incorrect. Changed path to the correct one and now the script works again.
* **Platform(s):** Ubuntu 16.04LTS
* **Python version(s):** Python 2.7.12 and Python 3.5.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1962)

Fixed client_bounding_boxes example script

---

Jenkinsfile

Jenkins-Doxygen c+ docs now do Travis-ci
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1976)

Updated Jenkinsfile (Doxygen stage to do the travis-ci)

---

PythonAPI/examples/manual_control.py
PythonAPI/examples/spawn_npc.py

Change default pedestrian speed. We've changed the speed of pedestrians to make it more like reality.
* **Platform(s):** Windows and Linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1924)

Change default pedestrian speed

---

TrafficManager/source/pipeline/SimpleWaypoint.cpp
TrafficManager/source/pipeline/SimpleWaypoint.h
TrafficManager/source/pipeline/TrafficDistributor.cpp
TrafficManager/source/pipeline/TrafficDistributor.h
TrafficManager/source/pipeline/TrafficLightStage.cpp
TrafficManager/source/pipeline/TrafficLightStage.h
TrafficManager/source/pipeline/VicinityGrid.h

Minor fixes in the VicinityGrid, SimpleWaypoint, TrafficDistribution and TrafficLightState according to review comment.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2116)

Review comment changes

---

TrafficManager/source/pipeline/CarlaDataAccessLayer.cpp
TrafficManager/source/pipeline/CarlaDataAccessLayer.h
TrafficManager/source/pipeline/CollisionStage.cpp
TrafficManager/source/pipeline/CollisionStage.h
TrafficManager/source/pipeline/PIDController.cpp
TrafficManager/source/pipeline/PIDController.h
TrafficManager/source/pipeline/Pipeline.cpp
TrafficManager/source/pipeline/Pipeline.h
TrafficManager/source/pipeline/PipelineStage.h
TrafficManager/source/pipeline/TrafficDistributor.cpp

Made changes to review comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2117)

Made changes for review comments

---

.travis.yml
CHANGELOG.md

Currently checking for Travis errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2154)

Enabled and fixed pylint for python3 in travis

---

CHANGELOG.md
Docs/bp_library.md
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h

- Added default Gaussian noise (normal distribution) functions to IMU and GNSS sensors.
- Fixed IMU Accelerometer, now is more accurate and the data is more similar to the real sensors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2235)

Added default noise function to IMU and GNSS

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp

**Description**
It's a small change but fixes the all ugly shadow of Pedestrians. 
**Where has this been tested?**
- **Platform(s):** Ubuntu 16.04
- **Python version(s):** 2.7
- **Unreal Engine version(s):** UE4 22.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2240)

Fix weird shadows in pedestrians

---

CHANGELOG.md
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.cpp

Fixes #1952 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2182)

Return HitDistance instead of HitRadius

---

PythonAPI/examples/no_rendering_mode.py

Manish added some documentation lines in `no_rendering_mode.py`. It could be a good idea merging this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2284)

Added more documentation and refactor on no rendering mode

---

CHANGELOG.md
PythonAPI/examples/automatic_control.py

Removed several unused lines of code that prevent the BasicAgent to work properly.
Looks like the `Num Lock` state was the main issue.
Thanks, @jackbart94 for pointing it out.
Fixes #1985
Compile everything and run:
```sh
./automatic_control.py -a Basic
```
_with `Num Lock` enabled / disabled_
* **Python version(s):** 2 & 3
Maybe some keyboard utility missing, but should not be used in this script, right?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2306)

Fixed NumLock error automatic_control.py

---

Docs/how_to_build_on_linux.md

- Linux build installation process has been rewritten. 
* **Platform(s):** Linux 18.04.3
* **Python version(s):** Python 2.7.17 and 3.6.9
- clang paragraph could be improved. 
- A specific command to set environment variable persistently could be added. 
- Test if it is better to add "&&" before the break lines for separated command sets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2412)

sergi-e/linux-build

---

Docs/getting_started/introduction.md
Docs/getting_started/quickstart.md
Docs/index.md
mkdocs.yml

- The documentation structure has been revisited in the mkdocs.yml to make more sense of the actual content. 
- Getting started section created:
- Introduction page created: contains a summary of the project, how it works, main features and values of CARLA. 
- Quickstart page created: corresponds to the installation process of the prepackaged CARLA releases. 
* **Platform(s):** Linux 18.04.3
* **Python version(s):** Python 2.7.17 and 3.6.9
- The current content has been redistributed but not updated so current documentation state is quite experimental.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2408)

Sergi e/intro and builds

---

Docs/how_to_add_assets.md

Updated vehicle art setup link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2347)

vehicle art setup artlink updated

---

CHANGELOG.md
LibCarla/source/carla/trafficmanager/BatchControlStage.cpp
LibCarla/source/carla/trafficmanager/CollisionStage.cpp
LibCarla/source/carla/trafficmanager/CollisionStage.h
LibCarla/source/carla/trafficmanager/InMemoryMap.cpp
LibCarla/source/carla/trafficmanager/InMemoryMap.h
LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.h
LibCarla/source/carla/trafficmanager/MessengerAndDataTypes.h
LibCarla/source/carla/trafficmanager/MotionPlannerStage.cpp
LibCarla/source/carla/trafficmanager/SimpleWaypoint.cpp
LibCarla/source/carla/trafficmanager/SimpleWaypoint.h
LibCarla/source/carla/trafficmanager/TrafficLightStage.cpp
LibCarla/source/carla/trafficmanager/TrafficManager.cpp
LibCarla/source/carla/trafficmanager/TrafficManager.h

This PR adds destruction of stuck vehicles. It checks for vehicles without moving (i.e., velocity minor than a threshold) and increments an internal counter for each vehicle. If this counter is greater than a threshold, the vehicle is considered to be stuck a it is destroyed. A threshold to avoid consecutive destructions has been added (elapsed time between destructions).
* **Python version(s):** 2.7.17 and 3.6.9
Removing vehicles that are not really stuck or removing vehicles that are not responsible of the blockage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2385)

Joel mb/traffic manager

---

CHANGELOG.md
Docs/how_to_make_a_new_map.md

Checklist:
Fixed some non-working links in `how_to_make_a_new_map.md`
* **Platform(s):**  n/a
* **Python version(s):** n/a
* **Unreal Engine version(s):** n/a
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2469)

Fixed some urls in how_to_make_a_new_map.md

---

Docs/core_actors.md
Docs/core_concepts.md
Docs/core_map.md
Docs/core_world.md
Docs/index.md
Docs/python_cookbook.md
Docs/recorder_and_playback.md
Docs/walker_bone_control.md
mkdocs.yml

- The "First steps" section has been divided into "First steps" and "Advanced steps". 
- The content in "Pyhton API Tutorial" has been separated into: "Core concepts", "1st. World and client", "2nd. Actors and blueprints", "3rd. Maps and traffic" and "4th. Sensors and data". 
- Content in "Python API tutorial" has been moved to recorder_and_playback.md. This section is now in Advanced steps. 
- The mkdocs.yml has been changed to add all these modifications. 
- Broken links have been updated in index.md and walker_bone_control.md
- Content in "First steps" has been reallocated but not rewritten, so it is quite urgent to do so.
--- …

sergi-e/new-first-steps

---

Docs/cameras_and_sensors.md
Docs/core_actors.md
Docs/core_map.md
Docs/how_to_add_assets.md
Docs/index.md
Docs/python_api_tutorial.md
Docs/rendering_options.md
Docs/simulation_time_and_synchrony.md
mkdocs.yml

- Changes in "Configuring the simulation": Time steps and synchrony are now an independent section.
- New section: "Simulation time and synchrony" to explain how do these concepts relate in CARLA. 
- Minor modification in a button text in "How to build on Linux". 
* **Platform(s):** Ubuntu 18.04.4 
- Is explanation clear?
- Configuring the simulation needs further rewriting.
- What about multiclient?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2452)

Sergi e/synch step

---

CHANGELOG.md
Docs/dev/build_system.md
Util/BoostFiles/rational.hpp
Util/BoostFiles/read.hpp
Util/BuildTools/Setup.bat
Util/BuildTools/Setup.sh

Upgraded Boost to latest version, supposedly 1.70 improves performance of Boost.Asio. See Boost's [release notes](https://www.boost.org/users/history/).
Closes #1607.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2301)

Upgrade Boost to 1.72.0

---

Docs/carla_docker.md
Docs/rendering_options.md

- CARLA in a Docker syntax updated. 
- Headless CARLA methods updated: Docker recommended, emulating deprecated. 
Fixes #  
* **Platform(s):**  Ubuntu 18.04.4
- NVIDIA syntax may be incorrect, as the tutorial has not been tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2507)

sergi-e/headless-docker

---

Docs/core_world.md
Docs/getting_started/quickstart.md
Docs/recorder_and_playback.md
Docs/rendering_options.md
Docs/simulation_time_and_synchrony.md
mkdocs.yml

Fixes #  
* **Platform(s):** 18.04.4
-Binary file format has not been checked yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2496)

Sergi e/adv recorder

---

Docs/release_readme.md

- release_readme.md added again. 
* **Unreal Engine version(s):** 4.22 
- This page appears again as not referenced anywhere, but it is the readme for release packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2549)

sergi-e/release-readme-fix

---

PythonAPI/examples/manual_control.py

Default values for accelerometer and gyroscope have been added to avoid the crash of manual_control in synchronous mode when updating the information text in the pygame window.
During the first frame, after reloading the actor, the information displayed may not be reliable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2552)

Add default values for accelerometer and gyroscope.

---

Docs/build_linux.md
Util/BuildTools/BuildUtilsDocker.sh
Util/BuildTools/Linux.mk

Improvements in Recast building for Linux:
- Less compilation and dependencies are required in the package
- Error + fix recommendation if it fails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2560)

Improved linux recast installation

---

CHANGELOG.md
LibCarla/source/carla/trafficmanager/CollisionStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.h
LibCarla/source/carla/trafficmanager/Parameters.cpp
LibCarla/source/carla/trafficmanager/Parameters.h
LibCarla/source/carla/trafficmanager/TrafficManager.h
LibCarla/source/carla/trafficmanager/TrafficManagerBase.h
LibCarla/source/carla/trafficmanager/TrafficManagerClient.h
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.h
LibCarla/source/carla/trafficmanager/TrafficManagerRemote.cpp
LibCarla/source/carla/trafficmanager/TrafficManagerRemote.h
LibCarla/source/carla/trafficmanager/TrafficManagerServer.h
PythonAPI/carla/source/libcarla/TrafficManager.cpp
PythonAPI/examples/spawn_npc.py

Revamped lane changes to happen more carefully and with a better algorithm, also adding final missing parameters
* **Python version(s):** 2,7
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2561)

Revamping lane changes and adding parameters

---

Docs/python_api.md
PythonAPI/docs/actor.yml

- GetLightState and SetLightState appear now properly. 
- Any to All in VehicleLightState. 
Fixes #  
* **Platform(s):**  Ubuntu 18.04.4
- Method order needs to be improved yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2564)

sergi-e/add-vehicle-lights

---

LibCarla/source/carla/trafficmanager/BatchControlStage.cpp
LibCarla/source/carla/trafficmanager/BatchControlStage.h
LibCarla/source/carla/trafficmanager/Parameters.cpp
LibCarla/source/carla/trafficmanager/Parameters.h
LibCarla/source/carla/trafficmanager/PerformanceDiagnostics.cpp
PythonAPI/carla/source/libcarla/TrafficManager.cpp
PythonAPI/examples/spawn_npc.py

* Implemented blocking call for RunStep() method to ensure step to step synchronisation with the simulator.
* Exposed set_synchronous_mode(bool) method in PythonAPI to explicitly set traffic manager into synchronous mode of operation.
* Set TrafficManger into synchronous mode in spawn_npc.py if run with flag --sync.
* **Platform(s):** Ubuntu 18.0f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2566)

Fix for synchronous mode operation of TrafficManager

---

Docs/extra.css
Docs/index.md
Docs/start_introduction.md
Docs/start_quickstart.md
mkdocs.yml

- Index links fixed. 
- Style updated for Index and Quick start installation. 
- Introduction to be checked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2573)

sergi-e/p098-index

---

LibCarla/source/carla/client/TrafficLight.h

Quick fix. `carla::client::TrafficLight` inheritance was broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2578)

Quick fix.

---

Docs/python_api.md
PythonAPI/docs/client.yml

- Added returns for the three recorder methods in client. 
- Check the Python API docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2613)

Added return for recorder methods

---

Docs/ros_installation.md
Docs/ros_launchs.md
Docs/ros_msgs.md
Docs/start_quickstart.md

- Style iteration for the whole "ROS" section.
- Updates on quick start installation regarding the new packages for CARLA 0.9.8 and CARLA 0.9.7 (with "all main"). 
- Links inside tables may not work online. Check after merge.
- New launchfiles regarding ScenarioRunner to be added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2591)

Sergi e/p098 ros

---

PythonAPI/carla/agents/navigation/controller.py
PythonAPI/carla/agents/navigation/local_planner.py

Max acceleration, brake and steering of the local planner are now parameters instead of constants.
Changed a max_accel for max_brake
Moved the "Destroying ego-vehicle" print inside the condition
None?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2653)

Minor changes to local_planner + some bug fixes

---

.travis.yml
Docs/build_linux.md
Docs/build_system.md
Docs/cont_coding_standard.md
Examples/CppClient/README.md
Jenkinsfile
LibCarla/source/carla/client/BlueprintLibrary.h
Util/BuildTools/Ad-rss.sh
Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Setup.sh
Util/Docker/Prerequisites.Dockerfile

Upgrading toolchain version to LLVM 8.0 and clang 8.0, to be able to use Unreal 4.24
* **Platform(s):** Ubuntu 16, 18
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2656)

Upgrade to LLVM 8.0.1

---

CHANGELOG.md
LibCarla/source/carla/geom/Mesh.cpp
LibCarla/source/carla/geom/Mesh.h
LibCarla/source/carla/opendrive/OpenDriveParser.cpp
LibCarla/source/carla/road/Map.cpp
LibCarla/source/carla/road/Map.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveGenerator.cpp

- Added support for pedestrian crosswalks on standalone OpenDRIVE.
- Improved road mesh generation code and added handy functions like creating triangle strips and fans.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2649)

Pedestrian crossing standalone OpenDRIVE

---

LibCarla/source/carla/client/BlueprintLibrary.cpp
LibCarla/source/carla/client/WalkerAIController.h
LibCarla/source/carla/client/World.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/EpisodeState.h
LibCarla/source/carla/client/detail/Simulator.h
LibCarla/source/carla/road/Map.cpp

Fixes some minor issues I've found compiling the client side with an older version of clang.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2662)

Fix build on old compilers

---

Docs/ref_sensors.md

- p098 iteration on sensors. 
- Check links after merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2639)

sergi-e/p098-sensors

---

Docs/adv_recorder.md
Docs/cont_contribution_guidelines.md
Docs/core_actors.md
Docs/core_map.md
Docs/core_sensors.md
Docs/core_world.md
Docs/ros_installation.md
Docs/ros_launchs.md
Docs/ros_msgs.md
Docs/tuto_A_map_creation.md
Docs/tuto_A_standalone_packages.md
Docs/tuto_G_control_vehicle_physics.md

- Links fixed. 
- sensors ref and python API to be updated in their own PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2661)

sergi-e/p098-links

---

CHANGELOG.md
Docs/python_api.md
LibCarla/source/carla/client/Client.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.cpp
LibCarla/source/carla/client/detail/Simulator.h
LibCarla/source/carla/geom/Mesh.cpp
LibCarla/source/carla/road/LaneSection.cpp
LibCarla/source/carla/road/LaneSection.h
LibCarla/source/carla/road/Map.cpp
LibCarla/source/carla/road/Map.h
PythonAPI/carla/source/libcarla/Client.cpp
PythonAPI/carla/source/libcarla/libcarla.cpp
PythonAPI/docs/client.yml
PythonAPI/util/config.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveGenerator.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

Added security features to the standalone OpenDRIVE mode aiming to prevent cars from falling from the road. Also, these parameters of these generation features have been exposed to the PythonAPI.
Cars can still fall in certain cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2678)

Standalone OpenDRIVE security features

---

LibCarla/source/carla/trafficmanager/BatchControlStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.h
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp

Modified traffic manager pipeline to wait for an external trigger to initiate data flow for each update cycle in synchronous mode.
This ensures data received from the simulator for a particular frame is processed and the result is sent back to the simulator within the same update cycle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2683)

Fix for synchronous mode data inconsistency in Traffic Manager

---

CHANGELOG.md
Docs/python_api.md
LibCarla/source/carla/client/Landmark.h
LibCarla/source/carla/client/Map.cpp
LibCarla/source/carla/client/Map.h
LibCarla/source/carla/road/Map.cpp
LibCarla/source/carla/road/Map.h
PythonAPI/carla/source/libcarla/Map.cpp
PythonAPI/docs/map.yml

Added new functions to the Python API:
`carla.Map`:
- `get_all_landmarks`: returns all landmarks in the map
- `get_all_landmarks_from_id`: returns all landmarks in the map with a specific OpenDRIVE id
- `get_all_landmarks_of_type`: returns all landmarks in the map of a specific type.
Fixed missing documentation for function `get_junction` in `carla.Waypoint`.
* **Python version(s):**2, 3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2684)

Added get landmarks functions from map.

---

Docs/adv_synchrony_timestep.md

Fix typos and a copy-paste error in document `Synchrony and time-step`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2692)

Doc fix typos and a copy-paste error

---

LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationUtils.cpp
LibCarla/source/carla/trafficmanager/LocalizationUtils.h

Implemented changes to account for all 2d bounding box corners during localization of unregistered vehicles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2702)

Better Localization For Unregistered Vehicles

---

LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.h

Implemented changes for tracking multiple hero vehicles in hybrid physics mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2701)

Multiple Hero Vehicles In Hybrid Physics Mode

---

LibCarla/source/carla/trafficmanager/CollisionStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
LibCarla/source/carla/trafficmanager/LocalizationStage.h
LibCarla/source/carla/trafficmanager/MotionPlannerStage.cpp
LibCarla/source/carla/trafficmanager/Parameters.cpp
LibCarla/source/carla/trafficmanager/Parameters.h
LibCarla/source/carla/trafficmanager/TrafficManager.h
LibCarla/source/carla/trafficmanager/TrafficManagerBase.h
LibCarla/source/carla/trafficmanager/TrafficManagerClient.h
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.h
LibCarla/source/carla/trafficmanager/TrafficManagerRemote.cpp
LibCarla/source/carla/trafficmanager/TrafficManagerRemote.h
LibCarla/source/carla/trafficmanager/TrafficManagerServer.h
PythonAPI/carla/source/libcarla/TrafficManager.cpp
PythonAPI/examples/spawn_npc.py

This PR changes some conditions in the collision detection policy, removes vertical overlap from Hybrid Mode and introduces a parameter to set a custom radius for Hybrid Mode.
* **Platform(s):** Ubuntu 16
* **Python version(s):** 2.7 & 3.5
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2708)

Minor changes to Traffic Manager

---

LibCarla/source/carla/road/Map.cpp

On OpenDRIVE standalone mode: Fixed sidewalks in junctions being smoothed with the road mesh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2731)

Prevent sedewalks to be smoothed in junctions

---

PythonAPI/examples/tutorial.py

It's not really nice that the first thing any user launches ends with an error, so since it's been reported a few times here is the change.
Fixes #2745 (among others)
* **Platform(s):** Ubuntu 16
* **Python version(s):** Python 2.7 & 3.5
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2750)

Fixes destruction of actors in tutorial.py

---

Jenkinsfile
PythonAPI/test/smoke/test_snapshot.py
Util/BuildTools/Package.bat

The spawn points in all the maps where lowered very close to the floor, so I need to raise them when executing the smoke test to avoid some vehicles change its rotation abruptly and make the test fails.
Also for windows, this is a fix to the 'make clean' command, that was not working properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2759)

Smoke test fix, and windows clean fix

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLightSubsystem.cpp

Added some checks on LightSubsytem to avoid possible crashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2772)

Added checks to avoid crash on LightSubsystem

---

Examples/CppClient/README.md

Update the README of the ClientCpp example. Some info was outdated/incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2782)

Update CppClient README

---

CHANGELOG.md
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Weather/Weather.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Weather/Weather.h
Update.sh

Added 2 fixes:
* Fixed rain drop particles spawn issues when spawning camera sensors
* Fixed Update.sh from failing when the root folder contains a space on it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2814)

Rain particles and Update.sh fixes

---

CHANGELOG.md
LibCarla/source/carla/rpc/WheelPhysicsControl.h

Added a missing include to WheelPhysicsControl.h.
Fixes #2810
* **Platform(s):** Win10
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2811)

Add missing include in WheelPhysicsControl.h

---

Docs/python_api.md
PythonAPI/docs/client.yml

Fix on Traffic Manager doc. 
- In force_lane_change() right is True and left is False. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2872)

Fix force lane change right/left

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightManager.cpp

Fixes crash in windows when loading a map. Adds a map check for signal spawning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2875)

Fixed map loading crash in windows.

---

README.md

- CARLA Talks 2020 added to the README so that they are easy accessible from GitHub. 
- The README will have to be updated to include new materials when created (and depending on these).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2936)

sergi-e/talks-2020

---

README.md

- New link for pedestrians video. 
- New link for ESI slides. 
- Check links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2941)

sergi-e/fix-talks

---

Docs/build_linux.md
README.md

- Added patch instructions in Build from Linux. 
- Added mention to patch in README. 
- Download link for the patch has to be changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2947)

sergi-e/patch-udn

---

LibCarla/source/carla/streaming/detail/tcp/ServerSession.cpp

This small change disables delays in the tcp communication from server to client, dramatically improving performance in synchronous mode in linux systems.
* **Platform(s):** Ubuntu18.04, Windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2965)

Improved stream performance

---

PythonAPI/carla/requirements.txt
PythonAPI/examples/requirements.txt
PythonAPI/util/requirements.txt

Fixes Python3 numpy install in Travis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3004)

Travis fix

---

CHANGELOG.md
Unreal/CarlaUE4/Config/DefaultEngine.ini
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Radar.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp

New low-poly collision boxes have been added to all cars (2 wheeled cars will also be added soon).
In order to take advantage of it, this PR changes which collision layers the Lidar and Radar are searching on. This means these sensors have better precision now.
Also, since the raycast is now ignoring several other channels, this could improve the performance.
Fixes #2716
* **Python version(s):** 3.x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2967)

Improved raycast sensor collisions

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderQuery.cpp

Small fix for the QueryInfo function.
Fixes #  
* **Python version(s):** 2,3
* **Unreal Engine version(s):** 24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3018)

Fixed QueryInfo parsing error.

---

CHANGELOG.md
Unreal/CarlaUE4/CarlaUE4.uproject

Added Renderdoc plugin to the Unreal project to speed up frame debugging operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3031)

Add Renderdoc plugin

---

Docs/build_linux.md

- Added new distro dependency for Linux build. 
- Update dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3042)

sergi-e/linux-distro

---

Docs/python_api.md
PythonAPI/docs/actor.yml
PythonAPI/docs/client.yml

- Added carla.Actor.is_alive.
- Improved description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3055)

sergi-e/fix-actor-alive

---

CHANGELOG.md
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp

Fixed the import pipeline due to changes in the Unreal Engine 4.24 code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3061)

Fixed import pipeline

---

Docs/ros_installation.md

- Added missing command for submodule installation. 
- Check versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3077)

sergi-e/ros-fix

---

Util/Docker/Release.Dockerfile

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3098)

Update: Make CARLA faster in a docker container

---

LibCarla/source/carla/opendrive/parser/ObjectParser.cpp

Removed debug warning
* **Python version(s):** 2,3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3136)

Removed debug warning

---

Util/BuildTools/Setup.sh
Util/InstallersWin/install_rpclib.bat

Fix a crash when closing sessions in the RPClib. We use a new version 2.2.1.c3 of the RPClib fork.
* **Platform(s):** Ubuntu, Windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3146)

Update RPClib with fix of crash when closing session

---

CHANGELOG.md
PythonAPI/examples/sensor_syncronization.py

Added script as an example to syncronize all gathering of sensor data in the client.
Co-authored-by: @marcgpuig 
Fixes #  
* **Python version(s):** 2.7, 3.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3147)

Sensor sincronization in client example

---

PythonAPI/examples/opend3d.py

Added new semantic tags to open3d script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3149)

Added new semantic tags to open3d script

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp

Fixed low-quality mode being too bright.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3148)

Fixed light in low quality mode

---

Jenkinsfile
Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Check.sh
Util/BuildTools/Linux.mk
Util/BuildTools/Package.sh
Util/BuildTools/Setup.sh

Updated build scripts to accept a specific python3 versions in ubuntu.
Hopefully nothing breaks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3226)

Python 3 version

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DepthCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SemanticSegmentationCamera.cpp

This fixes the OpenGL crash when connecting but more testing is strongly needed
Fixes #3188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3211)

Initial fix for OpenGL crash

---

Docs/start_introduction.md

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3201)

Update start_introduction.md minor typo fix responsible of>responsible for

---

Docs/cont_contribution_guidelines.md
Docs/cont_doc_standard.md

- Art contribution guidelines updated. Now including a step by step of the process. 
- Code contribution guidelines updated. Explanation of the new Gitflow (merges to the `dev` branch). 
- Docs contribution guidelines and standard briefly revisited. 
- Code and Docs standards are yet to be udpated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3249)

sergi-e/new-cont-guidelines

---

Jenkinsfile
Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Check.sh
Util/BuildTools/Linux.mk
Util/BuildTools/Package.sh
Util/BuildTools/Setup.sh
Util/Docker/Prerequisites.Dockerfile

Fixed prerequisites in dockerfile and removed python 2 default compilation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3227)

Fixed docker prerequisites and removed python 2 default compilation

---

Docs/ros_installation.md
Docs/start_quickstart.md

- Quickstart installation (deb instructions) updated. 
- ROS bridge installation (deb instructions) updated. 
- ROS bridge docs nee d to be revisited.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3241)

sergi-e/update-deb-installation

---

Jenkinsfile
LibCarla/source/carla/client/World.cpp
LibCarla/source/carla/client/World.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.h
PythonAPI/carla/source/libcarla/World.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/BoundingBox.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/BoundingBoxCalculator.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/BoundingBoxCalculator.h

Created a function to iterate through all the actors with geometry of the level and calculate their BB.
Also added a helper function on the GM that will be improved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3272)

Retrieve BBs of all the elements of the level

---

LibCarla/source/carla/ThreadPool.h
LibCarla/source/carla/client/ServerSideSensor.cpp
LibCarla/source/carla/rpc/Server.h
LibCarla/source/carla/streaming/detail/tcp/Client.cpp
LibCarla/source/carla/streaming/detail/tcp/Server.cpp
LibCarla/source/carla/streaming/detail/tcp/Server.h
LibCarla/source/carla/streaming/detail/tcp/ServerSession.cpp
LibCarla/source/carla/streaming/low_level/Client.h
LibCarla/source/test/server/test_benchmark_streaming.cpp

- Fixed the `bad_weak_ptr` descrived in #3122
- Updated several `boost::asio` calls that are deprecated in boost 1.72.0
Fixes #3122
* **Python version(s):** 2 and 3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3295)

Fixed bad_weak_ptr

---

Docs/cont_contribution_guidelines.md

- Added a brief note on "Code contributions" to remember users that they have to fork the CARLA repository and keep their fork in sync with the CARLA repo. 
- Links have been provided, but we still depend on some knowledge regarding GitHub/Git.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3289)

sergi-e/cont-fork-note

---

Docs/adv_rendering_options.md
Docs/adv_sumo.md
Docs/adv_synchrony_timestep.md
Docs/build_faq.md
Docs/build_linux.md
Docs/build_windows.md
Docs/cont_doc_standard.md
Docs/ref_sensors.md
Docs/ros_installation.md
Docs/start_quickstart.md
Docs/tuto_A_add_map.md
Docs/tuto_A_add_props.md
Docs/tuto_A_add_vehicle.md
Docs/tuto_G_openstreetmap.md
Docs/tuto_G_retrieve_data.md

- Updated all command-lines to use `python3`. 
- Added installation notes 
- Pending: documentation on how to use Python2 and how do these changes affect the ROS bridge. 
- Changes in the ROS bridge installation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3277)

sergi-e/python-version-note

---

Docs/build_linux.md
Docs/build_windows.md

- Fixed patch commands. 
- Changes in style and writing for this guide. 
- Minor changes in Windows build guide accordingly. 
- Windows build is to be updated yet. 
- Video tutorial for Linux build is about to come.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3311)

sergi-e/build-linux-update

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/DebugShapeDrawer.cpp

Since the light has been changed, so has to be done in the debug color multiplier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3342)

Fixed debug lines with current illumination

---

Unreal/CarlaUE4/Config/DefaultScalability.ini

- Added `DefaultScalability.ini` so UE4 doesn't disable `r.EyeAdaptionQuality` when using low quality.
_This prevents the spectator from being really bright while in using low-quality mode._
* **Platform(s):** Ubuntu 18.04 & Windows 10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3344)

Added DefaultScalability.ini 

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp

Removed debug warning.
* **Platform(s):** Ubuntu18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3351)

Removed debug warning.

---

Co-Simulation/PTV-Vissim/vissim_integration/carla_simulation.py

Updated `set_velocity` to `set_target_velocity` in PTV-Vissim Co-Simulation (https://github.com/carla-simulator/carla/pull/3335)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3354)

[Co-Simulation] Updated set_velocity to set_target_velocity

---

Docs/adv_rss.md

Updated adv_rss.md build instruction to reflect:
- latest pyplusplus changes
- PROJ not being installed in the system anymore
- move to python3 on CARLA build.
Fixes #3278   
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3357)

Upddate adv_rss docu

---

Docs/adv_synchrony_timestep.md
Docs/python_api.md
PythonAPI/docs/actor.yml
PythonAPI/docs/client.yml
PythonAPI/docs/commands.yml
PythonAPI/docs/map.yml

- Updates on:
- set_velocity() -> set_target_velocity()
- set_angular_velocity() -> set_target_angular_velocity()
- ApplyVelocity() -> ApplyTargetVelocity()
- ApplyAngularVelocity() -> ApplyTargetAngularVelocity()
- Added/Modified in carla.Actor: 
- add_angular_impulse()
- add_impulse()
- add_force()
- add_torque()
- enable_constant_velocity()
- disable_constant_velocity()
- Added commands: 
- ApplyForce()
- ApplyTargetAngularVelocity()
- ApplyTargetVelocity()
- ApplyTorque
- Missing units until PR on API units is merged. 
- Modifications are yet to come for this methods.
--- …

sergi-e/docs-vel-force-torque

---

Docs/python_api.md
Docs/tuto_G_openstreetmap.md
PythonAPI/docs/client.yml

- New method in PythonAPI regarding TM (client.md). The method fixes a bug that causes TM to crash on OSM generated maps. 
- This update may change when the bug is solved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3325)

sergi-e/tm-fix-osm

---

LibCarla/source/carla/trafficmanager/Constants.h
LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp

Removes a warning while building TM
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3363)

Fixes float conversion in TM

---

Docs/python_api.md
PythonAPI/docs/actor.yml
PythonAPI/docs/geom.yml
PythonAPI/docs/sensor_data.yml
PythonAPI/docs/world.yml

- Modified the PythonAPI reference with new information regarding bounding boxes.
- carla.BoundingBox now has a variable rotation. 
- New enum class carla.CityObjectLabel. 
- New function carla.World.get_all_bbs(). 
- Minor changes for Vehicle.bounding_box and Walker.bounding_box. 
- How are bounding boxes generated for junctions? 
- Other instances of bounding boxes along the docs should be fixed too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3304)

sergi-e/bounding-boxes-api

---

Unreal/CarlaUE4/Config/DefaultEngine.ini
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.cpp

Upgrades Carla to DX12 and fixes its issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3367)

Upgraded to DX12

---

Docs/plugins_carlaviz.md

Update CarlaViz doc to make it compatible with Carla 0.9.10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3369)

update CarlaViz doc

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

Fixes the SetSimulatePhysics for pedestrians. We were disabling the Physics from the PrimitiveComponent but for Walkers
we need to set the physics in the CharacterMovementComponent.
None, apart from the fact that the behaviour of the SetSimulatePhysics has change because now it does what it is suppose to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3375)

Fixing SetSimulatePhysics for pedestrians

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DepthCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DepthCamera.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SemanticSegmentationCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SemanticSegmentationCamera.h

Fixed a random freeze on the camera.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3383)

Fixed camera freeze

---

LibCarla/source/carla/client/Actor.cpp
LibCarla/source/carla/client/Actor.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.h
LibCarla/source/carla/rpc/Command.h
PythonAPI/carla/source/libcarla/Actor.cpp
PythonAPI/carla/source/libcarla/Commands.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

Added the feature to disable the gravity for actors so the can hang in the air without falling and without disabling all the physics.
* **Python version(s):** Python 3.6.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3382)

Added EnableGravity mode 

---

Jenkinsfile
Util/BuildTools/BuildCarlaUE4.sh
Util/BuildTools/BuildLibCarla.sh
Util/BuildTools/BuildOSM2ODR.sh
Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Check.sh
Util/BuildTools/Deploy.sh
Util/BuildTools/Package.sh
Util/BuildTools/Plugins.sh
Util/BuildTools/Prettify.sh
Util/BuildTools/Setup.sh

Now you can specify a list of python versions to compile: `make XXXX ARGS="--python-version=2,3"`.
Updated jenkinsfile to compile for python 2.7 and 3.7.
Removed check for invalid arguments. Scripts now use the arguments that are needed and ignore the rest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3381)

Python 2 Returns

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DepthCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SemanticSegmentationCamera.cpp

Fixed a bug that caused cameras to ignore the sensor_tick parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3399)

Fixed sensor_tick on cameras

---

Docs/build_linux.md
Docs/build_windows.md
Docs/index.md
Docs/ros_installation.md
Docs/start_quickstart.md
Docs/tuto_G_openstreetmap.md
mkdocs.yml

- Updates on quick start, Linux build, Windows build and ROS installation regarding Python2/Python3 support. 
- Fixed "Contribute with assets" title to "Contribute assets". 
- Added a note on OSM regarding how to open an OSM file in Windows. 
- Does the note in OSM work for all Windows installations?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3450)

sergi-e/docs-various-notes

---

Docs/python_api.md
PythonAPI/docs/doc_gen.py

- Fixed method sorting in the PythonAPI reference. 
- Should variables and enums follow some kind of ordering?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3457)

Fixed method sorting

---

LibCarla/source/carla/client/Map.cpp
LibCarla/source/carla/client/Map.h
LibCarla/source/carla/road/Lane.h
LibCarla/source/carla/road/Map.cpp
LibCarla/source/carla/road/Map.h
PythonAPI/carla/source/libcarla/Map.cpp

Changed LaneType enum type from unsigned to signed type. The previous version produced a crash with windows version.
* **Platform(s):** Ubuntu, Windows
Slightly uglier code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3481)

Changed LaneType enum from unsigned to signed type

---

Docs/adv_synchrony_timestep.md
Docs/adv_traffic_manager.md
Docs/python_api.md
PythonAPI/docs/client.yml
PythonAPI/docs/sensor_data.yml
PythonAPI/docs/world.yml

- New additions for carla.TrafficManager in the PythonAPI reference. 
- Updated "Other considerations" section in adv_tm.md:
- Removed "FPS limitations". 
- Updated "Synchronous mode". 
- TBD: Determinism for TM docs. 
- Check PythonAPI docs for discrepancies on TM 2.0 architecture.
- Should a note be added in adv_synchrony_timestep.md regarding TM.set_synchronous_mode()?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3453)

sergi-e/tm-determinism-and-updates-docs

---

Util/BuildTools/Check.sh

Add smoke tests for the specified python versions.
Longer jenkins time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3519)

Fixed check.sh smoke test python version

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp

Now prop position is recorded and reported like other dynamic actors in the scene.
The recorder info will be more cluttered with prop position data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3509)

Added prop position to recorder.

---

PythonAPI/carla/source/libcarla/World.cpp

Fixed a segmentation fault on python 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3534)

Fixed segmentation fault on Python2

---

CHANGELOG.md
LibCarla/source/carla/client/detail/Simulator.cpp
LibCarla/source/carla/rpc/EpisodeSettings.h
PythonAPI/carla/source/libcarla/World.cpp
PythonAPI/examples/test_collisions.py
PythonAPI/util/check_collisions_substepping.py
Unreal/CarlaUE4/Config/DefaultEngine.ini
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/EpisodeSettings.h

Physics substepping options now can be controlled by the client.
Also added a script to check determinism of collisions
Fixes #  
The new default options could have an impact on the performance but it should be very small. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3538)

Added control of substepping

---

PythonAPI/carla/source/libcarla/Actor.cpp

The `carla.Actor.semantic_tags` was throwing an error in Python when used, now it works correctly.
* **Python version(s):** 2 & 3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3553)

Fixed carla.Actor.semantic_tags

---

Docs/tuto_A_add_vehicle.md

Minor updates to make the docs wording more consistent with Unreal.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3560)

Minor improvements to add a new vehicle doc

---

CHANGELOG.md
Util/BuildTools/BuildOSM2ODR.sh
Util/BuildTools/BuildPythonAPI.sh

Quick fix that enables using the parameter `[--config={Debug,Development,Shipping}]` in the `make package` command like so:
```
make package ARGS="--config=Debug"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3641)

Fixed error when using "--config" in make package

---

LibCarla/source/carla/road/Map.cpp

Fixed crash when signals are at the start of a road.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3657)

Fixed distance > 0.0 bug for landmark search.

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ObjectRegister.cpp

Added check to avoid a crash on static mesh components without mesh assigned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3689)

Updates on control level objects

---

Docs/build_faq.md

Fixes broken layout in FAQ [1] due to mixing html and markdown. I have fixed this by using virtually only markdown apart from a button at the top for the forum so it should be less liable to break. Now the questions are laid out in a list at the top and link to the answers further down the page.
I also corrected some typos and reworded some sentences.
[1]: https://carla.readthedocs.io/en/latest/build_faq/
Firefox and Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3712)

Refactored FAQ section of docs to use minimal html and fix broken layout

---

Co-Simulation/Sumo/run_synchronization.py

This fixes a bug while using SUMO and traffic manager together (using the spawn_npc script).
Vehicles managed by the traffic manager are now moving correctly.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3736)

Fixed bug in SUMO while using the Traffic manager

---

Docs/build_windows.md

Added documentation to compile and patch the engine
in windows
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3751)

Documentation to compile UE4 in Windows

---

LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp

Fixes vehicles loosing control when managed by TM with low fps on the server side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3752)

Fixed tm loosing control of cars with low fps

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/EnvironmentObject.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/BaseCarlaMovementComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/BaseCarlaMovementComponent.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/CarSimManagerComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/CarSimManagerComponent.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/DefaultMovementComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/DefaultMovementComponent.h

This PR creates a better interface for controlling vehicles using different components that may use different physics (physX, CarSim, etc).
The class `UBaseCarlaMovementComponent` has been added and this is the base class for all other Movement Components. The virtual functions exposed in this class are used by `ACarlaWheeledVehicle` in order to control the vehicle.
The class `UDefaultMovementComponent` uses the Unreal physX vehicle system (the same as before).
And the class `UCarSimManagerComponent` uses CarSim to simulate the vehicle motion.
--- …

Improved vehicle movement components interface

---

PythonAPI/test/smoke/test_sensor_tick_time.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DepthCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SemanticSegmentationCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h

The sensors were not ticking according to the sensor_tick attribute.
A smoke test was added to check this scenario too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3818)

Fix sensor tick

---

Docs/build_linux.md

Added new patches to the Linux build documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3861)

Added new patches to the Linux build documentation

---

LibCarla/source/carla/client/Vehicle.cpp
LibCarla/source/carla/client/Vehicle.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.h
LibCarla/source/compiler/disable-ue4-macros.h
LibCarla/source/compiler/enable-ue4-macros.h
PythonAPI/carla/source/libcarla/Actor.cpp
Unreal/CarlaUE4/CarlaUE4.uproject
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/BaseCarlaMovementComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/BaseCarlaMovementComponent.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.h
Util/BuildTools/BuildCarlaUE4.bat
Util/BuildTools/BuildCarlaUE4.sh
Util/BuildTools/Setup.bat
Util/BuildTools/Setup.sh
Util/BuildTools/Windows.mk
Util/InstallersWin/install_chrono.bat

This PR brings an initial implementation of the CHRONO physics engine for vehicles (http://projectchrono.org/) to CARLA.
For vehicles, it adds a new function `enable_chrono_physics(max_substeps, max_substep_delta_time)`, which hands the physics simulation of the vehicle to CHRONO.
The implementation is done in `ChronoMovementComponent.h` and `ChronoMovementComponent.cpp`.
The build system has been changed to add the CHRONO library to be compiled and included in CARLA. CHRONO is added as an optional module, in order to include it in your project you need to add the argument "--chrono" to the `make XXX` commands.
In addition, CHRONO requires RTTI enabled which requires a small modification to the Unreal Engine: in the file `Engine\Source\Programs\UnrealBuildTool\Configuration\TargetRules.cs` …

Initial CHRONO implementation

---

CHANGELOG.md
PythonAPI/examples/manual_control.py
PythonAPI/examples/visualize_multiple_sensors.py
PythonAPI/util/check_lidar_bb.py

This PR improves manual_control and adds two new scripts.
- In manual_control: now the camera perspectives are set taking into account the car's size
- Added 'visualize_multiple_sensors' example that shows how to render several sensors in the same window. The script shows four cameras and two lidars but can easily be extended.
- Added 'check_lidar_bb' util script that shows how to compare lidar data with the BB of the cars.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3899)

Update example scripts

---

LibCarla/source/carla/client/Actor.h

The IsAlive method was updated because some problems were found after merging the PR #3940. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3944)

Fixed actor isAlive method

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
Util/BuildTools/Setup.bat

This PR places 3rd party chrono dlls in the same location as the executable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3955)

Fixed chrono Dlls separated from the binary file

---

LibCarla/source/carla/trafficmanager/Constants.h
LibCarla/source/carla/trafficmanager/TrafficManager.cpp
LibCarla/source/carla/trafficmanager/TrafficManager.h
LibCarla/source/carla/trafficmanager/TrafficManagerBase.h
LibCarla/source/carla/trafficmanager/TrafficManagerClient.h
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.h
LibCarla/source/carla/trafficmanager/TrafficManagerRemote.cpp
LibCarla/source/carla/trafficmanager/TrafficManagerRemote.h
LibCarla/source/carla/trafficmanager/TrafficManagerServer.h
PythonAPI/carla/source/libcarla/TrafficManager.cpp
PythonAPI/test/smoke/test_determinism.py

This PR fixes a memory leak in TM for some xodr maps.
It synchronizes its execution with the server so that
* **Unreal Engine version(s):** 4.24, 4.26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3937)

Fixed memory leak when activating TM in some maps in asynchronous mode

---

Util/BuildTools/Setup.sh

Creates a folder that could be missing during setup process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3962)

Fix missing setup folder

---

Util/BuildTools/BuildPythonAPI.bat

A typo in ./Util/BuildTools/BuildPythonAPI.bat file is fixed.
The comment for Python3-targeted build had been written as "Build for Python 2".
Fixes #   None
* **Python version(s):** Python 3.7.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3961)

Fix typo in BuildPythonAPI.bat file

---

README.md

Added license information for PROJ, SQLite, Xerces-c and Eigen. Added links for other mentioned licenses. 
I listed dependencies in the context of the integration they are used with. If you think there is a better way then let me know and I can reword it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3972)

Added dependency licenses to README

---

PythonAPI/examples/manual_control.py

Updated manual control with new camera shots of pedestrians. Also included a fix of a minor warning of the LaneInvasionSensor.
Fixes # 
#3900 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3971)

New camera shots for pedestrians in manual control

---

CHANGELOG.md
LibCarla/source/carla/sensor/data/LidarData.h
LibCarla/source/carla/sensor/data/SemanticLidarData.h
PythonAPI/test/smoke/__init__.py
PythonAPI/test/smoke/test_lidar.py
PythonAPI/test/smoke_test_list.txt
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.h

This PR fixed a bug in the point count of each channel in the case that there was a dropoff based on Intensity.
The points that were being dropped based on intensity were not being removed from the channel count so the real points being sent were less than the given by `get_point_count()` method.
* **Unreal Engine version(s):** 4.6
Fixes #4031
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4075)

Fix bug in Lidar channel point count

---

PythonAPI/test/smoke/__init__.py
PythonAPI/test/smoke/test_sensor_determinism.py
PythonAPI/test/smoke/test_sync.py

This PR introduces some improvements to the smoke tests to increase their stability.
Fixes #  
* **Python version(s):** 3.6 / 2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4203)

Minor improvements to smoke tests

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp

Fixes missing includes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4234)

Fix missing includes

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/RoadPainterWrapper.h
Util/BuildTools/Import.py

Fixed bugs with location and scale calculation
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4254)

Fixed scale excess and location bug

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4264)

Fix for loop error

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h

Removed render thread and game thread synchronization for all cameras except DVS. This improves performance for some configurations as it allows other clients (e.g., traffic manager) that does not need sensor data to start computing before the rendering has finished.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4252)

Removed renderthread and gamethread syncrhonization for cameras

---

CHANGELOG.md
LibCarla/source/carla/rpc/WeatherParameters.cpp
LibCarla/source/carla/rpc/WeatherParameters.h
PythonAPI/carla/source/libcarla/Weather.cpp
PythonAPI/util/environment.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Weather/Weather.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Weather/WeatherParameters.h

Extended PythonAPI for changing weather parameters. Those are scattering_intensity, mie_scattering_scale, rayleigh_scattering_scale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4298)

Extended PythonAPI for changing some parameters in weather 

---

CHANGELOG.md
LibCarla/source/carla/rpc/Command.h
PythonAPI/carla/source/libcarla/Commands.cpp
PythonAPI/test/smoke/test_vehicle_physics.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

Added fixes to increase determinism in CARLA.
- During the loading of the sublevels, we make sure that we are loading them in the correct order. Minor differences in this were affecting the determinism on the Opt maps
- Added ApplyVehiclePhysicsControl to allow use it with apply_batch_sync and rewrite of the vehicle smoke test with this to ensure that no commands are lost.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4341)

Determinism improvements: Sublevel loading + physics control command

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h

Changes for rotating vehicle wheels through the Python API without any crashes. Needs update from engine for this to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4370)

Fixed client crash when rotating vehicle wheels

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.cpp

Removed unnecessary warning/error logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4326)

Removed unnecessary warning/error logs

---

PythonAPI/util/environment.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4423)

Added missing commas in weather script

---

CHANGELOG.md
LibCarla/source/carla/client/Vehicle.cpp
LibCarla/source/carla/client/Vehicle.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.h
LibCarla/source/carla/rpc/Command.h
PythonAPI/carla/source/libcarla/Actor.cpp
PythonAPI/carla/source/libcarla/Commands.cpp
PythonAPI/docs/actor.yml
PythonAPI/docs/commands.yml
PythonAPI/examples/manual_control.py
PythonAPI/util/vehicle_physics_tester.py
Unreal/CarlaUE4/CarlaUE4.uproject
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h

Added a method (`enable_debug_telemetry()` for a vehicle that shows the telemetry information in the spectator window.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4402)

Added vehicle telemetry + minor bugs

---

PythonAPI/util/performance_benchmark.py

Updated benchmark script:
* Changed default camera resolution to `1920x1080`
* Fixed bug calling `wait_for_tick` in synchronous mode.
Fixes #  
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4429)

Updated benchmark script

---

Jenkinsfile
Util/BuildTools/BuildPythonAPI.bat
Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Package.bat
Util/BuildTools/Package.sh
Util/BuildTools/Setup.sh

This PR introduces support for `wheels` for the CARLA PythonAPI. `Eggs` are still built and provided in CARLA packages. 
**Important**: CARLA scripts are still depending on `eggs`.
Additionally, the following python dependencies are now required to build the wheel:
*Windows*
* `wheel` for each one of the python versions we want to generate the wheel.
*Ubuntu*
* `wheel` for each one of the python versions we want to generate the wheel.
* `auditwheel` (only for Python3). This dependency is only required to repair the resultant wheel (bundle the external shared libraries dependencies).
* **Platform(s):** Ubuntu 18.04, Windows 10
* **Python version(s):** 2.7, 3.6, 3.7, 3.8
The deployment of wheels is still not automatized. We will need to upload them …

Wheel support

---

PythonAPI/examples/manual_control.py

Two minor fixes to manual control
- Radar was located inside the chasis in big vehicles. Now, it is located in relation to the box of the car.
This fixes the cases where the radar was located inside the car
- Removed annoying warning about speed
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4448)

Minor fixes to manual control

---

LibCarla/source/carla/rpc/WeatherParameters.cpp
LibCarla/source/carla/rpc/WeatherParameters.h
PythonAPI/carla/source/libcarla/Weather.cpp

This PR adds new weather presets and fixes some others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4459)

New weather presets

---

CHANGELOG.md
PythonAPI/examples/generate_traffic.py
PythonAPI/examples/manual_control.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/PedestrianParameters.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/VehicleParameters.h

Added blueprint atribute to vehicle and pedestrian for mark the generation.
Fixes 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4462)

Added generation attribute to vehicles and pedestrians

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp

Updated commandlet for importing large maps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4468)

Fixed make import process for large maps

---

LibCarla/source/carla/trafficmanager/InMemoryMap.cpp
LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp

This PR fixes a bug generating waypoints with the same id in the InMemoryMap.
* **Platform(s):** Ubuntu18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4469)

[TM] Fix bug generating waypoints with the same id

---

PythonAPI/examples/generate_traffic.py
PythonAPI/examples/manual_control.py
PythonAPI/util/performance_benchmark.py
Util/BuildTools/Import.py

Minor improvements to the python scripts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4467)

Script changes

---

PythonAPI/carla/README.md
PythonAPI/carla/setup.py

Added project description to the python package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4471)

Added Python package description

---

PythonAPI/examples/generate_traffic.py
PythonAPI/examples/manual_control.py

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4474)

Minor changes in scripts

---

Co-Simulation/Sumo/spawn_npc_sumo.py
PythonAPI/examples/automatic_control.py
PythonAPI/examples/generate_traffic.py
PythonAPI/examples/manual_control_carsim.py
PythonAPI/examples/manual_control_chrono.py
PythonAPI/examples/no_rendering_mode.py
PythonAPI/examples/start_recording.py

In generate_traffic we have added microlino and sprinter to the vehicles to filter in safe mode.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4477)

Added vehicles to generate_traffic safe vehicles

---

LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp

Reverts a change in MP Stage that caused collision in specific situation
Needs testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4478)

Revert changes in MP stage

---

Docs/index.md
Docs/tuto_G_carsim_integration.md
mkdocs.yml

Removed references to CarSim being in beta stage from nav, index and docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4501)

Removed references to CarSim being in beta stage

---

CHANGELOG.md
Docs/python_api.md
LibCarla/source/carla/geom/Math.h
PythonAPI/carla/source/libcarla/Geom.cpp
PythonAPI/docs/geom.yml

CARLA vectors had several useful functions that were already prat of the C++ API but not the Python one, so they have been exposed. It also updates the Python API docs.
This are just additions, so none?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4499)

Exposed some vector functions to the python api

---

Docs/adv_synchrony_timestep.md

This PR adds python examples on how to achieve determinism in CARLA to the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4665)

[Doc] Determinism examples

---

PythonAPI/carla/source/libcarla/Actor.cpp
PythonAPI/carla/source/libcarla/Control.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp

Fixed lights not switching on an off during night time. Fixed compilation errors in linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4842)

Fix day night light switch

---

CHANGELOG.md
Util/BuildTools/Import.py

Some fixes in the import.py script that was failing when importing props without any map
* **Unreal Engine version(s):** UE 4.26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4718)

Fixing import script

---

CHANGELOG.md
Docs/python_api.md
PythonAPI/docs/blueprint.yml
PythonAPI/docs/world.yml
PythonAPI/util/apply_texture.py

This PR updated the documentation ans changelog for previous features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4850)

Adding missing classes and function to documentation

---

Docs/build_linux.md
Docs/build_windows.md

Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4909)

add UE4 warning

---

Util/InstallersWin/install_zlib.bat

Updates Zlib version for windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5294)

Updated zlib version

---

Util/BuildTools/Setup.sh

Fixes broken download link for xerces library.
Fixes #5305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5309)

Fix xerces download

---

CHANGELOG.md

Document the change to boost::variant2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5296)

Document switch to boost variant2

---

LibCarla/source/test/common/test_streaming.cpp

fixed the namespace resolution ambiguity with Server and Client class objects in tests
Fixes #  
* Ubuntu 21.10
* 3.8 
* CarlaUnreal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5184)

fixed the namespace resolution ambiguity with Server and Client class objects in tests

---

Util/BuildTools/Package.sh

This PR fixes cooking errors when too many tiles are being packaged at the same time.
It cooks tiles in batches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5331)

Fixed commandline overflow when too many tiles are cooked at the same time

---

Unreal/CarlaUE4/Source/CarlaUE4.Target.cs

Removes logs in packaged builds in shipping configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5335)

Removed shipping logs

---

Util/BuildTools/Ad-rss.sh
Util/BuildTools/BuildOSM2ODR.sh
Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Setup.sh

Fixes an issue when compiling with ubuntu 18.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5400)

Fix ubuntu18 compilation

---

LibCarla/source/carla/trafficmanager/TrafficLightStage.cpp

PR #5443 updated the TM to improve its smoothnes sat stop signed intersections, but added a segmeantation fault.
That segmentation fault was fixed with PR #5480, but it added a bug to the stop behavior
This PR fixes that bug, and hopefully doesn't add any more issues
* **Platform(s):** Ubutnu 18.04
* **Unreal Engine version(s):** CARLA's 4.26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5488)

Reverted some TM stop changes

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLightSubsystem.cpp

Removed a debug message at the `SetDayNightCycle` function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5565)

Remove debug message

---

LibCarla/source/carla/multigpu/listener.cpp
LibCarla/source/carla/multigpu/router.cpp
LibCarla/source/carla/multigpu/router.h
LibCarla/source/carla/streaming/detail/tcp/Server.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DataStream.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

In Editor mode the secondary server was still open after stopping the simulation.
Now it closes properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5614)

Secondary server listener is now closed (in editor it was still open)

---

CHANGELOG.md
PythonAPI/carla/agents/navigation/basic_agent.py
PythonAPI/carla/agents/navigation/constant_velocity_agent.py

Expanded the Python agents, adding detection of obstacle in adjacent lanes if the offset makes them invade such lane.
Additionally, exposed some of the parameters for more customization
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5664)

Added offset detection to Python agents

---

Docs/adv_agents.md

Fix wrong number in adv_agents.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5659)

fix wrong number in doc

---

Util/InstallersWin/install_zlib.bat

When run make PythonAPI with the old version, it gives an error and unable to make the build
Fixes #  5300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5337)

Increase zlib version to 1.2.12

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDefinition.h

Adding an structure to allow parked vehicle definition data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5696)

adding structure for vehicle definition (managing parked vehicles)

---

LibCarla/source/carla/opendrive/parser/ObjectParser.cpp
LibCarla/source/carla/road/MapBuilder.cpp

Added the possibility to spawn static signals (i.e, the signal is spawned using the position defined in the RoadRunner). By default, traffics signs are moved out of the roads. To spawn a static signal add `STATIC` to the signal name (e.g., `Speed_STATIC_50` or `Sign_STATIC_Yield`)
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5712)

Added static signals

---

PythonAPI/examples/manual_control.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/MapGen/LargeMapManager.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CustomTerrainPhysicsComponent.cpp

This PR adds a terramechanics attribute to enable or disable terramechanics to individual vehicles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5839)

Add terramechanics attribute

---

Util/BuildTools/Setup.sh
Util/InstallersWin/install_xercesc.bat
Util/InstallersWin/install_zlib.bat

Fix xerces-c dependency
Fixes #  
* **Python version(s):**  3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5850)

Fix dependencies

---

PythonAPI/carla/agents/navigation/basic_agent.py

From self._max_steer to self._max_brake
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5797)

Fix a typo in setting the max brake

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CustomTerrainPhysicsComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CustomTerrainPhysicsComponent.h

Fixed inputs for NN model.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5862)

Added local frame option. Fixed inputs for NN

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/VegetationManager.cpp

The vehicle was only checking foliage for the first tile only.
Also was checking with the local coordinates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5866)

Fixed bug vehicle not spawning foliage with multiples tiles

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/VegetationManager.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/VegetationManager.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h

Fixed a visual bug where vegetation would be hidden and displayed while the vehicle was driving through it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5876)

Luis package

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/SpringBasedVegetationComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/SpringBasedVegetationComponent.h

Adding radius of vegetation capsules as parameter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5882)

Adding radius parameter for the vegetation capsules

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/CarSimManagerComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/DefaultMovementComponent.cpp

Fixes a bug where the vehicle would freeze when enabling the chrono vehicle simulation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5957)

Fix chrono freeze

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/BaseVegetationActor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/BaseVegetationActor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/SpringBasedVegetationComponent.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/SpringBasedVegetationComponent.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CustomTerrainPhysicsComponent.cpp

Bug fixes to improve vegetation collision.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5948)

Vegetation fixes

---

Jenkinsfile

Add Town12 to the jenkins build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5995)

Add town12 jenkinsfile

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs

Fix for packages in Ubuntu.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6053)

Fixed package bug

---

PythonAPI/carla/agents/navigation/controller.py

Fix typo in updating lateral controller
Fixes #6037 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6080)

Fix typo in updating lateral controller

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/MapGen/LargeMapManager.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/MapGen/LargeMapManager.h

This PR enables the Spectator as an actor to use in large maps for tile streaming.
The map loading times becomes a bit larger due to the loading of the first tiles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6114)

Use Spectator in large maps

---

Docs/tuto_A_add_props.md
Util/Docker/docker_tools.py

Fixes two issues with the `docker_tools.py` utility script:
- The argument `--image` was ignored. 
- Fixes a typo in the "Add new props" docs (the option is defined as `packages`, not `package`)
* **Platform(s):** MacOS
* **Python version(s):** Python 3.8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6152)

Fix issues in docker_tools.py

---

PythonAPI/carla/agents/navigation/controller.py
Util/Docker/docker_tools.py

Fix typos in docker_tools.py
Fixes #6141
* **Unreal Engine version(s):** CARLAs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6142)

Fix typos in docker_tools.py

---

PythonAPI/carla/setup.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
Util/BuildTools/BuildOSM2ODR.sh
Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Setup.sh

The supported compiler is clang, but that is not the default on Ubuntu. Unreal Editor itself ships clang-10 for use on linux (along with the libc++ that Unreal itself uses) so just use those in CARLA.
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6132)

Use Unreal's host SDK on Linux

---

Examples/CppClient/ToolChain.cmake
LibCarla/source/third-party/simplify/Simplify.h

Remove unused parameter and commented code
Fixes #  
* **Python version(s):** 3.9
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6243)

Remove unused parameter

---

PythonAPI/carla/source/libcarla/Weather.cpp

**Remove the duplicated output of cloudiness in `Weather.cpp`**
Fixes **the annoying and confusing output (in fact nothing serious..)**
* **Platform(s):  *Ubuntu 20.04* ...
* **Python version(s):  *3.7.3* ...
Hopefully no one uses this duplicated output...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6404)

remove duplicated cloudiness output

---

Docs/build_linux.md

Change pseudopath to linux format
Change pseudopath in linux build documentation to linux format
It is only visual change in documentation, it should not break anything
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6449)

Change style of path/to/carla in build_linux.md

---

CHANGELOG.md
LibCarla/source/carla/multigpu/primary.cpp
LibCarla/source/carla/multigpu/primary.h
LibCarla/source/carla/streaming/detail/Stream.h
LibCarla/source/carla/streaming/detail/StreamStateBase.cpp
LibCarla/source/carla/streaming/detail/tcp/ServerSession.cpp
LibCarla/source/carla/streaming/detail/tcp/ServerSession.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/CollisionSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DVSCamera.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DataStream.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Radar.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SensorFactory.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Weather/Weather.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Weather/Weather.h

There was a posible race condition between a sensor is created and his stream of data is ready. That has been fixed, checking for the stream to be ready before using it.
Also the g-buffers has been disabled, as they doesn't work properly yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6538)

Fix sensors stream

---

Util/BuildTools/BuildCarlaUE4.bat

Fixes houdini compilation errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6601)

Houdini commit fix

---

Util/BuildTools/BuildCarlaUE4.sh

Fixes a compilation error related to houdini in Ubuntu
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6607)

Ubuntu houdini fix

---

Docs/build_linux.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6626)

fixed linux build docs

---

.readthedocs.yaml

Changed the python version to 3.7 to address ReadTheDocs build problems
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6893)

Update .readthedocs.yaml python version to 3.7

---

Docs/tutorials.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7000)

Corrected tutorials page with list

---

Docs/build_windows.md

specified CMake version 3.15 for windows build

---

Docs/adv_rss.md
Docs/tuto_A_material_customization.md
Docs/tuto_D_generate_colliders.md
Docs/tuto_G_retrieve_data.md
Docs/tuto_G_texture_streaming.md
Docs/tuto_content_authoring_maps.md

Remove excess parentheses in `carla/Docs/adv_rss.md`.
* **Platform:** Window 10

Fix some spelling errors in the document

---

Docs/tuto_A_add_vehicle.md
Docs/tuto_G_carsim_integration.md
Docs/tuto_G_pedestrian_bones.md

Replaced last AWS asset links

---

requirements.txt

https://github.com/orgs/carla-simulator/projects/5/views/1?pane=issue&itemId=51117409

Add python requirement urllib3

---

Update.bat
Update.sh
Util/BuildTools/Setup.bat

Changed urls to https to correcto working
Fixes #  

Updated http to https

---

Docs/ref_sensors.md

I updated the semantic labels used since 0.9.14 in the docs
Fixes #6902   

Update semantic labels in doc (changed from version 0.9.13 -> 0.9.14)

---

Docs/ref_sensors.md

Reverts carla-simulator/carla#7112

Revert "Update semantic labels in doc (changed from version 0.9.13 -> 0.9.14)"

---

Docs/tuto_content_authoring_maps.md

Added instructions for exporting a map package
Fixes #  

Instructions for exporting a map package

---

Docs/tuto_content_authoring_maps.md

Added package location

---

Docs/tuto_content_authoring_maps.md

fixed hyperlink

---

Docs/tuto_content_authoring_maps.md

Corrected path

---

CMakeLists.txt
Configure.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/CarlaTools.Build.cs
Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/Online/CustomFileDownloader.cpp
Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/OpenDriveToMap.cpp

- Set clang16 as default toolchain.
- Add GTest as optional dependency.
- Make SUMO, xercesc and proj, really optional via OSM2ODR flag.
- Link with Unreal libc++ instead listdc++.

Implement Ubuntu Build

---

Docs/tuto_content_authoring_maps.md

update map package instructions

---

Util/BuildTools/Setup.sh

Added timers to Setup.sh to measure
Fixes #  
* **Python version(s):** 3.7.10

Added timers to setup.sh for downloading and unzipping

---

CHANGELOG.md
Docs/build_faq.md
Util/BuildTools/BuildCarlaUE4.bat
Util/BuildTools/BuildPythonAPI.bat
Util/BuildTools/Package.bat

Make pythonapi anaconda compatible on Windows

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/JsonFileManagerLibrary.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/JsonFileManagerLibrary.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.h

- The SensorSpawnerActor has been modified so that cameras can be attached to an element.
- IMU and GNSS sensor json data can be saved.
- The Sensor class and the SceneCaptureSensor class have been modified so that PhysTick() runs on sensors even if no clients are connected. It does not run on the SceneCaptureSensor and its subclasses to avoid crashes.
- Getters have been added to the IMU and GNSS sensors to get the data that is calculated in the PhysTick().
- Added JsonFileManagerLibrary class to handle Read/Write from files.
Fixes #  
* **Platform(s):** Windows 11
* **Python version(s):** Python 3.8.10
* **Unreal Engine version(s):** UE 5.3
- Not tested on Linux.

Extended functionallity of SensorSpawnerActor

---

Docs/build_update.md
Docs/download.md
Docs/tuto_A_add_vehicle.md
Docs/tuto_G_carsim_integration.md
Docs/tuto_G_pedestrian_bones.md
Docs/tuto_content_authoring_vehicles.md
Docs/tutorials.md
README.md
Update.bat
Update.sh
Util/BuildTools/Setup.bat
Util/BuildTools/Setup.sh
Util/ContentVersions.txt
Util/CreateDebian.sh
Util/InstallersWin/install_boost.bat
Util/InstallersWin/install_libpng.bat
Util/InstallersWin/install_xercesc.bat
Util/InstallersWin/install_zlib.bat

Update urls at master branch 
Fixes #  
* **Platform(s):**  Windows && Ubuntu 20.04
* **Python version(s):**  3.8.10
Some links stop working

Update Master URLS

---

Docs/tuto_M_generate_pedestrian_navigation.md

Added warning to remove CARLA cache when rebuilding pedestrian navigation

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/Tagger.cpp
Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/WheelParentClassFixer.cpp
Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Public/WheelParentClassFixer.h

-Wheel blueprint classes fixed with a C++ editor utility actor called "WheelParentClassFixer".
-Tagger fixed to work with UE 5.3.

Antonio mata/wheel parent actor fixer

---

CHANGELOG.md
LibCarla/source/carla/client/World.cpp
LibCarla/source/carla/client/World.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.h
PythonAPI/carla/source/libcarla/World.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

Exposed IMUI Sensor gravity variable to impact Accelerometer calculus
Fixes #  

Added IMUI gravity parameter

---

Docs/adv_multigpu.md

corrected nullrhi typo

---

Docs/3rd_party_integrations.md
Docs/adv_opendrive.md
Docs/python_api.md
README.md
mkdocs.yml

fixed opendrive refs

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.cpp

Check if sensors are being listened by a client to avoid sending data if not

Check if clients are listening

---

LibCarla/source/carla/sensor/data/RadarData.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/Radar.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/Radar.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Util/JsonFileManagerLibrary.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Util/JsonFileManagerLibrary.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.h

Enable again Radar and adapt it

Re enable radar and make it work with SensorSpawnerActor

---

.gitignore
Setup.sh

This script pretends to make easier the installation process and firts build for carla.
* **Platform(s):** Ubuntu 20.04 & 22.04
* **Python version(s):** 3.8 & 3.10

Implement Environment Setup.sh

---

CMake/Options/Unreal.cmake

Hot fix to prevent cmake error when parsing CARLA_UNREAL_ENGINE_PATH
* **Platform(s):** Windows10

Fix unreal engine path option

---

CMake/Options/Common.cmake
CMake/Options/Dependencies.cmake
CMake/Options/Unreal.cmake

This PR fixes several escape character errors during CMake configure.

Fix string option escape character errors.

---

CMake/Options/Common.cmake
CMake/Options/Dependencies.cmake
CMake/Options/Unreal.cmake

This reverts commit bc5a76bfd2b06693e2dea19dfd468afc9fa6f0f8.
* **Platform(s):** Windows10
* **Python version(s):** Python 3.8

Revert pr 7291 not compiling

---

CMakeLists.txt
Unreal/CMakeLists.txt

This PR adds a check for whether CarlaUnreal Content is there.
It also changes the conditions under which a warning is issued due to the CMake build type.

Add check for CarlaUnreal Content presence.

---

CMakeLists.txt
Setup.bat

Implement Setup.bat script to install the requirements and build.
* **Python version(s):** Python 3.8

Setup.bat: Install requirements

---

Unreal/CMakeLists.txt

This PR adds a quick fix related to an incorrect target name.

Fix incorrect target name.

---

CMake/Options/Common.cmake
CMake/Options/Unreal.cmake
CMake/Util.cmake

This PR switches CMake options to a wrapper macro fer better diagnostics.

Switch to wrapper macro for options.

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Carla.Build.cs

- Copy properly ros2 native libs to the package
- Remove unnecessary carla plugin ros2 direct dependencies (this libraries should target as libcarlaros2native.so dependency not carla plugin directly).

Copy properly ros2 native libs to the package and remove unnecessary carla plugin ros2 direct dependencies

---

Setup.sh

The unnecessary use of sudo for echo .bashrc was asking the super user password more than one time to the user.

Setup.sh: Do not use sudo for modifying .bashrc

---

Util/BuildTools/Setup.sh

Change variable name to avoid syntax error. 
Fixes #7348  
* **Platform(s):** Ubuntu 20.4
* **Python version(s):** Irrelevant
* **Unreal Engine version(s):** Irrelevant

Fix Syntax Error

---

Unreal/CMakeLists.txt

Adding one cmake package generation target for each build configuration state defined on this link:
https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/DevelopmentSetup/BuildConfigurations/
```bash
cmake --build Build --target package #Same as package-Shipping
cmake --build Build --target package-Shipping
cmake --build Build --target package-Debug
cmake --build Build --target package-DebugGame
cmake --build Build --target package-Development
cmake --build Build --target package-Test
```

Add Package build configuration target

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp

* **Platform(s):**Ubuntu 22.04

Fix isvalid build error in package mode

---

Setup.bat
Setup.sh

Use the requirements.txt provided in the CarlaUE5 repo root as common description for CARLA build pip requirements.
Fixes #7360
* **Platform(s):** Ubuntu 22.04, Windows 10

Use requirement to install setup python pip

---

Setup.bat

Fix pip install commmand for Setup.bat

Fix setup bat pip install command

---

Unreal/CMakeLists.txt

Add clean to remove ue5 temp files

Add clean to remove ue5 temp files 

---

Setup.bat
Setup.sh

Before this PR:
```
CARLA_UNREAL_ENGINE_PATH=/home/carlaUE5/../UnrealEngine5_carla
```
After this PR:
```
CARLA_UNREAL_ENGINE_PATH=/home/UnrealEngine5_carla
```
Fixes [#7452](https://github.com/carla-simulator/carla/issues/7452)
* **Platform(s):** Ubuntu 22.04, Windows 10

Create CARLA_UNREAL_ENGINE_PATH environment varaible without /../

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.cpp

Possible null pointer access during master-slave synchronization（ One master and four slaves）.
Fixes #  
* **Platform(s): ubuntu 20.04
* **Python version(s): python3.8
* **Unreal Engine version(s): ue4.26

Possible null pointer access during master-slave synchronization

---

PythonAPI/carla/src/SensorData.cpp

This PR removes some debugging code left from PixelReader testing.

Remove unwanted PixelReader testing code.

---

PythonAPI/test/API/test_semantic_segmentation.py

This PR adds a test python script for semantic segmentation.

Add semantic segmentation test.

---

PythonAPI/test/API/test_no_rendering_mode.py
PythonAPI/test/API/test_sensor_recording.py
PythonAPI/test/API/test_sensor_recording_fast.py

Fixes #  
* **Unreal Engine version(s):** UE5 Carla

Adding NoRenderingMode unit test and copyright message for other unit tests

---

Setup.bat

SetupSh: Build Unreal Engine even the variable CARLA_UNREAL_ENGINE_PATH was already defined

---

Setup.bat

* **Unreal Engine version(s):**

Remove already done TODO commit

---

Setup.sh

Some times, the Unreal Engine is downloaded but not build or build fails, so we need to check if the engine was already build and build it if not.

Try build unreal engine even was already downloaded

---

.gitignore
CMake/Options.cmake
CMake/Util.cmake
CMakeLists.txt
Examples/CppClient/CMakeLists.txt
LibCarla/CMakeLists.txt
PythonAPI/CMakeLists.txt
Ros2Native/CMakeLists.txt
Ros2Native/LibCarlaRos2Native/CMakeLists.txt
Unreal/CMakeLists.txt
osm-world-renderer/CMakeLists.txt

Reverts carla-simulator/carla#7609

Revert "Introduce several helper macros and utilities for improved usability."

---

LibCarla/source/carla/ros2/ROS2.cpp
LibCarla/source/carla/ros2/ROS2.h
LibCarla/source/carla/ros2/ROS2CallbackData.h
LibCarla/source/carla/ros2/listeners/BasicListener.cpp
LibCarla/source/carla/ros2/listeners/BasicListener.h
LibCarla/source/carla/ros2/publishers/BasicPublisher.cpp
LibCarla/source/carla/ros2/publishers/BasicPublisher.h
LibCarla/source/carla/ros2/subscribers/BasicSubscriber.cpp
LibCarla/source/carla/ros2/subscribers/BasicSubscriber.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorROS2Handler.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorROS2Handler.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h

Create basic ROS2 publisher and subscriber

Ue5 ros2tutorial

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp

Enabling raytracing on SceneCaptureSensors

---

CMake/Util.cmake
LibCarla/source/carla/Version.h.in

This PR fixes a minor error in Version.h.in, which caused Version.h to be generated incorrectly.

Fix incorrect Version.h generation

---

PythonAPI/examples/ros2/ros2_native.py
PythonAPI/examples/ros2/stack.json

Added ros2 native script for testing. The script spawns the stack defined in the `stack.json` file so the user can easily add/remove sensors.
Usage:
```bash
python3 ros2_native.py -f stack.json
```
When the scripts starts the vehicle autopilot is enabled.
* **Platform(s):** Ubuntu22
* **Python version(s):** Python3.10

Added ros2 example

---

Util/BuildTools/BuildPythonAPI.sh
Util/BuildTools/Setup.sh

This PR updates `patchelf` version from `0.12`to `0.14`. Latest `auditwheel`version requires `patchelf` >= `0.14`(https://pypi.org/project/auditwheel/)
Also, this PR makes sure you use the desired python version to audit the wheel. Previously, the python system version was used.
* **Python version(s):** 3.8, 3.9, 3.10

Update patchelf version

---

Setup.sh

When UnrealEngine repo is not in the last version, pull it.

Setup.sh: Pull unreal engine if not in the last version

---

Setup.bat
Setup.sh

* **Platform(s):** Ubuntu 22.04, Windows 10
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7712)

Setup: Unreal Engine 5 path must be variable

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Weather/Sky.cpp

-Code has changed to make all the components in the skybase (except the post process, which now is the root), to be attached to the root component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7728)

Skybase slight change

---

Unreal/CarlaUnreal/Config/DefaultEngine.ini

Removed SM5 Vulkan so we can force SM6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7741)

Disable SM5 Vulkan

---

Docs/build_linux_ue5.md
Docs/build_windows_ue5.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7743)

added UE5 build instructions

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h

This PR exposes the following postprocess parameters to SceneCaptureSensor:
Color Grading / Global / Saturation
Color Grading / Global / Contrast
Color Grading/ Misc/ Tone Curve Amount
Color Grading/ Misc/ Scene Color Tint
Lens/Image Effects/Vignnete intensity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7745)

Expose extra post process options to SceneCaptureSensor

---

Docs/python_api.md
PythonAPI/docs/client.yml
PythonAPI/docs/sensor.yml
PythonAPI/docs/sensor_data.yml

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7763)

changed get_required_files docs

---

Unreal/CarlaUnreal/Config/DefaultEngine.ini
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/MapGen/SoilTypeManager.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/OpticalFlowCamera.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SensorManager.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.cpp

Add traces for debugging purposes and add engine variables
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7778)

Add traces and update engine vars

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Game/Tagger.h

Add UE5 Use Only assets to semantic tags
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7801)

Add UE5Only tags

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/DepthCamera.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/InstanceSegmentationCamera.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/NormalsCamera.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/OpticalFlowCamera.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SemanticSegmentationCamera.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/Sensor.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/ShaderBasedSensor.h

This PR fixes the OpticalFlow Sensor. It also fixes several issues related to sending non-FColor data to the client and some other minor problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7797)

Fix OpticalFlowSensor

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/MapGen/CityMapMeshHolder.cpp

This PR adds a missing include.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7804)

Add potentially missing include to Engine/Level.h

---

PythonAPI/carla/include/PythonAPI.h
PythonAPI/examples/manual_control.py

Update manual control to be able to spawn new gen vehicles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7853)

update manual control

---

README.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7937)

updated readme with advisories

---

Docs/adv_cpp_client.md
Docs/build_linux_ue5.md
Docs/cpp_client_cmake_windows.md
Docs/ref_cpp.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7942)

added cpp client build docs

---

Docs/ref_sensors.md

Fixed inconsistencies in IMU sensor docs
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7960)

fixed IMU units

---

README.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8045)

Update Ubuntu version required in README.md

---

.clangd.in
CMakeLists.txt

This PR adds basic clangd support to CARLA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8104)

Enable clangd support.

---

CMake/Common.cmake

Fix the compilation error related to encoding format in Windows11 platform
Related issues: #7907  
* **Platform(s):** Windows11
* **Unreal Engine version(s):** 5.3.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8033)

Fix compilation error in win11

---

LibCarla/source/carla/streaming/detail/tcp/Client.cpp
LibCarla/source/carla/streaming/detail/tcp/ServerSession.cpp

The slowdown is considerably more noticeable here since the engine runs much smoother. This makes evident that this is a stopgap measure, and should be looked into further down the line.
Removed parallelization of the Write functions in ServerSession and Client by stopping the use of boost post, which led to desync between client and server, and ultimately caused the leak.
Fixes #  
* **Platform(s):** Ubuntu 22
* **Unreal Engine version(s):** Unreal Engine 4
Noticeable slowdown while recording with the Python API. On my tests, both the client and the server slowed to about 6 fps while saving to disk in sync mode.
- - - …

Porting the changes done to UE5 to fix the recording leak in UE4

---

Docs/ref_sensors.md

Fixed typo in documentation `(0, 80, 100)`
Fixes #8136
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8137)

Fixed typo in `CityScapes palette`

---

CMake/Dependencies.cmake

This PR enables recast builder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8142)

Re-enable recast builder.

---

.gitignore
CMake/Dependencies.cmake

This PR fixes an issue where streetmap wasn't downloading in the correct path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8145)

Fix Streetmap download issue.

---

PythonAPI/examples/manual_control.py

This PR changes the default vehicle generation to `all`in the manual control script.
* **Unreal Engine version(s):** CARLA UE5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8149)

Changed default vehicle generation to ALL

---

Unreal/CarlaUnreal/Config/DefaultEngine.ini

This PR fixes some package errors in Windows related to PCD3D_ES31.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8157)

Remove Mobile shaders from package.

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Carla.cpp
Unreal/CarlaUnreal/Plugins/CarlaTools/Source/CarlaTools/Private/CarlaTools.cpp

Fix linker error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8169)

Fix linker error.

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderQuery.cpp

This PR adds a missing <format> include.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8174)

Add missing format include.

---

Docs/build_windows_ue5.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8225)

fix typo in title

---

Unreal/CarlaUnreal/Config/DefaultGame.ini

This PR fixes a package crash on windows platforms.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8236)

Fix package crash on Windows platforms.

---

PythonAPI/examples/ros2/ros2_native.py
PythonAPI/examples/ros2/stack.json

Small fixes for the ROS2 native demo:
* Updated vehicle blueprint to `vehicle.lincoln.mkz`
* Updated lidar frequency to `20Hz` for better visualization in `rviz`
* Set traffic manager in sync mode. Otherwise the TM controller is not working correctly.
Fixes #  
* **Unreal Engine version(s):** CARLA Unreal 5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8268)

Fixes ROS2 native demo

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/BlueprintLibary/MapGenFunctionLibrary.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/BlueprintLibary/MapGenFunctionLibrary.h

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8292)

Return sm names

---

PythonAPI/examples/invertedai_traffic.py
PythonAPI/examples/requirements.txt

Include example script with realistic data-driven traffic generation simulated by [InvertedAI](https://www.inverted.ai/home).
Only tested in Town10, expected issues in other towns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8322)

Include data-driven traffic generation with Invertedai

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8344)

Apply fix for Sensor when weather disabled

---

Docs/build_linux_ue5.md
Docs/build_windows_ue5.md
README.md
UE5_BUILD_README.md

Fixes #  
* README.md
* Docs/build_linux_ue5.md
*   Docs/build_windows_ue5.md
*  UE5_BUILD_README.md
Updated the above mark down docs to use CarlaSetup.bat and CarlaSetup.sh instead of Setup.bat and Setup.sh, which is used to install the required packages.
* **Platform(s):** Ubuntu & Windows
* **Python version(s):** 3.X
* **Unreal Engine version(s):** 5.5
* Can change the name of the script (Setup.bat/Setup.sh) in align with other branches.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8372)

Updated the Docs of CARLA UE5 build

---

.github/stale.yml

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8389)

Update stale.yml ue5-dev

---

.github/stale.yml

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8388)

Update stale bot configuration ue4-dev

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Game/Tagger.cpp

Changed _Road_  to _Roads_ in the _Tagger.cpp_, which was causing road lines to be detected as roads
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8430)

Fixed tag bug

---

PythonAPI/carla/requirements.txt
PythonAPI/examples/requirements.txt
PythonAPI/util/requirements.txt
requirements.txt

Unify numpy versions in all requirements files and ensure that it is lower than 2.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8474)

Unify numpy versions in all requirements files and ensure that it is lower than 2.0

---

Unreal/CarlaUnreal/Config/DefaultEngine.ini

Re enable virtual shadow maps cache
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8480)

Reenable virtual shadowmaps cache

---

PythonAPI/carla/agents/navigation/basic_agent.py
PythonAPI/carla/agents/navigation/local_planner.py
PythonAPI/examples/manual_control.py
PythonAPI/examples/manual_control_with_traffic.py
Unreal/CarlaUnreal/Config/DefaultGame.ini
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/VehicleActorFactory.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/VehicleActorFactory.h

Various improvements:
- Improved the python agents controller (PID and max brake)
- Removed the DVS cameras from both manual control 
- Added the semantic LIDAR to the manual_control_with_traffic
- Both manual controls now have their lights controlled by the autopilot too when active
- Fixed an issue where the mining truck was being spawned in Town10 by adding the possibility to make vehicles map specific. The exact fix will be done content side, updating the corresponding jsons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8482)

Various script improvements and fixes + map specific vehicles

---

Docs/index.md

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8498)

added note about UE5 documentation

---

LibCarla/source/carla/opendrive/parser/SignalParser.cpp

Fix typo of zOffset parameter. See #8501.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8523)

Fix spelling of zOffset parameter (#8501).

---

LibCarla/source/carla/opendrive/parser/SignalParser.cpp

UE4-side fixes for the issue #8501 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8524)

Fix zOffset typo (UE4).

---

Unreal/CarlaUnreal/Plugins/Carla/Carla.uplugin

Update plugin CARLA Version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8545)

Update Carla.uplugin version

---

.gitignore
CarlaSetup.bat
CarlaSetup.sh
Util/SetupUtils/InstallPrerequisites.bat
Util/SetupUtils/InstallPrerequisites.sh

This PR syncs CarlaSetup.bat and CarlaSetup.sh. It also fixes some issues introduced in CarlaSetup.sh in the previous PR.
Other notable changes:
- Content download is no longer asynchronous. This will be re-added in the future.
- By default, editor launch is disabled (like in CarlaSetup.bat)
- Prerequisites install is optional (like in CarlaSetup.sh).
- CarlaSetup.bat is not guaranteed to be able to support fully unattended execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8565)

Sync CarlaSetup.sh and CarlaSetup.bat.

---

CarlaSetup.sh

This PR fixes CarlaSetup.sh using "$cd" instead of the correct variable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8573)

Fix CarlaSetup.sh invalid variable.

---

PythonAPI/carla/source/carla/__init__.py
PythonAPI/carla/source/carla/command.pyi
PythonAPI/carla/source/carla/libcarla.pyi

Continuation of  #7787  and fork of #8111 without the rss stubs.
- Added `command.pyi` files
- Some support for generics, e.g. `ActorList`
- Minor signature improvements and fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8564)

[ue4] Update of type-hints - without ad-rss stubs

---

PythonAPI/examples/rss/rss_sensor.py
PythonAPI/examples/rss/rss_visualization.py

This is the rebased version of  #8123 
- Changed color coding to be like it was intended: One dynamic color value was unused and overwritten with a static one, others shared a variable and was jointly modified.
- More efficient and simpler code.
- Changed `np.matrix` to np.array code.
Note for reviewing: `np.matrix` is always two dimensional even with operations that create different shapes for `np.array` hence the swap from `np.concatenate` to `stack`.
* **Python version(s):** Python 3.10
---
#8123 Button: [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8123)
---
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

[Ue4] - Upgraded RSS example code

---

CMakePresets.json

Fix preset error related to the change in the toolchain filename.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8623)

Fix cmake preset error.

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/PathLossModel.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2XSensor.cpp

Added missing header when launching unreal editor. Otherwise the following compilation error will be reported.
```
D:/work/workspace/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/PathLossModel.cpp(176): error C3861: “DrawDebugLine”: identifier not found
D:/work/workspace/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/PathLossModel.cpp(542): error C2027: use of undefined type “URandomEngine”
D:/work/workspace/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/PathLossModel.cpp(542): error C2027: use of undefined type “URandomEngine”
D:/work/workspace/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2XSensor.cpp(189): error C2653: “UCarlaStatics”: is not a class or namespace name
D:/work/workspace/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Se …
```

added missing header

---

LibCarla/source/carla/client/Vehicle.cpp
LibCarla/source/carla/client/Vehicle.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Episode.cpp
LibCarla/source/carla/client/detail/Simulator.h
PythonAPI/carla/src/Actor.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h

Carrying over the changes from UE4
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8672)

Bone Transformation Rendering Mismatch Fix

---

Unreal/CarlaUnreal/Config/DefaultEngine.ini

Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8676)

Config Change to Enable Segmentation by Default

---

Docs/build_linux.md
Docs/build_windows.md

The current build instructions for UE4 instruct to clone the repo directly which is now by default on ue5-dev.
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8719)

Update Linux and Windows build instructions to target UE4 branch

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/BlueprintParameters.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/BlueprintActorFactory.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/BlueprintActorFactory.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/PropActorFactory.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/PropActorFactory.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/VehicleActorFactory.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/VehicleActorFactory.h
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/WalkerActorFactory.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/Factory/WalkerActorFactory.h

This PR adds derived classes for the CarlaActorFactory that add functionality already seen in the Vehicle factory, extending it to Walkers, Props and Blueprints to be configured from a JSON file found in "Carla/Config/".
There are also changes in the Blueprints to reflect this functionality, mainly the Load and Store from Json files call in editor functions. To be used, they have to be spawned in the world: loading, modifying and storing the Parameters in the instance itself and not from the blueprint editor.
Additionally, the PostProcess functions in the blueprints allow for configuration to all factory spawned actors.
* **Platform(s):** Windows 10, Linux 22
* **Unreal Engine version(s):** Unreal Engine 5
- - - …

Refactoring Carla Actor Factories to be Programmable

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp

There still some playback issue after the last fix, ex. vehicle's color are not correct.  There are issues with 
1. attribute type
2. uid
1. Attribute type is an enum type, but it's value <--> definition is changed in this [commit](https://github.com/carla-simulator/carla/commit/e349dc79c92f222750fde1dceca88188eacf8a5a) . No easy way to change it back as that commit seems to fix another previous issue. So we bump the log file version 
2. description uid is calculate from the description id(ex. vehicle.ford.crown) but only calculate from an array offset. It is not robust enough when any change to the asset happens  Change to map searching between uid <-->id and makes it more robust. 
Fixes #  
* **Platform(s):** 
* **Unreal Engine version(s):** UE4.26
- - - …

0.9.15 log playback id & attribute type issue

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp

Fix camera output after conversion of types
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8801)

Fix camera output

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8872)

Return 0exntent BB when actor is destroyed

---

Unreal/CarlaUnreal/Plugins/CarlaTools/Source/CarlaTools/CarlaTools.Build.cs
Unreal/CarlaUnreal/Plugins/CarlaTools/Source/CarlaTools/Private/BlueprintLibrary/CarlaToolsFunctionLibrary.cpp
Unreal/CarlaUnreal/Plugins/CarlaTools/Source/CarlaTools/Public/BlueprintLibrary/CarlaToolsFunctionLibrary.h

Add functionality to split meshes into chunks in editor
Fixes #  
* **Python version(s):**  3.8
* **Unreal Engine version(s):** 5.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8875)

Add functionality to subdivide meshes in chunks

---

Util/BuildTools/BuildOSM2ODR.bat
Util/BuildTools/BuildOSM2ODR.sh

Updating SUMO hashes in python script for building OSM2ODR.
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8894)

Updated Sumo Commit Hash to be correct for latest changes

---

Docs/build_linux.md

Remove the setuptools version spec from the docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8901)

Remove the setuptools version spec from the docs.

---

LibCarla/source/carla/client/DebugHelper.cpp
LibCarla/source/carla/client/DebugHelper.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.h
PythonAPI/carla/source/libcarla/World.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaStatics.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaStatics.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/CarlaTools.Build.cs

This PR aims to enable load maps from different places to be loaded and not only in Carla/Maps folder of content. 
Also enables the capability of disable draw debug strings
Fixes #8867   
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8885)

Load Maps and Remove Draw Strings

---

PythonAPI/test/smoke/test_map.py
PythonAPI/test/smoke/test_spawnpoints.py

This PR updates the smoke tests to use a specific set of maps instead of getting all available maps using `get_available_maps`.
`get_available_maps` could return maps without an OpenDRIVE file, which causes the tests to fail.
To make sure all maps are tested, new maps should be added manually to the list.
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8945)

Fix map names in smoke tests

---

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Util/GeometryImporter.cpp
Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Util/GeometryImporter.h

-Fix of include. use "BlueprintLibary/MapGenFunctionLibrary.h" instead of "Generation/MapGenFunctionLibrary.h"
-Use the actor function "Rename" instead of "SetActorLabel".
-Use "CARLA_API"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8949)

Geometry importer quick fix

---

.github/workflows/ci.yml
.github/workflows/pr.yml

This PR fixes issues with workflows triggered from external forks.
Due to security restrictions, secrets are not accessible when workflows run from forked repositories.
Since the current PR pipeline does not perform any deployment, it does not require access to secrets.
This update adapts the workflow to treat secrets as optional, allowing it to run successfully without them for the PR pipeline.
* **Python version(s):** 3.10,3.11,3.12
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8987)

[CI/CD] Fix workflows triggered from external forks

---

.github/workflows/dev.yml

FIxed a type in the windows pipeline. This type was preventing the windows artifacts to be uploaded.
* **Python version(s):** 3.12
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8997)

[CI/CD] Fix typo in windows workflow

---

.github/workflows/ue4_release.yml

UE4 release workflow placeholder (see https://github.com/carla-simulator/carla/pull/9003)
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/9012)

[CI/CD] Added UE4 release workflow placeholder

---

PythonAPI/examples/open3d_lidar.py

The LABEL_COLORS have been updated. The `open3d_lidar.py` semantic lidar
used to return IndexError out of bound, since more semantic labels have
been added to Carla. However, the example script was not updated. 
Fixes #6847 
* **Platform(s):** Ubuntu 24.04
* **Unreal Engine version(s):** (only python script was updated).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8926)

The open3d_lidar.py LABEL_COLORS have been updated.

---

PythonAPI/test/unit/test_client.py
Util/BuildTools/BuildLibCarla.bat
Util/BuildTools/BuildOSM2ODR.bat
Util/BuildTools/Environment.bat
Util/BuildTools/Environment.sh
Util/BuildTools/Setup.bat

This PR excludes Git tags from the versioning.
Additionally, it resolves an issue with make clean not working correctly on Windows.
* **Platform(s):** Ubuntu / Windows
* **Python version(s):** Python 3.12
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/9070)

Exclude tags from versioning

---

PythonAPI/examples/invertedai_traffic.py

Use argparse default formatter instead of specifically writing default values for each argument.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/9082)

Use formatter for InvertedAI defaults in help

---

LibCarla/source/carla/client/ServerSideSensor.cpp
LibCarla/source/carla/client/ServerSideSensor.h
LibCarla/source/carla/client/detail/Client.cpp
LibCarla/source/carla/client/detail/Client.h
LibCarla/source/carla/client/detail/Simulator.cpp
LibCarla/source/carla/client/detail/Simulator.h
PythonAPI/carla/source/libcarla/Sensor.cpp
PythonAPI/examples/tutorial_gbuffer.py
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SensorFactory.cpp
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp

Re enable gbuffers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/9080)

Re Enable GBuffer code

---

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp

Add logs if recast is already running when loading new episode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/9089)

Close proc if its already running before launch it
