Docs/faq.md, Docs/troubleshooting.md, Setup.sh, Update.sh
Added the `-s` and `--skip-download` options to "Update.sh" and "Setup.sh". This way people having troubles downloading the 10GB of content can manually download this file, possibly from somewhere else, and run setup.
=> Add option to skip content download

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/CityMapGenerator.cpp
While iterating the graph I was adding road both for a half-edge and its pair. Now I keep a count of the edges (and its pairs) that have being visited and skip the visited ones.
Fix #221.
* **Unreal Engine version(s):** 4.17.2
=> Fix road map generator generates duplicated meshes

PythonClient/carla/sensor.py, PythonClient/client_example.py, PythonClient/manual_control.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Lidar.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/LidarMeasurement.h
* Fixes #290 Crash when requesting too few Lidar points.
* Fixes Lidar points were sent in centimeters.
* Fixes some Lidar examples had incorrect units.
* **Python version(s):** 2.6, 3.5
=> Fix crash in Lidar

PythonClient/client_example.py, PythonClient/manual_control.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/VehicleSpawnerBase.cpp
Added a switch to set the quality level of the simulation in both `client_example.py` and `manual_control.py`.
* **Python version(s):** 2.7, 3.5
=> Add quality level switch to python client examples

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/ServerGameController.cpp
Fix the race condition between the client and server that causes the server
to reset the connection.
Now disconnect errors in ports 2001 and 2002 are ignored.
Fixes #297.
=> Fix race condition

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaVehicleController.cpp
Bounding box was scaled twice when computing map intersection (bounding box transform already contains an scale).
Fixes #371.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/372)
=> Fix bounding box was scaled twice when computing map intersection

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp
Fix #396 
Now we don't get all the actors primitive components for landscapes actors or instancedfoliage actors to apply the max culling distance to them when the settings quality changes.
* **Platform(s): Windows 10 x64
* **Unreal Engine version(s):** 4.18.3
Foliage models should now define a max distance for culling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/397)
=> Changes in CarlaSettingsDelegate so it wont apply max distance culling to foliage in Low mode

.travis.yml, PythonClient/carla/carla_server_pb2.py, PythonClient/client_example.py, PythonClient/manual_control.py, PythonClient/view_start_positions.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Lidar.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaEncoder.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaEncoder.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/ServerGameController.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.h, Util/CarlaServer/include/carla/carla_server.h, Util/CarlaServer/source/carla/server/CarlaEncoder.cpp, Util/CarlaServer/source/test/Test_CarlaServer.cpp, Util/Proto/carla_server.proto
Adds an extra string to the scene description message with the current map name. I also updated `view_start_positions.py` and `manual_control.py` to use it.
Fixes #313.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/358)
=> Include map name in scene description message

Docs/how_to_build_on_linux.md, Jenkinsfile, Setup.sh
A couple of measures to speed up the _Setup.sh_ script.
* Added an option to run the `make` commands with multiple async jobs.
* Boost only compiles the used libraries, `system`.
It runs now in about 5min30s in our build machine (before it was 12min) :+1:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/408)
=> Speed up setup script

PythonClient/carla/settings.py, PythonClient/test/acceptance_tests/test_map_changing.py
Hello @juaxix,
Thanks for the very useful feature of map changing on client side !
First of all, I added on carla/settings.py the possibility of changing the map name
on the carla settings code. Quite trivial.
Now about the tests.
At first it seemed to be working correctly. I was able to start CARLA on Town01 and execute
tests on Town02. However I decided to make a test to stress this map change since it is a very
important functionality.
For that, I created the acceptance_test called " test_map_changing.py"
Basically, what it does is changing maps from Town01 to Town02 and then Town02 to Town01 ...
repeating this process 8 times. At each time it asserts if the map name received is the same
as the map loaded by the client. 
What happens is the following:
It starts on town 01 , receives …
=>  Adding unit/acceptance test for map changing

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaPlayerState.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaPlayerState.h
The fixed time-step mode keeps generating a lot of confusion. I think partly because of using the term FPS for both modes while they're not exactly the same (frames-per-simulation-second vs frames-per-real-second). While we cannot change the command line args because they're handled by UE4, at least we can change the HUD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/478)
=> Change HUD: replace "FPS" by "Simulation Step"

Package.sh, Util/Docker/Release.Dockerfile
Adding the Dockerfile provided by @germanros1987 to the repo.
I changed _Package.sh_ to include the Dockerfile automatically on each new release.
Download and extract the [release package](http://158.109.9.218:8080/blue/organizations/jenkins/carla/detail/PR-481/1/artifacts), and on that folder
```
$ docker build -t carla -f Dockerfile .
$ docker run -p 2000-2002:2000-2002 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 carla:latest ./CarlaUE4.sh  /Game/Maps/Town01 -benchmark -carla-server -fps=10 -world-port=2000 -windowed -ResX=100 -ResY=100 -carla-no-hud
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/481)
=> Add Dockerfile for running Carla releases

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.cpp
This modifies the autopilot to look at the front wheels position while following way-points. This makes the turns at intersections more coherent among vehicles independently of their length.
**Important: This requires the latest changes in the map, as the intersections have been slightly adapted to the new behavior. This changes will be made public with the 0.8.4 release.**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/507)
=> Change autopilot to turn at intersections based on front wheels position

PythonClient/carla/driving_benchmark/metrics.py, PythonClient/carla/driving_benchmark/recording.py, PythonClient/test/unit_tests/test_recording.py
On Driving Benchmark:
Fixing a newly found bug that made the writing on the csv
to go on different order when RESTARTING the benchmark process
or when using in a subprocess.
* **Platform(s):**  16.04 ubuntu linux
* **Python version(s):**  python3.6, python 2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/514)
=> Fix dictionary order issue on driving benchmark

Docs/python_api.md, LibCarla/source/carla/client/ActorAttribute.h, LibCarla/source/carla/client/ActorBlueprint.h, PythonAPI/source/libcarla/Blueprint.cpp
Added a way of iterating all the attributes of an actor blueprint, the following code now works
```py
for blueprint in blueprint_library:
print(blueprint)
for attribute in blueprint:
print('  - %s' % attribute)
```
Also does minor improvements to the Python prints of blueprint related objects.
Fixes #702.
* **Python version(s):** Python 2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/736)
=> Allow iterating attributes of an Actor's Blueprint

Util/BuildTools/BuildLibCarla.bat, Util/BuildTools/BuildPythonAPI.bat
For "CarlaLIB" and "PythonAPI" don't check if the a build already exists, as the build check is done by the compiler and installation check is done by CMake.
* **Platform(s):** Windows 10 x64 1803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/762)
=> Remove install folder path check

Docs/Example.CarlaSettings.ini, PythonClient/carla/settings.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettings.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaVehicleController.cpp
Changes to enable or disable rendering of the world (Unreal render) and CARLA HUDs (Unreal HUD rendering) using a property of the server settings.
The changes involve:
- Tests needed
Using the code for manual_control.py, with this modification:
```py
def make_carla_settings(args):
"""Make a CarlaSettings object with the settings we need."""
settings = CarlaSettings()
settings.set(
SynchronousMode=True,
SendNonPlayerAgentsInfo=True,
NumberOfVehicles=15,
NumberOfPedestrians=30,
WeatherId=random.choice([1, 3, 7, 8, 14]),
QualityLevel=args.quality_level,
DisableRendering=True)
settings.randomize_seeds()
if args.lidar:
lidar = sensor.Lidar('Lidar32')
lidar.set_position(0, 0, 2.5)
lidar.set_rotation(0, 0, 0)
lidar.set(
Channels=32,
Range=50,
PointsPerSecond=100000,
RotationFrequency=10, …
```
=> Non-rendering mode

.travis.yml, Docs/carla_docker.md, Docs/index.md, mkdocs.yml
Adding a tutorial for the CARLA docker.
CARLA 0.8.4
Docker's pull using 
docker pull carlasim/latest
Was not working for me. We should probably add docker pull carlasim/stable
and docker pull carlasim/latest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/616)
=>  adding a docker tutorial

Docs/python_api.md, LibCarla/source/carla/Time.h, LibCarla/source/carla/client/Client.h, PythonAPI/example.py, PythonAPI/manual_control.py, PythonAPI/source/libcarla/Client.cpp
- Change Python client timeout to float seconds for convenience.
- Add timeout to manual_control.py.
Related #809, by adding a timeout to the manual control script we avoid blocking the GIL forever.
* **Python version(s):** Python 2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/819)
=> Change timeout to use seconds in Python and add timeout to manual control

Unreal/CarlaUE4/.gitignore
Now `\Unreal\CarlaUE4\Content\` folder is ignored again, but git will track `\Unreal\CarlaUE4\Plugins\Carla\Content\`.
Fixes #804
* **Platform(s):** Win10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/827)
=> Fixed .gitignore not ignoring the Content

LibCarla/source/carla/streaming/detail/tcp/ServerSession.cpp, LibCarla/source/test/test_benchmark_streaming.cpp
Requires #750.
See description and comments in #815.
I have removed the part that "re-posts" a message when the socket is busy. Now it simply ignores the message. It is a bit drastic but reduces latency on client considerably when connection is slow, plus this won't be a problem once we enable the synchronous mode.
I have also tweaked the unit tests to reflect that we can miss messages.
Fixes #815.
* **Platform(s):** Ubuntu 16.04 and Windows 10
Some messages are lost if the connection is too slow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/854)
=> Fix client receives interleaved sensor messages

Unreal/CarlaUE4/Config/DefaultEngine.ini
Fixes the issue of textures loading only in low quality in the camera sensors (images retrieved in the Python API).
May reduce performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/913)
=> Disable texture streaming

Docs/python_api.md, LibCarla/source/carla/client/DebugHelper.cpp, LibCarla/source/carla/client/DebugHelper.h, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/rpc/Color.h, LibCarla/source/carla/rpc/DebugShape.h, LibCarla/source/carla/rpc/Variant.h, LibCarla/source/carla/sensor/data/Color.h, PythonAPI/source/libcarla/World.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/TheNewCarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/DebugShapeDrawer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/DebugShapeDrawer.h
Allow drawing debug primitives from Python API, some examples
```py
world.debug.draw_point(carla.Location(1,2,3))
world.debug.draw_line(carla.Location(), carla.Location(x=10), color=carla.Color(0, 255, 0))
world.debug.draw_string(carla.Location(z=4), "Hello!")
```
Draw bounding box
```py
transform = vehicle.get_transform()
bounding_box = vehicle.bounding_box
bounding_box.location += transform.location
world.debug.draw_box(bounding_box, transform.rotation)
```
```py
draw_point(location, size=0.1, color={Red}, life_time=-1.0, persistent_lines=True)
draw_line(begin, end, thickness=0.1, color={Red}, life_time=-1.0, persistent_lines=True)
draw_arrow(begin, end, thickness=0.1, arrow_size=0.1, color={Red}, life_time=-1.0, persistent_lines=True)
draw_box(box, rotation, thickness=0.1, color={Red}, …
```
=> Allow drawing UE4 debug shapes from Python API

Util/BuildTools/Setup.sh, Util/InstallersWin/install_rpclib.bat
We observed a crash when the client disconnects during an rpc call. It seems to be fixed by https://github.com/rpclib/rpclib/pull/167.
I have upgraded rpclib to the commit that fixes this.
@iFuSiiOnzZ Please check the Windows script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/928)
=> Upgrade rpclib to fix crash when client exits too fast

LibCarla/source/carla/opendrive/OpenDrive.cpp, LibCarla/source/carla/road/MapBuilder.h, LibCarla/source/carla/road/element/RoadSegment.h, LibCarla/source/carla/road/element/Types.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDriveActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/RoutePlanner.cpp
Currently given a lane from a road segment there is no way to know which is the next or previous lane. The missing information has been added as is needed for the PythonAPI.
Each road section has a function called `GetNextLane` and `GetPrevLane` that accepts as input the current lane and return a vector of pairs where the first element of the pair is the next lane id and the second one the next road id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/938)
=> Road lane next prev

Docs/python_api.md, LibCarla/source/carla/client/TrafficLight.cpp, LibCarla/source/carla/client/TrafficLight.h, LibCarla/source/carla/client/Vehicle.cpp, LibCarla/source/carla/client/Vehicle.h, LibCarla/source/carla/client/detail/EpisodeState.h, LibCarla/source/carla/rpc/TrafficLightState.h, LibCarla/source/carla/sensor/data/ActorDynamicState.h, PythonAPI/source/libcarla/Actor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorRegistry.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorView.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DepthCamera.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficSignBase.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h
Added the vehicle control struct (throttle, steer, brake, ...) to the actors' state that is sent every tick. Now the last control applied to a vehicle (autopilot or otherwise) can be retrieved in Python with the `get_vehicle_control()` method of vehicles.
Also moved traffic light state to rpc so it can be serialized as part as the "type dependent dynamic state" of actors.
The world observer message becomes bigger thus may reduce performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/954)
=> Send vehicle control to client

CMakeLists.txt, Docs/how_to_build_on_linux.md, LibCarla/cmake/CMakeLists.txt, LibCarla/cmake/client/CMakeLists.txt, LibCarla/cmake/server/CMakeLists.txt, LibCarla/cmake/test/CMakeLists.txt, Util/BuildTools/Setup.sh
No feature of cmake newer than 3.5 is used. Therefore, we can use
cmake 3.5, which is also standard in Ubuntu 16.04, whereas cmake 3.9
is non-standard.
Checklist:
Where has this been tested?
* **Python version(s):** Python 2.7
* **Unreal Engine version(s):** Unreal 4.19
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/980)
=> Change cmake version from 3.9 to 3.5

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorAttribute.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/OpenDrive.cpp
Depending on the included headers sometimes the compilation was failing giving errors as ` {instrinsic funtion} is not a member of {class name}` or some Unreal functions as `GetObject` was replaced by the `GetObjectW` macro of Windows. So to fix the problem some of the general Unreal includes and some other unused includes have been removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/988)
=> Fix win32 compilation

LibCarla/source/carla/opendrive/OpenDrive.cpp, LibCarla/source/carla/road/element/Geometry.h, LibCarla/source/carla/road/element/RoadInfo.h, LibCarla/source/carla/road/element/RoadInfoVisitor.h, LibCarla/source/carla/road/element/RoadSegment.h, LibCarla/source/carla/road/element/Waypoint.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDriveActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDriveActor.h
Improved the integration with OpenDrive:
- **Python API**: Now you can get the height and rotation of the waypoints.
- **OpenDriveActor**: Now spawns trigger boxes with the correct map elevation.
- **OpenDriveActor**: Disabled `AddSpawners` by default.
Nothing found
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1031)
=> Opendrive elevation

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/geom/Location.h, LibCarla/source/carla/geom/Math.cpp, LibCarla/source/carla/geom/Math.h, LibCarla/source/carla/geom/Rotation.h, LibCarla/source/carla/geom/Transform.h, LibCarla/source/carla/geom/Vector3D.h, LibCarla/source/test/test_geom.cpp, PythonAPI/source/libcarla/Geom.cpp, PythonAPI/source/libcarla/libcarla.cpp
Required by #748.
Added a convenient method to compute the forward vector of a rotation (unit vector pointing towards the X-axis of the rotation). The method is also exposed to Python API.
Since I was there I also uncrustified and organised the geom classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1145)
=> Add get_forward_vector to rotation and transform

CHANGELOG.md, Docs/build_system.md, LibCarla/source/carla/image/BoostGil.h, LibCarla/source/carla/image/ImageIOConfig.h, LibCarla/source/compiler/disable-ue4-macros.h, Util/BuildTools/Setup.sh, Util/InstallersWin/install_boost.bat
Continuing with @praveen-palanisamy's PR #947.
- Updated the `Setup.sh` script to define the boost version in one place and use it appropriately in all other places
- Upgraded the boost version to 1.69.0 as lower versions have been reported to have build issues
- Upgraded image IO methods as there have been changes to boost::gil IO methods
- Suppressed new compiler warnings inside Boost libs
- Fixes #875 
- Fixes #881 
Boost is used thoroughly across the project so we can't discard it broke something, but tests are passing and basic functionality works.
--- …
=> Upgrade Boost to 1.69

CHANGELOG.md, Docs/cameras_and_sensors.md, Docs/python_api.md, LibCarla/source/carla/client/GnssSensor.cpp, LibCarla/source/carla/client/GnssSensor.h, LibCarla/source/carla/client/Map.cpp, LibCarla/source/carla/client/Map.h, LibCarla/source/carla/client/detail/ActorFactory.cpp, LibCarla/source/carla/opendrive/OpenDrive.cpp, LibCarla/source/carla/opendrive/parser/OpenDriveParser.h, LibCarla/source/carla/opendrive/types.h, LibCarla/source/carla/road/MapBuilder.h, LibCarla/source/carla/road/MapData.h, LibCarla/source/carla/sensor/SensorRegistry.h, LibCarla/source/carla/sensor/data/GnssEvent.h, PythonAPI/manual_control.py, PythonAPI/source/libcarla/Sensor.cpp, PythonAPI/source/libcarla/SensorData.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.h
An initial reference location is read from the header of the OpenDRIVE definition (/OpenDRIVE/header/geoReference)
The expected format is based on the Proj4 syntax:
+lat_0=<LATITUDE as double> +lon_0=<LONGITUDE as double)
Example (Town01):
<OpenDRIVE>
<header revMajor="1" revMinor="4" name="" version="1" date="2018-10-26T12:17:35" north="2.0479999989271146e+1" south="-3.4888998413085938e+2" east="4.1446086126736287e+2" west="-2.0712774024007370e+1" vendor="VectorZero">
<geoReference><![CDATA[+lat_0=4.9000000000000000e+1 +lon_0=8.0000000000000000e+0]]></geoReference>
</header>
...
Fixes #  
--- …
=> Add support for a gnss sensor

CHANGELOG.md, Unreal/CarlaUE4/Config/DefaultGame.ini, Util/BuildTools/Package.sh
Remove UE4 crash reporter from the packaged version.
By default UE4 includes a crash reporter in packaged builds, however since we don't use it, it's only causing noise in the output and stalling the simulator after a crash.
Related to #1111.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1176)
=> Remove crash reporter

CHANGELOG.md, PythonAPI/manual_control.py, PythonAPI/no_rendering_mode.py
- Fixes the bug in `manual_control.py` and `no_rendering_mode.py` to avoid crashes due to:
```bash
OverflowError: cannot convert float infinity to integer
Segmentation fault (core dumped)
```
(See #1217  for more information)
Fixes #1217
* **Python version(s):** 3.6, 3.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1218)
=> Fixes #1217 to prevent crashes when run in no-rendering mode

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp
Make possible to control movable objects already present in the map, e.g. chairs and tables in Town01
```python
props = [(x, x.get_transform()) for x in world.get_actors().filter("static.prop*")]
for actor, _ in props:
actor.add_impulse(carla.Vector3D(z=1.5))
actor.set_angular_velocity(carla.Vector3D(z=14000))
time.sleep(0.3)
for actor, _ in props:
actor.set_simulate_physics(False)
time.sleep(3)
for actor, transform in props:
actor.set_transform(transform)
```
What I did is parsing the scene at begin play and adding every static mesh that is movable to the actor registry so they're visible in the API as actors.
If art team forgets to set an unwanted object as "static" in UE4Editor, this object will show up in the API.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Add movable static meshes to the actor registry

CHANGELOG.md, LibCarla/source/carla/RecurrentSharedFuture.h, LibCarla/source/carla/client/TimeoutException.cpp, LibCarla/source/carla/client/TimeoutException.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Episode.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/test/client/test_recurrent_shared_future.cpp
- Improved time-out error messages, now instead of an rpc error you get the following message
```
RuntimeError: time-out of 2000ms while waiting for the simulator, make sure
the simulator is ready and connected to 127.0.0.1:2000
```
- Print same error message if we meet the time-out in `world.wait_for_tick` (RecurrentSharedFuture), previously the message was very cryptic.
- Wait for tick after subscribing to the world observer to have the world ready after `client.get_world()`, solves issues of having an empty list when calling `world.get_actors()` right after creating the world.
Fixes #1151.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1257)
=> Improve time-out error messages and fix 1151

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/client/Waypoint.cpp, LibCarla/source/carla/client/Waypoint.h, LibCarla/source/carla/geom/CubicPolynomial.h, LibCarla/source/carla/geom/Transform.h, LibCarla/source/carla/opendrive/OpenDrive.cpp, LibCarla/source/carla/opendrive/parser/LaneParser.cpp, LibCarla/source/carla/opendrive/parser/LaneParser.h, LibCarla/source/carla/opendrive/types.h, LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/road/WaypointGenerator.cpp, LibCarla/source/carla/road/WaypointGenerator.h, LibCarla/source/carla/road/element/RoadInfo.h, LibCarla/source/carla/road/element/RoadInfoLaneOffset.h, LibCarla/source/carla/road/element/RoadInfoLaneWidth.h, LibCarla/source/carla/road/element/RoadInfoMarkRecord.h, LibCarla/source/carla/road/element/RoadInfoVisitor.h, LibCarla/source/carla/road/element/RoadSegment.h, LibCarla/source/carla/road/element/Waypoint.cpp, LibCarla/source/carla/road/element/Waypoint.h, LibCarla/source/test/common/test_road.cpp, PythonAPI/lane_explorer.py, PythonAPI/source/libcarla/Map.cpp
Extended the waypoint API with new functions:
- `carla.Waypoint.lane_change`: Returns a `carla.LaneChange`.
- `carla.LaneChange`: A Python enum that tells whether traffic rules allow a lane change.
+ 0: `None`
+ 1: `Right`
+ 2: `Left`
+ 3: `Both`
+ Can be used as a flag i.e.:
* `LaneChange.Right & LaneChange.None => False`
* `LaneChange.Right & LaneChange.Left => False`
* `LaneChange.Right & LaneChange.Both => True`
* `LaneChange.Right & LaneChange.Right => True`
- `carla.Waypoint.lane_type`: Returns an string that codifies the type of the current lane, i.e.: `"driving", "bidirectional", "shoulder", "sidewalk", "median", "parking", "none", ...`
- `carla.Waypoint.right_lane()`: Returns another `carla.Waypoint` (although the rules allow the change or not) at the closest right neighbor lane. …
=> Waypoint API extended

CHANGELOG.md, Util/Docker/Release.Dockerfile
- Fixed error in run arguments documentation
- Modified package installation to recommended, non-polluting variant
- Unified COPY and chown steps which halves the image size
- Removed installing sudo
* **Platform(s): Ubuntu 16.04, Docker
* **Python version(s): - 
* **Unreal Engine version(s): - 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1318)
=> Simplify Dockerfile and halve image size

CHANGELOG.md, LibCarla/source/carla/streaming/EndPoint.h
- Allows usage of hostnames instead of IP addresses only
with carla::Client
carla::Client (and all derived Python clients) can now use hostnames as parameter for the simulator host and not just IP addresses.
* **Platform(s): Ubuntu 16.04
* **Python version(s): Python 2.7
* **Unreal Engine version(s): - 
Not aware of any.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1326)
=> Resolve hostname for streaming client

CHANGELOG.md, Util/InstallersWin/install_libpng.bat
Some people had issues with the following error while running the client:
```
ImportError: DLL load failed: The specified module could not be found.
```
This is an issue with `zlib` that was not correctly statically linked.
A workaround was putting a x64 `zlib.dll` on `carla/PythonAPI` folder.
This is not necessary anymore because `zlib` is correctly statically linked now.
Fixes #1345
* **Platform(s):** Win10
* **Python version(s):** 3.x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1350)
=> Zlib correctly statically linked

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/client/GnssSensor.cpp, LibCarla/source/carla/client/GnssSensor.h, LibCarla/source/carla/client/Map.cpp, LibCarla/source/carla/client/Map.h, LibCarla/source/carla/geom/GeoLocation.cpp, LibCarla/source/carla/geom/GeoLocation.h, LibCarla/source/carla/opendrive/parser/GeoReferenceParser.cpp, LibCarla/source/carla/opendrive/parser/GeoReferenceParser.h, LibCarla/source/carla/opendrive/parser/OpenDriveParser.cpp, LibCarla/source/carla/opendrive/parser/OpenDriveParser.h, LibCarla/source/carla/opendrive/types.h, LibCarla/source/carla/road/MapBuilder.h, LibCarla/source/carla/road/MapData.h, LibCarla/source/carla/sensor/data/GnssEvent.h, PythonAPI/source/libcarla/Geom.cpp, PythonAPI/source/libcarla/Map.cpp, PythonAPI/source/libcarla/SensorData.cpp
Refactored a bit the code to reuse the functionality in GNSS sensor, moved the parsing to the OpenDrive parser and the geo-location transformation to the new GeoLocation class so we can easily convert Locations (x, y, z) to GeoLocations (latitude, longitude, altitude).
Add `transform_to_geolocation` to the Python API's Map so we can convert any location to the GNSS coordinates without parsing the OpenDrive file
```py
geoloc = map.transform_to_geolocation(location)
```
and also exposed the GeoLocation class in Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1355)
=> Add method to Map to transform Location to GeoLocation

CHANGELOG.md, LibCarla/source/carla/client/Waypoint.h, LibCarla/source/carla/road/element/RoadInfo.h, LibCarla/source/carla/road/element/Waypoint.h, LibCarla/source/carla/road/element/WaypointHash.cpp, LibCarla/source/carla/road/element/WaypointHash.h, PythonAPI/source/libcarla/Map.cpp
Added a hash function for waypoints taking into account its road_id, lane_id, and "s" offset. The "s" offset is truncated to half centimetre precision.
I have also added the "s" property to waypoints, that was the last piece missing to uniquely identify a waypoint in the OpenDrive format.
Theoretically, the hash could have collisions as we are hashing to 64 bits, but unlikely enough, about 1 in 10^5 for the typical amount of waypoints you can generate in our cities. There aren't collisions in our current towns, I tested to be sure :grin:.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1365)
=> Add waypoint id and s

LibCarla/source/carla/streaming/EndPoint.h
Fixes resolving "localhost" host for Carla client.
This canonical name for a local loopback was no longer resolvable
with the latest changes allowing hostname lookup.
* **Platform(s):** Ubunutu 16.04
* **Unreal Engine version(s):** 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1354)
=> Fix resolving host "localhost"

CHANGELOG.md, Docs/cameras_and_sensors.md, Docs/python_api.md, LibCarla/source/carla/client/GnssSensor.cpp, LibCarla/source/carla/client/LaneDetector.cpp, LibCarla/source/carla/sensor/RawData.h, LibCarla/source/carla/sensor/SensorData.h, LibCarla/source/carla/sensor/data/GnssEvent.h, LibCarla/source/carla/sensor/data/LaneInvasionEvent.h, LibCarla/source/carla/sensor/s11n/SensorHeaderSerializer.cpp, LibCarla/source/carla/sensor/s11n/SensorHeaderSerializer.h, PythonAPI/source/libcarla/SensorData.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/AsyncDataStream.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/CollisionSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DataStream.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp
Until now SensorData only had the frame_number. This might be sufficient for a lot of use cases, but it's a pain to work with in ROS (using the carla-ros-bridge)
ROS is reliant on time, e.g. transforms (ros-tf) are calculated by specifying a time.
The workaround to match a specific frame_number with the time would be cumbersome. Therefore the timestamp is now added to SensorData.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1348)
=> Add timestamp to SensorData

LibCarla/source/carla/sensor/SensorData.h, LibCarla/source/carla/sensor/data/RawEpisodeState.h, LibCarla/source/carla/sensor/s11n/EpisodeStateSerializer.h, PythonAPI/test/smoke/test_sync.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/AsyncDataStream.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/CollisionSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/CollisionSensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/DataStream.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SensorFactory.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp
Make sensors use timestamp from UCarlaEpisode instead of UWorld. The latter stores the value in a float accumulating greater error.
Fixes #1381.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1395)
=> Fix discrepancy between timestamps

CHANGELOG.md, PythonAPI/agents/navigation/local_planner.py
If the local_planner is used by other Python modules the cleanup causes
a destruction of the actor, handed over to the local_planner. As this
may be undesired, an additional reset_vehicle() method was added to the
local_planner.
Checklist:
* **Python version(s):** 2.7, 3.5
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1396)
=> Fix cleanup local_planner when used by other modules

.gitignore, CHANGELOG.md, Update.sh, Util/BuildTools/Setup.bat, Util/ContentVersions.txt
Migrated Update.sh to download the Content from AWS. Download is a bit slower than Google Drive, but should solve issues related to reaching download quota limit each weekend.
If installed, it will use `aria2c` to speed up download, otherwise wget.
In parallel to this I have created a Jenkins pipeline to the Content repo that automatically uploads the package to AWS.
* Fixes #1180.
* Maybe #84?
Uhm possibly a lot, but let's try and see how it works, rolling back to Google Drive is fairly easy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1415)
=> Migrate Content to AWS

CHANGELOG.md, PythonAPI/manual_control.py
When using the ROS bridge the role_name is used to differentiate between hero vehicles. For every hero vehicle another set of ROS topics is available.
To allow easy testing with multiple hero vehicles within the ROS context, a parameter `--rolename` is added to `manual_control.py`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1429)
=> Add rolename parameter to manual_control

PythonAPI/scene_layout.py
Adding the static props to the dict of dynamic objects.
For some reason the type_id was not printing the prop name, the same was not true when spawning it. After you get it it lose the ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1437)
=> Adding static props to the scene layout parser

CHANGELOG.md, LibCarla/source/carla/client/ActorList.cpp, LibCarla/source/carla/client/ActorList.h
- change return type to SharedPtr<ActorList>
- this fixes tr1::bad_weak_ptr when using / iterating filtered list
Iterating a ActorList aquired by anotherActorList->Filter(...) cause tr1::bad_weak_ptr exceptions to be thrown.
Changing the return type to SharedPtr<ActionList> fixes that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1445)
=> Fix ActorList.Filter(...) method

CHANGELOG.md, Docs/cameras_and_sensors.md, LibCarla/source/carla/client/GnssSensor.cpp, LibCarla/source/carla/client/LaneInvasionSensor.cpp, LibCarla/source/carla/client/LaneInvasionSensor.h, LibCarla/source/carla/client/detail/ActorFactory.cpp, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/sensor/SensorRegistry.h, PythonAPI/automatic_control.py, PythonAPI/manual_control.py, PythonAPI/manual_control_steeringwheel.py, PythonAPI/source/libcarla/Sensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/LaneInvasionSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/LaneInvasionSensor.h
- Fix naming: Use 'LaneInvasionSensor'/'lane_invasion' instead of mixture with 'LaneDetector'/'lane_detector'
- Create server-side LaneInvasionSensor (to be able to access it via ROS bridge)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1450)
=> LaneInvasionSensor stabilization

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/RoutePlanner.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/RoutePlanner.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.cpp
If the simulator is running at high FPS the following snippet may fail
```py
vehicle = world.spawn_actor(bp, transform)
vehicle.set_autopilot()
```
The reason, currently we use a finely tuned combination of trigger boxes and spawn points placed on top of them(*), if the "set autopilot" message arrives after the vehicle has fallen inside the trigger box the waypoints are not assigned to its controller.
I've made the controllers check if they're inside a route planner when the autopilot is enabled, and retrieve a route if so.
(*) Workaround for reusing the old autopilot we newer OpenDrive based navigation.
This adds quite some overhead to the "set autopilot" function, but isn't called very often. Hopefully we'll get rid of the old autopilot system soon anyway.
--- …
=> Fix vehicles missing the route if autopilot enabled too late

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/Overload.h, LibCarla/source/carla/client/Client.h, LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Episode.cpp, LibCarla/source/carla/client/detail/Episode.h, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/rpc/Command.h, LibCarla/source/carla/rpc/CommandResponse.h, PythonAPI/carla/source/libcarla/Client.cpp, PythonAPI/carla/source/libcarla/Commands.cpp, PythonAPI/carla/source/libcarla/World.cpp, PythonAPI/examples/spawn_npc.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/TheNewCarlaServer.cpp
Added methods to spawn actor in batch mode, reducing the number of accidents related to vehicles spawning on top of each other.
* Added new `carla.command.SpawnActor` to spawn actors in batch
* Added method `client.apply_batch_sync` that waits for server response
* Updated `spawn_npc.py` to spawn vehicles in batch
The `SpawnActor` command also accepts queuing commands to be applied to the newly spawned actor.
```py
batch.append(
SpawnActor(blueprint, transform).then(
SetAutopilot(FutureActor, True)).then(
ApplyVelocity(FutureActor, Vector3D(z=5))))
```
`spawn_npc.py` has been updated to spawn all the vehicles in batch, but now it does not support spawning more vehicles than spawn points. This is probably a good thing due to the amount of accidents that it was producing.
---
This change …
=> Spawn actors in batch

PythonAPI/carla/agents/navigation/global_route_planner.py
Fixes #  
This happened to be a floating point imprecision issue from np.linalg functions.
Clipped math.acos inputs between -1 and 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1528)
=> Fixed out of domain input problem

Update.sh
the update is a very costly operation and it downloads ~6gb every time. 
many time this download get interrupted and again the same file needs to be downloaded from the beginning.
to avoid this  -c argument is added to `wget`.
this will help in continuing download from the point it was interrupted previously.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1559)
=> added -c to wget to recover the interrupted download

CHANGELOG.md, PythonAPI/examples/no_rendering_mode.py
Fixes a bug related with a Pygame limitations. Pygame tends to throw an error when the surface size is too large, so now the towns are adapted to the maximum size of a Pygame surface. Also, more zoom out will be provided. 
Fixes #  
* **Platform(s):** Ubuntu 16.04LTS
* **Python version(s):** 2.7.12 and 3.5.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1657)
=> Fixed pixel per meter size and enabled more zoom out

Unreal/CarlaUE4/Config/DefaultGame.ini, Util/BuildTools/Package.sh
Include debug information in the packaged build, this will help us a lot debugging as we get now a complete call stack.
Just to be sure, I have run the benchmark with and without debug symbols and there no noticeable loss.
[benchmark_debug.log](https://github.com/carla-simulator/carla/files/3198975/benchmark_debug.log)
[benchmark_no_debug.log](https://github.com/carla-simulator/carla/files/3198976/benchmark_no_debug.log)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1659)
=> Include debug info in packaged version

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/rpc/AttachmentType.h, PythonAPI/carla/source/libcarla/World.cpp, PythonAPI/examples/manual_control.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ActorAttacher.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ActorAttacher.h
Added a new attachment mode "Spring Arm" for a more cinematic feeling.
https://youtu.be/Iwfn58NJpTE
It can be specified when spawning an actor
```py
camera = world.spawn_actor(
camera_blueprint, 
transform, 
attach_to=vehicle,
attachment_type=carla.AttachmentType.SpringArm)
```
If not specified, `attachment_type` defaults to `carla.AttachmentType.Rigid`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1682)
=> Allow attaching actors with a spring arm

CHANGELOG.md, Docs/cameras_and_sensors.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h
Add new attribute to RGB camera blueprint: "gamma". It controls the target gamma of the render target of the camera. Defaults to 2.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1720)
=> Add gamma value as attribute to RGB camera

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/WheeledVehicleAIController.h
*  `AWheeledVehicleAIController` derive from `AController` instead of `APlayerController` to avoid having player overhead.
* Tick autopilot only if autopilot is enabled. We've been carrying this since 0.8.x version where it was always required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1726)
=> Vehicle controller fixes

CHANGELOG.md, LibCarla/source/carla/road/Map.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/FBXImport/MapProcessCommandlet.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaStatics.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveActor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveMap.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveMap.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDriveActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/OpenDrive.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/OpenDrive.h
Created a new class "OpenDriveMap" accessible from blueprints that allows generating and operating on waypoints, similar to LibCarla's `road::Map`.
Also fixes that OpenDrive files were only loaded if the file was stored at a specific folder, now first searches in this default location, if not found then searches anywhere in contents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1684)
=> Expose waypoints API to UE4 Blueprints

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/client/ActorList.cpp, LibCarla/source/carla/client/ActorList.h, LibCarla/source/carla/client/Vehicle.cpp, LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/detail/ActorFactory.cpp, LibCarla/source/carla/client/detail/ActorFactory.h, LibCarla/source/carla/client/detail/ActorState.cpp, LibCarla/source/carla/client/detail/ActorState.h, LibCarla/source/carla/client/detail/ActorVariant.cpp, LibCarla/source/carla/client/detail/ActorVariant.h, LibCarla/source/carla/client/detail/CachedActorList.h, LibCarla/source/carla/client/detail/Episode.cpp, LibCarla/source/carla/client/detail/Episode.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/Simulator.h, PythonAPI/carla/source/libcarla/World.cpp
A pointer to the actor's parent was kept on each actor, thus this pointer was needed to initialize new actor instances which carried its own problems (#1724). By allowing finding a single actor by id (using episode's cached result if present) we can stop caching the parent in the actor and keep only the id, thus is easier to create a new instance.
- Fixes #1724.
- Allow finding single actors by id in PythonAPI.
- Improved complexity when finding traffic light associated to vehicle.
`actor.parent` might do an RPC call if the actor was not yet cached, this was happening anyway but now is "lazy-initialized".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1744)
=> Do not cache actor parent on each actor

LibCarla/source/carla/sensor/SensorRegistry.h, LibCarla/source/carla/sensor/s11n/CollisionEventSerializer.cpp, LibCarla/source/carla/sensor/s11n/CollisionEventSerializer.h, LibCarla/source/carla/sensor/s11n/EpisodeStateSerializer.cpp, LibCarla/source/carla/sensor/s11n/EpisodeStateSerializer.h, LibCarla/source/carla/sensor/s11n/ImageSerializer.cpp, LibCarla/source/carla/sensor/s11n/ImageSerializer.h, LibCarla/source/carla/sensor/s11n/LidarSerializer.cpp, LibCarla/source/carla/sensor/s11n/LidarSerializer.h, LibCarla/source/carla/sensor/s11n/NoopSerializer.cpp, LibCarla/source/carla/sensor/s11n/NoopSerializer.h, LibCarla/source/carla/sensor/s11n/ObstacleDetectionEventSerializer.cpp, LibCarla/source/carla/sensor/s11n/ObstacleDetectionEventSerializer.h
Make the code a bit more expressive by adding a No-op serializer. Client-side sensors can be added to the registry using this serializer to make sure that they don't send any data.
Also, pass all the raw-data by r-value ref, a bit more efficient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1760)
=> Add NoopSerializer for sensors that do not send data

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/LaneInvasionSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/LaneInvasionSensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ObstacleDetectionSensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastLidar.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h
Set up the `RootComponent` in `ASensor` so we don't need to set it up on each individual sensor. Forgetting to set up the root component results in difficult to track bugs (e.g. sensor not having a transform), this way we make sure every sensor has a root component. Moreover, they will be displayed in editor (though for the moment all of them look like cameras).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1758)
=> Set up RootComponent in ASensor

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/RecurrentSharedFuture.h, LibCarla/source/carla/client/ActorSnapshot.h, LibCarla/source/carla/client/GnssSensor.cpp, LibCarla/source/carla/client/LaneInvasionSensor.cpp, LibCarla/source/carla/client/TrafficLight.cpp, LibCarla/source/carla/client/Vehicle.cpp, LibCarla/source/carla/client/Walker.cpp, LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/WorldSnapshot.h, LibCarla/source/carla/client/detail/Episode.cpp, LibCarla/source/carla/client/detail/Episode.h, LibCarla/source/carla/client/detail/EpisodeState.cpp, LibCarla/source/carla/client/detail/EpisodeState.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/sensor/SensorData.h, PythonAPI/carla/source/libcarla/Snapshot.cpp, PythonAPI/carla/source/libcarla/World.cpp, PythonAPI/carla/source/libcarla/libcarla.cpp, PythonAPI/examples/automatic_control.py, PythonAPI/examples/dynamic_weather.py, PythonAPI/examples/synchronous_mode.py, PythonAPI/examples/vehicle_gallery.py, PythonAPI/test/smoke/__init__.py, PythonAPI/test/smoke/test_map.py, PythonAPI/test/smoke/test_snapshot.py, PythonAPI/test/smoke/test_sync.py
A world snapshot represents the state of every actor in the simulation at a single frame, a sort of still image of the world with a timestamp. This is meant to solve all the synchronization issues when retrieving actor locations, now is possible to record the location of every actor and make sure all of them were captured at the same frame without the need of using synchronous mode. It can also be used to remove the flickering in scripts like no-rendering mode.
This is a concept that already existed internally but wasn't exposed in the API. It actually doesn't add any overhead at it simply returns a reference to the episode state that is kept internally. For some more context see https://github.com/carla-simulator/carla/issues/1274#issuecomment-465567495.
```py
world_snapshot = …
```
=> Adding world snapshot to Python API

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h
At the end of a replayed session we make all the vehicles continue in autopilot, and also all pedestrians will be stop to avoid roaming without control. In the future the pedestrians could be enabled in autopilot also, walking at random positions.
* **Python version(s):** 2 & 3
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1764)
=> Stop pedestrians after a recorded session

CHANGELOG.md, Docs/python_api.md, Docs/python_api_tutorial.md, LibCarla/source/carla/rpc/GearPhysicsControl.h, LibCarla/source/carla/rpc/VehiclePhysicsControl.h, PythonAPI/carla/source/libcarla/Control.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/VehiclePhysicsControl.h
Proper calculation of vehicle acceleration require transmission details like the gear ratios.
This adds read and write access from LibCarla and PythonAPI.
* **Python version(s):** Python 2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1813)
=> Add transmission gears access

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/AtomicList.h, LibCarla/source/carla/client/GnssSensor.cpp, LibCarla/source/carla/client/GnssSensor.h, LibCarla/source/carla/client/LaneInvasionSensor.cpp, LibCarla/source/carla/client/LaneInvasionSensor.h, LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/WorldSnapshot.h, LibCarla/source/carla/client/detail/CallbackList.h, LibCarla/source/carla/client/detail/Episode.h, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/client/detail/WalkerNavigation.h, LibCarla/source/carla/sensor/data/LaneInvasionEvent.cpp, LibCarla/source/carla/sensor/data/LaneInvasionEvent.h, PythonAPI/carla/source/libcarla/World.cpp
I have added an ID to the callbacks so they can be removed
```py
id = world.on_tick(lambda x: do_something())
world.remove_on_tick(id)
```
I also finally made client-side sensors deregister their callbacks when they're stopped (there was no way of stopping these sensors before). While doing so I noticed that any exception thrown was ignored, actually a lot of exception were thrown all the time due to race conditions between callbacks. Basically, their "tick" is called simultaneously from different threads, and they were not taking this into account. This was specially bad for the lane invasion sensor since its measurements depend on previous measurements.
I have fixed them by making sure either the shared data is const or is properly synchronized using atomics.
Now they no longer throw …
=> Allow removing on tick callbacks and fixes to client-side sensors

CHANGELOG.md, Docs/python_api.md, PythonAPI/docs/world.yml, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/DebugShapeDrawer.cpp
Currently, we can only render debug helpers on UE4 Editor and Debug Packages.
This PR changes that, so now you can use `debug.draw_point`, `debug.draw_line`, `debug.draw_box`, `debug.draw_arrow`, and `debug.draw_string` in Shipping packages too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1874)
=> Added Debug Render on Shipping Package

LibCarla/source/carla/sensor/data/Array.h
This problem has been mentioned in #1778, you can find more information there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/1902)
=> Fixed assertion checking before updating the value

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaHUD.h
See https://github.com/carla-simulator/carla/issues/1894 for more details about the problem.
I a few words, the problem is that windows compilers change the name of some functions (those who use strings mainly) depending if they need to use UNICODE or ANSI strings. For UNICODE the function name is the same but ending with 'W', and for ANSI they end with 'A'. So, for example the function DrawText() of the windows API will change to DrawTextW() or DrawTextA() transparently.
That modification is made by the compiler using some kind of #DEFINE preprocessors, and that means that the name of the function changes globally in all the code. The problem is that if we need to load that exact function like DrawText() from a non windows DLL (like UE4Editor-Engine.dll from Unreal), the compiler at the …
=> Fix Windows build

Unreal/CarlaUE4/Config/DefaultEngine.ini, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
- Remove Depth of Field to eliminate the blur it produces with nearby objects.
- Activate Mesh Distance Field
- Tweak PostProces values of CameraSceneCapture: Bloom and SSAO.
- Now Camera Spectator and Camera Scene Capture have a very similar render.
* **Unreal Engine version(s):** UE4 22.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2173)
=> Camera Scene Capture / Dept of Field / Mesh Distance Field

Unreal/CarlaUE4/Config/DefaultEngine.ini
We have been forced to disable the Mesh Distance Fields. They have appeared many weird shadows for all towns. Another reason is that we don't have control over them. At last, we decided to disabled for this release and to research more.
* **Unreal Engine version(s):** UE4 22.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2286)
=> Disable Mesh Distance Fields

CHANGELOG.md, LibCarla/source/carla/client/Map.cpp, LibCarla/source/carla/client/Map.h, LibCarla/source/carla/opendrive/OpenDriveParser.cpp, LibCarla/source/carla/opendrive/parser/ObjectParser.cpp, LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/road/Map.h, LibCarla/source/carla/road/MapBuilder.cpp, LibCarla/source/carla/road/MapBuilder.h, LibCarla/source/carla/road/ObjectSet.h, LibCarla/source/carla/road/Road.h, LibCarla/source/carla/road/element/RoadObject.h, LibCarla/source/carla/road/element/RoadObjectCrosswalk.h, LibCarla/source/carla/road/element/RoadObjectIterator.h, LibCarla/source/carla/road/element/RoadObjectVisitor.h, PythonAPI/carla/source/libcarla/Map.cpp
New PythonAPI function to parse the OpenDRIVE file and return a list with all the points that define each crosswalk.
That functionality is needed because we can define crosswalk zones with RoadRunner and they are exported only with the OpenDRIVE file of the map.
Then we can parse that information and generate the geometry needed for the pedestrian's navigation system to know where they can cross the roads.
This API is used automatically in the Docker import pipeline.
* **Platform(s):** Ubuntu 18, Windows 10
* **Python version(s):** Python 2 and 3
Currently, there is some angle distortion, and the crosswalks need to be extended about 1 meter in each extreme so they cover any space until the sidewalk (Road_Gutter, Road_Curb...).
--- …
=> Parsing OpenDRIVE crosswalks

PythonAPI/examples/automatic_control.py, PythonAPI/examples/manual_control.py, PythonAPI/examples/manual_control_steeringwheel.py, PythonAPI/examples/no_rendering_mode.py
Fixes font name on windows. 
Now the scripts uses 'mono' on Linux and 'courier' on Windows by default.
* **Platform(s):** Windows, Linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2195)
=> Fix font name for windows

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Settings/CarlaSettingsDelegate.cpp
This PR will fix the transition from Epic / Low quality settings. 
Two problems were found in version Carla 0.9.7:
First, Unreal was writing the last quality settings to a file in /Saved/ folder and was reading and applying those settings without taking care of the desired quality settings that the user could specify.
We have fixed this thanks to the help of BenAscent who pointed the way to disable the writing of those settings.
Second, when enabling low-quality settings, the autoexposure was disabled but a value of Exposure Compensation of 4.5 was applied what made the image brighter than usual. We fixed that forcing autoexposure to be enabled also at low-quality level.
Fixes #2336, #2335
* **Platform(s):** Ubuntu and Windows
* **Unreal Engine version(s):** …
=> Fix Low / Epic quality levels transition

CHANGELOG.md, PythonAPI/carla/agents/navigation/agent.py
Fixed agent crashes due to API changes in is_within_distance_ahead. This is urgently required for the agents in ScenarioRunner to have ScenarioRunner be compatible with 0.9.7
* **Python version(s):** 2.7 and 3.x
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2386)
=> Fixed agent crashes due to API changes in is_within_distance_ahead

CHANGELOG.md, Docs/bp_library.md, Docs/python_api.md, LibCarla/source/carla/geom/BoundingBox.h, LibCarla/source/carla/geom/Rotation.h, LibCarla/source/carla/geom/Transform.h, LibCarla/source/test/common/test_geom.cpp, PythonAPI/carla/source/libcarla/Geom.cpp, PythonAPI/docs/geom.yml
Added new methods to BoundingBox:
- BoundingBox::Contains: whether a point in world space is contained by the bbox.
- BoundingBox::GetWorldVertices: returns a list of the 8 vertices of the bbox in world space.
- BoundingBox::GetLocalVertices: returns a list of the 8 vertices of the bbox in local space.
Exposed them to the Python API as:
- contains
- get_world_vertices
- get_local_vertices.
To implement this, I have also modified Transform and Rotation to be able to transform points back and forth:
- Transform::InverseTransformPoint
- Rotation::RotatePoint (moved from Transform::TransformPoint to its own function)
- Transform::InverseRotatePoint 
Also added a tests that make sure that transformation back and forth are coherent to one another (P after being transformed and untransformed …
=> Added to BoundingBox methods Contains, GetWorldVertices and GetLocalVertices 

CHANGELOG.md, Docs/python_api.md, LibCarla/source/carla/client/Map.cpp, LibCarla/source/carla/client/Map.h, LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/road/Map.h, PythonAPI/carla/source/libcarla/Map.cpp, PythonAPI/docs/map.yml
We added a new function for the Python API where you can request a new waypoint giving a set of parameters from the openDRIVE file. The parameters are the road id, the lane id and the distance from the road start.
An example is:
```py
m = world.get_map()
w = m.get_waypoint_xodr(10, 2, 1)
```
It requests a waypoint placed a 1m of the lane id 2, from the road id 10.
For this waypoint, we can request a lane id of 0, which means that the waypoint will be placed at the centerline of the road.
If any of the parameters are wrong, then the result is None instead of a waypoint.
--- …
=> Allow waypoint creation from OpenDRIVE

Util/BuildTools/BuildPythonAPI.bat
py launcher which is required for building Python API is missing on default installations of python. The batch file is calling this utility to build the Python API.
In cases where it is missing a better error message is provided to guide the user to installing this utility.
WINDOWS only
None - just an error message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2267)
=> better error message for missing "py launcher"

CHANGELOG.md, LibCarla/source/carla/opendrive/parser/ProfilesParser.cpp, LibCarla/source/carla/opendrive/parser/RoadParser.cpp
Fixed crash when reading OpenDRIVE file with missing elevation profile or lane offset.
All roads will have a default neutral elevation profile and lane offset if none is specified.
* **Python version(s):** 2 and 3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2484)
=> Fix for missing elevation profile and lane offset.

CHANGELOG.md, LibCarla/source/carla/client/Client.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, PythonAPI/carla/source/libcarla/Client.cpp, PythonAPI/examples/start_replaying.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
A new parameter has been added at the time of replaying a session, where you can choose if the recorded hero vehicles will be replayed or not. If they are not, then they can drive freely while the recorder system is replaying all other vehicles. That allows to the hero vehicles to test different strategies while the simulation is the same every time.
The parameter is the `-i` or `--ignore_hero`
For example: `./start_replaying.py -f recorded.log -i`
Fixes # 1605
Fixes # 1769
* **Python version(s):** 2.7 and 3.7
Take care with the collisions, because the replayed vehicles will not react to collisions from the hero, and they will maintain always the recorded position.
--- …
=> Adding Ignore Hero to Replayer (Issue 1769)

Util/BuildTools/BuildLibCarla.sh
Use the checksum of the source folder (filenames only) to determine if files were added or removed. This way calling `make clean` is no longer necessary after adding new files.
Linux only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2513)
=> Use folder checksum to determine if CMake needs to be re-run

Util/BuildTools/Linux.mk
Quick fix for Jenkins not able to build FBX libs while doing the package:
```
Do you want to read the ReadMe file [y/n] ? 
Compiling FBX2OBJ...
CMake Error: The source directory "/var/lib/jenkins/workspace/carla_master/Util/DockerUtils/fbx/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Util/BuildTools/Linux.mk:138: recipe for target 'build.utils' failed
make: *** [build.utils] Error 1
```
We've temporarily removed FBX build in the package generation, this will have no effect for users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/253 …
=> Temporal fix for jenkins not able to compile FBX

LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/road/Map.h
Fixed crash for Roundabout8Course.xodr from the OpenDRIVE official examples in rtree generation. Now it takes into account lanes that are start or end mid-way through the road.
Fixed issues where lane 0 could be accessed from the client API if LaneType was set to something other than "none". Now `ForEach*LaneImpl` checks for lane 0 and ignores it.
Lane 0 is ignored in all queries except `carla::road::Map::GetWaypoint`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2557)
=> Fixed lane 0 and rtree issues.

CHANGELOG.md, LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/sensor/SensorRegistry.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp, Util/BuildTools/BuildUtilsDocker.sh, Util/BuildTools/Linux.mk
Now, `carla.client.generate_opendrive_world(opendrive)` will also automatically generate the Recast information allowing the walkers to move around the sidewalks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2554)
=> Recast navigation generation from server-side

Docs/build_docker.md
The `-e` flag is used to define an environment variable. It requires a parameter. `-e --gpus all` means "Define environment variable `--gpus` to be empty, execute image `all:latest`. I have a suspicion that whoever wrote this intended to define an environment variable but forgot it (e.g. `NVIDIA_VISIBLE_DEVICES=0` used below).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2625)
=> Remove superfluous flag in docker documentation

LibCarla/source/carla/client/Landmark.h, LibCarla/source/carla/client/TrafficSign.cpp, LibCarla/source/carla/client/TrafficSign.h, LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/sensor/data/ActorDynamicState.h, PythonAPI/carla/source/libcarla/World.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorRegistry.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorView.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp
The PythonAPI has been updated to be able to get a TrafficLight or TrafficSign actor from a Landmark.
Example:
```python
traffic_lights = waypoint.get_landmarks_of_type(100, "1000001")
if len(traffic_lights) > 0:
traffic_light = self.world.get_traffic_light(traffic_lights[0])
print( traffic_light.state )
print( traffic_light.get_state() )
print( traffic_light.get_green_time() )
print( traffic_light.get_yellow_time() )
print( traffic_light.get_red_time() )
print( traffic_light.get_elapsed_time() )
print( traffic_light.is_frozen() )
print( traffic_light.get_pole_index() )
print( traffic_light.get_group_traffic_lights() )
print( traffic_light.trigger_volume.location )
print( traffic_light.trigger_volume.extent )
```
* **Unreal Engine …
=> Added methods to get trafficlights and trafficsigns from landmarks

LibCarla/source/carla/geom/Rtree.h
Currently CARLA fails to build under Bullseye coverage due to the usage of an overloaded operator&& from Boost.Geometry. This is a limitation of the coverage tool and not Carla's fault, however since it can be worked around simply by changing how the operator&& is called it might be a good idea to do this small change in CARLA to avoid someone else stumbling upon this issue again.
This PR does not change behaviour, simply replaces `a && b` by `operator&&(a, b)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2691)
=> Fix compilation issue with BullseyeCoverage

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightManager.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightManager.h
Moved trigger box generation for traffic lights from `ATrafficLightManager` to `UTrafficLightComponent'.
Added spawn of traffic lights without controllers when defined outside junctions. The signal needs to fullfill the following conditions for this to happen:
- Has no controllers
- Is defined outside any junction (standard roads)
- It's type corresponds to a traffic light as defined in the OpenDRIVE specification.
A traffic light may be defined outside a junction but may take effect inside one. The traffic light will spawn and behave independently of the other lights in the junction.
--- …
=> Spawn lone traffic lights

LibCarla/source/carla/client/Landmark.h, LibCarla/source/carla/client/Map.cpp, LibCarla/source/carla/client/Waypoint.cpp
This is a quick fix for the functions `get_all_landmarks`, `get_all_landmarks_from_id` and `get_all_landmarks_of_type` returning corrupted landmarks.
The issue happened when calling these functions in the following way:
```
for landmark in world.get_map().get_all_landmarks():
```
The call `world.get_map()` calls the simulator to retrieve the OpenDRIVE file and parses the map. Then the call `get_all_landmarks()` retrieves a list of landmarks with contents that points towards the map. After this last call, python deletes the map from `world.get_map()` rendering the contents of the landmark list corrupted.
This fix adds the necessary shared pointers to the Landmark class to prevent this deletion from happening before the loop is completed.
* **Python …
=> Fixed get_all_landmarks functions returning corrupted landmarks

PythonAPI/examples/spawn_npc.py
Before this commit, `synchronous_master` is defined inside
try-block so if any error happens before the definition and args.sync is true,
"ReferenceError: `synchronous_master` is not defined" is raised
in the finally-block.
You can reproduce this error when you run `python spawn_npc.py --sync` without good connection to the server (like `RuntimeError: rpc::timeout: Timeout of 10000ms while connecting to 127.0.0.1:2000`)
Described above (and in the commit message too)
* **Platform(s):** ...Ubuntu 16
* **Python version(s):** ... python 2.7.13
* **Unreal Engine version(s):** ... 4.24
I am pretty sure this is OS independent.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulato …
=> Fix variable definition

LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/road/MapBuilder.cpp, LibCarla/source/carla/road/MapBuilder.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/YieldSignComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/YieldSignComponent.h
Added small preprocess in `MapBuilder.cpp` to move the signals out of driving lanes. The signal is always moved to it's right until it finds a suitable spot. If it cannot find a suitable position (due to complex road layout) the signal will remain in it's original position.
Added a small fix to `UYieldSignComponent` and `UStopSignComponent` that would cause the simulation to crash when de-spawning vehicles affected by the signals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2736)
=> Signal displacement and traffic signs crash fix

Co-Simulation/PTV-Vissim/run_synchronization.py, Co-Simulation/PTV-Vissim/vissim_integration/carla_simulation.py, Co-Simulation/PTV-Vissim/vissim_integration/vissim_simulation.py
This PR fixes a bug that was freezing carla when calling the synchronization script with a relative path for the vissim network. Now it is possible to call the synchronization script in the following way:
```sh
python run_synchronization examples/Town01/Town01.inpx
```
* **Python version(s):** 3.7.7
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2740)
=> Fix bug PTV Vissim relative path

PythonAPI/carla/agents/navigation/global_route_planner.py
Fixes #2719 
* **Platform(s):** ... Ubuntu 16
* **Python version(s):** ... python 2.7.13
* **Unreal Engine version(s):** ... 4.24
To be honest I don't know what is expected behavior for `automatic_control.py` script. So I was not able to test it on my environment.
But my guess is this is right correction because `agents.navigation.local_planner.RoadOption` is enum and its attributes are all int. After this modification, at least the error showed in #2719 disappeared.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2742)
=> Delete wrongly referenced .value attribute

Co-Simulation/Sumo/util/netconvert_carla.py
This PR adds a default values (net.net.xml) for the output argument in the script netconvert_carla.py.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2743)
=> added default argument in output file argument

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp
Now that Traffic manager runs on client, we can not use the autopilot feature from server, so we can not enable autopilot at the end of a recorded simulation. Instead, I will stop all vehicles to avoid them go crazy.
Probably we will re-enable this feature in the future, with a better communication client-server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2754)
=> Stop vehicles at end of the recorded simulation, instead of using autopilot

CHANGELOG.md, LibCarla/source/carla/client/Waypoint.cpp
Fixes #  
`GetLeftLaneMarking` is supposed to look at the second element of `_mark_record`, not the first one, in terms of context as well as according to the comment. 
* It may cause the runtime error by trying to dereference the null pointer. 
* **Python version(s):** Python 3.6 and Python 2.7 
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2771)
=> Fix the mistake in GetLeftLaneMarking

Docs/build_linux.md, Docs/build_windows.md, Docs/start_quickstart.md, Util/BuildTools/BuildCarlaUE4.bat, Util/BuildTools/Package.bat
In Windows build there was a discrepancy on how to get the Unreal Engine directory, so we now use two methods together:
- First it tries to use the environment variable **UE4_ROOT**. If that variable is defined, then we use it.
- If the UE4_ROOT is not defined, then we search on the windows registry for all keys inside:
HKEY_LOCAL_MACHINE\SOFTWARE\EpicGames\Unreal Engine\
the result could be:
4.21
4.22
4.23
4.24
then we use always the last one, following the order on the registry, so probably the last installed version of UE will be the one to use.
We get the **InstalledDirectory** of that version and we can continue.
If all these methods fail, the we can not make the windows build.
Fixes #  2776 …
=> Fix windows script to find UE4 directory

CHANGELOG.md, Docs/build_linux.md, Docs/build_windows.md, Docs/python_api.md, LibCarla/source/carla/client/Actor.cpp, LibCarla/source/carla/client/Actor.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/rpc/Command.h, PythonAPI/carla/source/libcarla/Actor.cpp, PythonAPI/carla/source/libcarla/Commands.cpp, PythonAPI/docs/actor.yml, PythonAPI/docs/commands.yml, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
New API function **actor.add_angular_impulse(vector)**
It sends an angular impulse to the actor.
The **vector** has this characteristics:
* in **world** coordinates
* in **degree** units
* defines the **axis** of rotation
* the magnitude is the **strength** of the impulse
It takes into account the **mass** of the actor, so for massive actors you need bigger impulse (magnitude of the vector).
You can use it as a function like:
`actor.add_angular_impulse(carla.Vector3D(0, 100, 0))`
or as a command batch:
`batch = []`
`batch.append(carla.command.ApplyAngularImpulse(actor, carla.Vector3D(0, 100, 0)))`
`client.apply_batch(batch, True)`
Both will apply an angular impulse of 100 degrees on the world Y axis (pitch).
* **Python version(s):** Python 3.7
* **Unreal …
=> New API function to add angular impulse to an actor

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp
On the IMU sensor, there was an issue where acceleration due to gravity was added after rotating the actor acceleration vector to the orientation of the IMU. This meant that there was a constant 9.8 m/s^2 added to the Z axis of the accelerometer readings regardless of the orientation of the accelerometer. This PR changes this so that gravity is added to the Z axis before rotation.
Fixes #2790 
* **Python version(s):** 2.7, 3.6
If any code has been written to explicitly account for this error, it could break. However, anyone using an IMU in a Z-up orientation (the default) will see almost no changes.
--- …
=> Fixed IMU gravity

CHANGELOG.md, LibCarla/source/carla/client/Waypoint.cpp, LibCarla/source/carla/geom/MeshFactory.cpp, LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/road/MapBuilder.cpp, LibCarla/source/carla/road/element/Geometry.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightManager.cpp
* Fixed poly geometries problems at `s = 0`, crash when computing the junction's bounding box
* Fixed crash in `GetNextUntilLaneEnd`, and `GetPreviousUntilLaneStart` for very short roads.
* Fixed a particular case of a floating-point error in mesh generation
* Fixed traffic light ingestion from wrongly defined OpenDRIVE that crashes the simulation when using the OpenDRIVE standalone mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2828)
=> OpenDRIVE ingestion fixes

PythonAPI/carla/source/libcarla/LightManager.cpp
Quick fix on LightGroup names. The python binding was using None which is a reserved keyword on Python. It was replaced by NONE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2839)
=> Replaced use of reserved keyword None in PythonAPI

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp
The lane marking colors (white and yellow) were applied in reverse when importing a map.
Now they are correct.
* **Platform(s):** Windows, Ubuntu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2838)
=> Exchange the lane marking colors, they were in reverse

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveGenerator.cpp
The signs where not created properly on imported maps.
Also sign prop duplication was fixed.
Props with names that contains "light" or "sign" or if their materials contains "light" or "sign" on their name, will not be imported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2852)
=> Fix sign creation on imported maps

Util/CreateDebian.sh
This PR updates `Util/CreateDebian.sh` script to support new CARLA releases (trying to make it version independent).
This PR is based on the modifications introduced in the PR #2791 
Functionality added:
* Allow choosing carla release through a parameter when calling the script.
* Package name updated to `carla-simulator`.
* Package URL updated.
* Automatic detection of python3 and python2 egg files.
* Adds Co-Simulation folder to the debian package.
Fixes #2770   
* **Python version(s):** 2.7, 3.6.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2887)
=> [Debian Package] Add support for new carla releases

Docs/core_actors.md
`spawn_actor()` raises an exception, and `try_spawn_actor()` returns
`None` on failure. However, the documentation swapped the descriptions
of those two. This commit simply fixes the documentation.
* **Platform(s):**  Ubuntu 18.04.4, kernel 5.3.0-46-generic
* **Python version(s):** Python 3.6.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2907)
=> Fix inconsistency in the doc with the actual API.

LibCarla/source/carla/nav/Navigation.cpp, LibCarla/source/carla/profiler/Profiler.h, LibCarla/source/carla/rpc/Response.h, LibCarla/source/carla/sensor/data/Array.h, LibCarla/source/carla/sensor/data/DVSEventArray.h, LibCarla/source/carla/sensor/data/ImageTmpl.h, LibCarla/source/carla/sensor/data/LidarMeasurement.h, LibCarla/source/carla/sensor/data/RadarMeasurement.h, LibCarla/source/carla/sensor/data/RawEpisodeState.h, LibCarla/source/test/common/test_streaming.cpp
Found running the build from #2693.
- Division by zero in Profiler.h
- Calling memcpy with a nullptr on MsgPack
- Accessing the address of a destroyed object in the benchmarking tests
- Two wrongly placed asserts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2901)
=> Fixes to some issues found running with sanitizers

LibCarla/source/carla/trafficmanager/ALSM.cpp, LibCarla/source/carla/trafficmanager/InMemoryMap.cpp, LibCarla/source/carla/trafficmanager/InMemoryMap.h, LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
This PR replaces the earlier hash buckets used for waypoint indexing and querying with Boost's R-tree.
This also solves the problem of slow TrafficManager setup on large .xodr only maps.
* **Platform(s):** Ubunru 20.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2933)
=> Boost R-tree for waypoint indexing and querying in TrafficManager

.gitmodules, CHANGELOG.md
We add a submodule to the CARLA repo to publish all plugins available for CARLA
To get those plugins you need to use these commands:
- when cloning CARLA repo add the command --recursive, like
`git clone https://github.com/carla-simulator/carla --recursive`
- or if you already have cloned the repo
`git submodule update --init`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2921)
=> Add plugins repo as submodule

.gitmodules, CHANGELOG.md
Removing the Plugins folder as submodule, we will use Plugins in another way.
After removing, you may need to use the command:
`git rm Plugins`
to properly remove the references to the plugin in your CARLA repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2948)
=> Removing plugins as submodule

PythonAPI/carla/source/libcarla/Weather.cpp
Quick fix where all the elements of the weather parameters are now exposed when printing an instance in Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2957)
=> Fixed weather out in PythonAPI

Util/CreateDebian.sh
The launcher script CarlaUE4.sh shouldn't require sudo. In fact the line that
requires sudo is not necessary at all since the executable flag is already
set.
Fixes #  
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2945)
=> Remove unecessary line from launcher script to avoid sudo

Util/Docker/README.md
Updating version of UE4 to be use when building the docker. Some users got confused and used version 4.22.2 instead of the new 4.24.3 with last version of CARLA 0.9.9, and then got some errors.
Fixes # 3011
* **Unreal Engine version(s):** UE 4.24.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3034)
=> Update UE4 version (from 4.22.2 to 4.24.3)

.travis.yml, CHANGELOG.md, PythonAPI/carla/requirements.txt, PythonAPI/carla/setup.py, Util/BuildTools/Setup.sh
Replaced the deprecated function call `platform.dist()` with recommended `distro.linux_distribution()` in `setup.py`. Recommendation is from the python docs of the platform module: https://docs.python.org/3.7/library/platform.html#unix-platforms
The deprecated call is removed in Python 3.8 which is default Python version of Ubuntu 20.04.
No drawbacks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/2857)
=> Replace deprecated function call in setup.py

CHANGELOG.md, Docs/tuto_G_retrieve_data.md, LibCarla/source/carla/client/detail/Client.cpp
If an actor is attached to another one with z transformation with a translation only in the z axis with the SpringArm,
its transformation will be ill formed. A warning has been added when the actor is spawn to alert the user of this issue.
Fixes #  
#2842 
* **Platform(s):** Ubuntu 28.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3036)
=> Added a warning when the SpringArm transformation can fail

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
Spawns a decal deep below the world to fix transparency issues in any map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3096)
=> Fix for transparency see-through

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.cpp
Quick fix for an error that prevent objects from being correctly tagged after being spawned from the client side.
Fixes #2866
* **Unreal Engine version(s):** 2.24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3088)
=> Fixed untagged objects spawned from the client

CHANGELOG.md, Util/BuildTools/Ad-rss.sh
Just using the v1.x branch is now longer working, as it
requires a cmake newer than 3.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3128)
=> Fixed spdlog version to v1.7.0 for RSS

PythonAPI/carla/agents/navigation/global_route_planner.py, PythonAPI/examples/manual_control.py
**Before** RoadOptions were calculated from the angle between the direction of the entering road and the "net vector" (vector between the start of the intersection and the end).
**Now**, the "net vector" has been substituted by the angle of the existing road.
This helps deal with irregular intersection where some roads are very wide and other are very narrow (due to the difference in the amount of lanes).
Here are some HD images showing the idea.
Before (1st one was accepted as LEFT, but the second wasn't):
After:
**Bonus change:** The manual control has a left panel with the closest vehicles. Added a clause that forces the comparison to only use the distances, not the vehicle itself (as they can't be compared, resulting in an error).
* **Python …
=> Fixed global planner's RoadOptions

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/YieldSignComponent.cpp
This fixes the generation of trigger boxes when signs are placed in lanes with 0 width (can happen when a lane is being created along the road).
* **Python version(s):** 2,3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3203)
=> Fixed trigger box generation for traffic signs

Jenkinsfile
This is just an addition to the Jenkinsfile to let the Jenkins machine to update the documentation from Doxygen to Github through SSH (private key) instead of using normal URL (user/password).
This stage only happens when building the **master** branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3258)
=> Changing Jenkinsfile for Doxygen

Co-Simulation/Sumo/run_synchronization.py, Co-Simulation/Sumo/spawn_npc_sumo.py
This pull requests adds two new arguments to `spawn_npc_sumo.py`: `--sumo-host` and `--sumo-port`. This way, the script can be used to connect to a remote sumo instance.
It also fixes a typo in `run_synchronization.py`.
* **Platform(s): Ubuntu 20.04, Debian Bullseye**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3263)
=> New feature: remote sumo instance in spawn_npc_sumo.py

Docs/start_quickstart.md
This fixes a minor error in the documentation regarding running carla, if the deb installation was choosen.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3178)
=> Running Carla when choosing a) deb Carla install

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightState.h
Added off state to traffic lights so that all lights are off. The related content branch is `axel/traffic-lights-off`.
The UE4 enum for traffic light state was lacking the off state. It has been added and the blueprints in the content branch have been updated to shut the lights off when this state is triggered.
Traffic manager stops vehicles when the state is off in the same way when it is red. As a workaround, traffic lights report green state to the vehicles when they are off. This should be fixed once the traffic manager is capable of detecting off state properly.
--- …
=> Added off state to traffic lights.

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp
Actors that are already present in the scene when replaying were not moved to the initial position in the first frame. This PR fixes this as it produces problems during a frame if it overlaps objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3328)
=> Existing actors in replayer are positioned to the initial position

Docs/core_map.md, Docs/python_api.md, PythonAPI/docs/map.yml, PythonAPI/docs/world.yml
- Some notes and clearer documentation regarding the waypoint API.
In summary, the world.get_map() method does call the server, but the waypoint API itself happens on the client-side. 
#2992 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3356)
=> sergi-e/docs-map-issue-2992

Docs/build_linux.md, PythonAPI/carla/setup.py, Util/BuildTools/Setup.sh, Util/Docker/Prerequisites.Dockerfile, Util/OSM2ODR/CMakeLists.txt, Util/OSM2ODR/src/CMakeLists.txt
Added Xerces-c library to automatic compilation in setup.sh instead of being a required library installed in your system though `apt-get`. 
Removed the library from requirements and documentation as it is compiled during setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3379)
=> Compile and link Xerces-c in setup

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
In some special cases, when the physics are re-enabled, the collisions seem to not work.
This fix reinforces them to be enabled to be sure.
Fixes #  
* **Platform(s):** Ubuntu 18.04 
* **Python version(s):**3.6.9
* **Unreal Engine version(s):**4.24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3380)
=> Reinforce collisions in SetSimulatePhysics(true)

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp
We were getting the id from ActorInfo and this one is not the same as the client's actor id.
Now, we take it from FActorView that correspond to the one we need.
* **Python version(s):** Python 3.6.9
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3396)
=> RayCastSemanticLidar: Fix actor's id bug

CHANGELOG.md, LibCarla/source/carla/streaming/Server.h, LibCarla/source/carla/streaming/detail/tcp/Server.cpp, LibCarla/source/carla/streaming/detail/tcp/Server.h, LibCarla/source/carla/streaming/detail/tcp/ServerSession.cpp, LibCarla/source/carla/streaming/detail/tcp/ServerSession.h, LibCarla/source/carla/streaming/low_level/Server.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Fixed a dead lock in synchronous mode happening randomly at high frame rate. 
It was caused by a race condition between messages to be sent through the network (the message causing the dead-lock was the one who has the episode data). The messages are added in a queue and processed in order. While one is being sending a flag is marked, and then the flag is unmarked once the message has been sent. But the unmarking of the flag was coded in a handler that was added to the queue when the message has been sent, instead of processing it at the instant. That was producing the race condition when another message was added to the queue before this handler, because if the flag is not unmarked the next message will be discarded. 
In the case of a message with the episode data, if it is skipped in …
=> Fix dead-lock in synchronous mode at high frame rate

PythonAPI/carla/source/libcarla/Map.cpp
Fixed windows signed - unsingned conversions of `LaneType` parameter in `map.get_waypoint()` function. An intermediate function accepts a signed version of the variable and then performs the explicit cast.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3458)
=> Fixed map.get_waypoint function crashing with LaneType.Any

LibCarla/source/carla/trafficmanager/LocalizationStage.cpp
Adding null checks in the ExtendAndFindSafeSpace method to prevent a crash when unable to find the next waypoints.
Fixes #3466  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3484)
=> TrafficManager: Adding null checks in LocalizationStage

LibCarla/source/carla/trafficmanager/TrafficManager.h, LibCarla/source/carla/trafficmanager/TrafficManagerBase.h, LibCarla/source/carla/trafficmanager/TrafficManagerClient.h, LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp, LibCarla/source/carla/trafficmanager/TrafficManagerLocal.h, LibCarla/source/carla/trafficmanager/TrafficManagerRemote.cpp, LibCarla/source/carla/trafficmanager/TrafficManagerRemote.h, LibCarla/source/carla/trafficmanager/TrafficManagerServer.h, PythonAPI/carla/source/libcarla/TrafficManager.cpp
This PR removes the Traffic Light reset method from TM, and changes its usages from TM's one to the new one in World.
Documentation must be updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3498)
=> Remove TM's Traffic Light reset, and use the new one from World instead

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightManager.cpp
The TL (TrafficLight) and TS (TrafficSigns) were spawned from code always to the persistent level.
Now, before spawning them it is detected if the level support sub-levelling and if the right sublevel exists, so they can be spawned in the right level.
If there are no sublevels or the specific sublevel is not included in the hierarchy, they will be added to the persistent level as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3532)
=> TrafficLight and TrafficSigns can spawn on sublevels

LibCarla/source/carla/client/Actor.h, LibCarla/source/carla/client/Vehicle.h, LibCarla/source/carla/client/Walker.h, PythonAPI/carla/source/libcarla/Actor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/BoundingBoxCalculator.cpp
The bounding_box attribute has been moved to Actor and the BB calculation has been added on the server side for all the actors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3595)
=> All actors have bounding box

PythonAPI/examples/manual_control.py
In packages executed with python2 and Pygame 2.0 the initial image is all noise. This issue hasn't been detected with other versions of Pygame nor python 3.
The initial surface of the window has been set to black to avoid this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3608)
=> Fixed noise on manual_control

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/LidarDescription.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp
Added a "horizontal_fov" parameter to (semantic) lidar to allow for a restricted field of view of the sensor. The field of view is centered around the axis in which the sensor is directed. The rotation frequency parameter is scaled towards the total fov of the sensor, meaning it describes the frequency for one full scan of the fov.
Fixes #1440 #1544
* **Platform(s):** Ubuntu 18.04.5
* **Unreal Engine version(s):** 4.24.3
With a default 360° horizontal FOV the lidar scan will start at -180° and finish at 180° when performing a full revolution, assuming the sensor itself is at a 0° orientation. Previously the scan would in this case start at 0° and finish at 360°.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Add horizontal fov parameter to lidar sensor

LibCarla/source/carla/rpc/String.h
Fix a bug regarding string format conversions.
The conversion becomes a bit slower but this is used typically for loading a map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3619)
=> Fixed conversion of std::string to FString.

CHANGELOG.md, PythonAPI/carla/agents/navigation/controller.py, PythonAPI/carla/agents/navigation/local_planner.py
Added an offset input to the VehiclePIDController, allowing the controlled vehicles to move displaced from the lane center.  The LocalPlanner has been extended to accomodate these changes.
It is important to note that due to the current state of the controllers, they are subject to break if the offset is high enough to make the vehicle drive through an adjacent lane. This is mainly due to the use of functions such as *get_waypoint()* or *is_at_traffic_light()*.
There should be no possible drawbacks as this is purely an extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator …
=> Extended local planner with a lateral offset

Jenkinsfile, LibCarla/source/carla/client/Vehicle.cpp, LibCarla/source/carla/client/Vehicle.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, PythonAPI/carla/source/libcarla/Actor.cpp, Unreal/CarlaUE4/CarlaUE4.uproject, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Trigger/FrictionTrigger.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h, Util/BuildTools/BuildCarlaUE4.bat, Util/BuildTools/BuildCarlaUE4.sh, Util/BuildTools/BuildPythonAPI.sh, Util/BuildTools/Package.bat, Util/BuildTools/Package.sh, Util/BuildTools/Windows.mk
Added initial support for CarSim.
This PR integrates carsim in our vehicles using the plugin provided by https://www.carsim.com/products/carsim/index.php.
The plugin needs to be present in the engine before running it.
You need to run `make clean` and then `make XXXX ARGS="--carsim"` to enable carsim capabilities.
Vehicles get a new function `enable_carsim` to enable carsim.
* **Platform(s):** Ubuntu 18.04, Windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3680)
=> Added initial support for CarSim

Jenkinsfile, Unreal/CarlaUE4/.gitignore, Unreal/CarlaUE4/CarlaUE4.uproject, Util/BuildTools/BuildCarlaUE4.bat, Util/BuildTools/BuildCarlaUE4.sh, Util/BuildTools/Environment.sh, Util/BuildTools/Linux.mk, Util/BuildTools/Package.bat, Util/BuildTools/Package.sh, Util/BuildTools/enable_carsim_to_uproject.py
Added fixes to compile unreal engine without requiring the CarSim plugin.
This PR adds a small step in the compilation to edit the `.uproject` file to add or remove the CarSim plugin dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3704)
=> CarSim broken pipeline fix

LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp
This change protects UnregisterVehicle calls when an actor is still running TM-related operations, by extending the mutex lock to include stage specific calculations. It has been introduced to comply with the new synchronous pipeline.
None, although now to unregister a vehicle it will be necessary for it to have finished its frame-related calculations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3723)
=> Extended mutex to Traffic Manager operation stages

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Missing defines prevented successful compilation without CarSim plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3734)
=> Fixed missing defines

LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, PythonAPI/carla/source/libcarla/World.cpp
This fixes a bug in the new synchronous pipeline of the server.
Coming from a simulation in asynchronous mode, after asking the server to apply the synchronous mode,
the apply_settings method checks that the server has correctly set all the options before returning the control to the client.
Fixes # 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3732)
=> Fix bug in Apply Synchronous mode

Jenkinsfile, Util/BuildTools/BuildPythonAPI.sh, Util/BuildTools/Package.bat, Util/BuildTools/Package.sh
We added a new command line option to collect all cooked packages in a single archive (ZIP or TAR.GZ).
The option is like: 
`make package ARGS="--packages=Town06_Opt,Town07_Opt --target-archive=MyArchive"`
If the **--target-archive** is not specified, each map will go to an individual archive like
- Town06_Opt.tar.gz
- Town07_Opt.tar.gz
But with the new option specified the result will collect those two packages into a single one:
- MyArchive.tar.gz
We use this option to collect all maps Town06, Town07, Town10HD and all their optimized version, inside the AdditionalMaps.
* **Platform(s):** Ubuntu, Windows
--- …
=> Packaging maps in a single package (new option --target-archive=<file>)

LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/detail/Simulator.cpp
Fix a delay in the apply_settings when changing from synchronous mode to asynchronous mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3739)
=> Removed synchronization causing timeout in apply_settings

CHANGELOG.md, Util/OSM2ODR/src/netwrite/NWWriter_OpenDrive.cpp
When converting OSM maps to OpenDRIVE the `laneChange` attribute in the roadMark record was missing.
This PR adds this information to the converted OpenDRIVE to fit the OpenDRIVE standard and enable lane changes in CARLA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3747)
=> Fixed missing lanechange in OSM maps

LibCarla/source/carla/client/detail/Simulator.cpp
Lower timeout in SynchronousFrame for EpisodeSettings. We lower because this was producing a delay in the ApplySettings that is not necessary.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3748)
=> Lower timeout in SynchronousFrame for EpisodeSettings

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/BoundingBoxCalculator.cpp
Fix to register crosswalks in environment objects. They were ignored previously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3794)
=> Fix to register crosswalks in environment objects

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp
FPaths::GameDir() is deprecated in next UE4 4.25, so we replaced by the new FPaths::ProjectDir()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3717)
=> Replacing FPaths::GameDir() 

Util/BuildTools/Package.bat, Util/BuildTools/Package.sh
Now when we make the default package (_make package_) it tries to copy the folder **Plugins** to the package, without checking first if it exists (this folder is optional).
This fix checks if the folder exist before copying its content.
Some issues where reported by this using Docker.
Fixes #3758
* **Platform(s):** Windows 10, Ubuntu 18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3784)
=> Make /Plugins/ folder optional when packaging

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h
For performance reasons, we disable the PhysicsState of vehicles when the simulate_physics is set to false. Previously, even if the physics of the vehicle were disabled, the PhysXVehicleManager was still running impacting our performance.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3798)
=> Destroy PhysicsState of vehicles when physics is disable

CHANGELOG.md, PythonAPI/carla/agents/navigation/behavior_agent.py, PythonAPI/carla/agents/navigation/local_planner_behavior.py
Fixed a bug at the BehaviourAgent causing the RoadOptions to not work as intended.
This was caused by having two instances of the RoadOption enumerator, one at the *local_planner.py* and another one at the *local_planner_behavior.py*. Despite the fact that the latter file has one, this same file also uses the *global_route_planner.py* to calculate the route of the agent, which in turn uses the RoadOptions at the *local_planner.py*. This causes some unintended equality checks between these two different RoadOption enums, which will always be False.
This has been fixed by removing the RoadOptions enum at the *local_planner_behavior.py*, and always using the one at the *local_planner.py*
Fixes  #3462
* **Unreal Engine version(s):** …
=> Fixed bug related to RoadOptions

PythonAPI/util/performance_benchmark.py
This PR improves the **performance_benchmark.py** script.
The following options have been added:
- Option for sync mode (**--sync**, on by default) and the possibility of setting the dt as a parameter.
- Added a warm-up time after spawning actors to not contaminate the performance results.
- Option for no rendering mode (on by default)
- Two new cases for LiDAR benchmark (100k and 1M points)
- Option to benchmark only a sublist of maps (**--maps**), sensors(**--sensors**), and types of weather (**--weather**).
- Parameter (**--show_scenarios**) to show all the maps, sensors and types of weather possible. 
For using these new options, you can run the following to show all the possible scenarios without running them:
`python3 performance_benchmark.py --show_scenarios`
Also, you can show …
=> Improved benchmark script

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/MoveAssetsCommandlet.cpp
Fix the import process for UE 4.26
The process was failing when moving assets to the corresponding folder for semantic segmentation.
* **Platform(s):** Windows, Ubuntu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3929)
=> Fix for import process in UE 4.26

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/MoveAssetsCommandlet.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, Unreal/CarlaUE4/Plugins/CarlaExporter/Source/CarlaExporter/Private/CarlaExporter.cpp, Util/DockerUtils/fbx/src/FBX2OBJ.cpp
RoadRunner last release has changed the way they name assets for the road. Before it was starting by **Road_**, but in last version they changed to plural word **Roads_**. That broke our nomenclature for the semantic segmentation and also pedestrian navigation, that are based on the name of the asset to identify different parts of a road (sidewalks, crosswalks, markings...).
Now CARLA can use **Road_** and also **Roads_** as part of the nomenclature. All of these are valid now:
- Road_Road
- Roads_Road
- Road_Marking
- Roads_Marking
- Road_Curb
- Roads_Curb
- Road_Gutter
- Roads_Gutter
- Road_Sidewalk
- Roads_Sidewalk
- Road_Crosswalk
- Roads_Crosswalk
- Road_Grass
- Roads_Grass
Also, when a FBX amp was imported, the name of the FBX was added as a prefix of the name of all assets. We were …
=> CARLA uses the old and new RoadRunner nomenclature

CHANGELOG.md, Jenkinsfile, LibCarla/source/carla/client/Vehicle.cpp, LibCarla/source/carla/client/Vehicle.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, PythonAPI/carla/source/libcarla/Actor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/BaseCarlaMovementComponent.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/MovementComponents/ChronoMovementComponent.h, Util/InstallersWin/install_zlib.bat
This PR adds the capability to define chrono vehicles with JSON files that can be set from the python side.
API changes:
`actor.enable_chrono_physics(max_substeps, max_substep_delta_time, vehicle_json, powetrain_json, tire_json, base_json_path)`
- **max_substeps**: max number of chrono substeps 
- **max_substep_delta_time**: max size of substep 
- **vehicle_json**: relative path to vehicle json file with respect to `base_json_path` (e.g.: `hmmwv/vehicle/HMMWV_Vehicle.json`)
- **powetrain_json**: relative path to powertrain json file with respect to `base_json_path` (e.g.: `hmmwv/powertrain/HMMWV_ShaftsPowertrain.json`)
- **tire_json**: relative path to tire json file with respect to `base_json_path` (e.g.: `hmmwv/tire/HMMWV_Pac02Tire.json`)
- **base_json_path**: path to …
=> Chrono JSON vehicle definition

PythonAPI/test/smoke/__init__.py, PythonAPI/test/smoke/test_sensor_determinism.py, PythonAPI/test/smoke_test_list.txt, Util/BuildTools/Check.sh
Minor modification of the smoke test pipeline to execute all the tests in a predetermined order. This allows us to have consistency between local and build executions and to have a more robust test pipeline.
The list of smoke tests is stored in the file  `smoke_test_list.txt`. In extra tests are added this file need to be updated.
Fixes # 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3942)
=> Smoke test are now executed in a predetermined order

CHANGELOG.md, PythonAPI/carla/agents/navigation/local_planner.py, PythonAPI/carla/agents/navigation/local_planner_behavior.py
By default, the local planner never stops adding waypoints to the buffer, making the vehicle move aimlessly around the town forever. However, this behavior is stopped whenever a global plan is set up. This PR adds a new argument that makes it optional.
With an example:
- Random control around town -> Set a lane change plan -> vehicle stops at the end of the lane change
- Random control around town -> Set a lane change plan -> vehicle stops at the end of the lane change / keeps moving randomly (both options are available, being the first one the default one)
--- …
=> Improved local planner set_global_plan function

LibCarla/source/carla/streaming/detail/tcp/Client.cpp
At the time we close a stream, we were receiving an error because the socket was closed by the local system, showing the warning in the log console. If that happens when we close the stream, then we don't need to show the warning because that is something decided by the user.
* **Platform(s):** Windows, Ubuntu
Not sure why we didn't get this warning message in previous versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3948)
=> Ignore any error coming from a closed socket

Docs/ref_sensors.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp, Util/BuildTools/Package.bat
Updated the auto exposure value for Linux to compensate for UE 4.26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3947)
=> Updating exposure value in Linux and UE 4.26

CHANGELOG.md, LibCarla/source/carla/geom/Math.cpp
This PR fixes a bug in the GetUpVector function of Carla transforms.
Fixes #  
#3763 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3979)
=> Fix Transform::GetUpVector()

Docs/index.md, Docs/python_api.md, PythonAPI/docs/doc_gen.py
I have put a warning on the Docs home page and on the Python API to warn users that they should change the docs to the correct version of the docs they want. I have clarified that "Latest" points to documentation from the dev branch so it will contain references to features that are not available in packaged versions as well as improved documentation.
I have not yet changed where the "latest' branch points to on readthedocs.org's admin panel because I want there to be information about it on the documentation first so that people don't get confused. What I will do is change:
- Default version -> 0.9.11 (The version of your project that / redirects to)
- Default branch -> dev (What branch "latest" points to.)
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Warning that "latest" version of docs is dev branch

CHANGELOG.md, LibCarla/source/carla/streaming/detail/tcp/Client.cpp, Util/BuildTools/Setup.sh, Util/InstallersWin/install_rpclib.bat
The **no_delay** socket option was only enabled on stream sockets on the server side, but not on the client side (client send the stream id at the beginning through the steam) and also not in any of the RPC sockets, causing a discontinuous delay on the tick() packet.
We have changed the RPCLib fork to enable this option on both client and server RPC. 
Now we are using the RPCLib tag v2.2.1_c5
* **Unreal Engine version(s):** UE 4.26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4041)
=> Enable the no_delay option on sockets

CHANGELOG.md, LibCarla/source/carla/client/Client.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, PythonAPI/carla/source/libcarla/Client.cpp, PythonAPI/carla/source/libcarla/libcarla.cpp, PythonAPI/docs/client.yml, PythonAPI/examples/start_replaying.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
This PR adds a new flag to the replayer to enable/disable the spawn of sensors from the recorded session.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4046)
=> Optional sensor replay

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Radar.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp
We observed that the parallel implementation of the raycasting sensors was performing badly in systems with a large number of cores with low computing capacity.  We added in the engine a new function that compute raycasts without blocking the physics scene internally so we can increase the performance of our implementation.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4080)
=> Improved parallelism of raycast sensors

Docs/adv_opendrive.md
Some users have needed help due to not realising they need write permissions on a certain directory when using the Opendrive standalone mode. I have added a note on that doc page about the error that can happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4078)
=> Added note about permissions

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp
The IMU was some rare cases near the return zero was given nans.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4135)
=> Fix IMU: In some rare cases was given nans

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.h, Unreal/CarlaUE4/Plugins/CarlaExporter/Source/CarlaExporter/Private/CarlaExporter.cpp, Util/BuildTools/Import.py, Util/DockerUtils/fbx/src/FBX2OBJ.cpp
Now we can import large maps in tiles, resulting in a individual .umap per tile.
As before, if you don't specify a .json file when importing, one is created automatically. A sample one is like this:
> {
>    "maps": [
>       {
>          "name": "testmap",
>          "xodr": "./testmap.xodr",
>          "use_carla_materials": true,
>          "tiles": [
>             "./testmap_Tile_0_0.fbx",
>             "./testmap_Tile_0_1.fbx",
>             "./testmap_Tile_1_0.fbx",
>             "./testmap_Tile_1_1.fbx"
>          ]
>       }
>    ],
>    "props": []
> }
For the automatic generation of .json to work, we need to be sure that the tile have this nomenclature ..._Tile_i_j...
the _i_ and _j_ are the index of the tile, starting at (0,0). The import process will end as soon as one tile is …
=> New import process to cook large maps divided in tiles

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/MapGen/ProceduralBuilding.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/MapGen/ProceduralBuilding.h
Fix for mobility warnings in Town10HD. This will avoid future warnings when creating new buildings, however town10HD buildings themselves have to be modified (via editor) in order to stop those warnings. This is because the instances have already been made with the old version of "ProceduralBuilding.cpp" (before this fix).
Fixes #  
* **Platform(s):** Windows & Linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4156)
=> Fix for warnings of mobility type in buildings

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/GnssSensor.cpp
This PR fixes the GNSS sensor for large maps. As the world origin is dynamic in large maps the sensor was not taking into account the shift with respect to the global origin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4403)
=> Fix gnss largemap

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorRegistry.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorRegistry.h
Added capability to detect when an UE actor has been destroyed by unreal (out of bounds) or by the large map system. When unreal destroys an actor, it is removed from the registry. This fixes crashes when actors move out of bounds or other reasons.
Destroying actors is very slightly more expensive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4364)
=> Fix crash when unreal destroys an actor

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLight.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLight.h
This PR fixes an issue where the street lights did not register in _Opt maps when starting the map. The GameMode now ensures that the lights are registered and ready to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4416)
=> Fix streetlights for opt maps

CHANGELOG.md, LibCarla/source/carla/client/Client.h, LibCarla/source/carla/client/FIleTransfer.cpp, LibCarla/source/carla/client/FileTransfer.h, LibCarla/source/carla/client/Map.cpp, LibCarla/source/carla/client/Map.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/client/detail/WalkerNavigation.cpp, LibCarla/source/carla/rpc/MapInfo.h, PythonAPI/carla/source/libcarla/Client.cpp, PythonAPI/util/environment.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveGenerator.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightManager.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/NavigationMesh.cpp
Required map files (OpenDRIVE, Traffic Manager...) are now downloaded from the server to the client local cache.
This local cache is stored by default in a folder called carlaCache under the User (Windows) or Home (Linux) folder.
It can be changed with the `set_files_base_folder` command.
To get the names of the required files for the current map use the `get_required_files` command.
Optionally, you can specify a folder under the current loaded ".umap" location to look for the files (e.g. "OpenDrive" to just get the files inside that folder), and you can either store the files or just get the names.
To download a exact file for the current map use the `request_file` command, passing its path and name starting from the current loaded ".umap" location (e.g. "OpenDrive/Map_1.xodr").
* …
=> Required files from server to client cache

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.h
The creation of FCollisionQueryParams object inside each raycasting point was slowing down some threads breaking the parallel speedup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4427)
=> Fix for parallel LiDAR

Jenkinsfile, Unreal/CarlaUE4/Config/DefaultEngine.ini, Unreal/CarlaUE4/Config/DefaultGame.ini
Now Town10HD_Opt is the default one when you start the server or UE4 editor.
So, the maps on each package are:
* Carla:
* Town01 and Town01_Opt
* Town02 and Town02_Opt
* Town03 and Town03_Opt
* Town04 and Town04_Opt
* Town05 and Town05_Opt
* Town10HD and Town10HD_Opt (loaded by default)
* AdditionalMaps:
* Town06 and Town06_Opt
* Town07 and Town07_Opt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/3951)
=> Town10 by default

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp
This PR fixes the collision sensor as it was reporting blank names of the collided objects. Now the correct string is used to identify the type of object the sensor has detected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4449)
=> Fix colision sensor

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h
Enabled overlap events on all meshes in the world so CarSim and Chrono detect collisions correctly. Also added error messages to log if there are empty meshes detected in the world.
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4088)
=> Enabled overlap events on static meshes and log error messages when meshes in world are empty

Util/BuildTools/Linux.mk, Util/Docker/Carla.Dockerfile, Util/Docker/Prerequisites.Dockerfile, Util/Docker/docker_tools.py
Until now CARLA and its docker were using official versions of UE4.
With the new upcoming version 0.9.12 CARLA uses a new forked version of UE 4.26, so we need to download that for the docker also. That means that the user needs to provide to the docker commands the login credentials of Github-Epic account to be able to download the repo.
Also we remove the use of **ue4-docker** because it was using official versions.
The user in docker now is **carla**, instead of **ue4**.
* **Python version(s):** Python 3
* **Unreal Engine version(s):** UE 4.26
To build the docker pre-requisites, we need to provide credentials of the user Epic account.
--- …
=> Docker now uses CARLA forked UE4.26 version, instead of the official

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp
This PR fixes pedestrian animation death as motion commands where being executed despite the pedestrian being dead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4454)
=> Fixed pedestrians being moved after dying.

Docs/build_faq.md, Docs/build_windows.md
Updated mentions to VS 2017 -> 2019 and UE2.24 -> 4.26 in windows build and FAQ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4460)
=> [NO_BUILD] Updated VS and UE versions in build docs and FAQs

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightManager.cpp
Quick fix for detecting speed limits of 70 and 80 and match with signals placed in the map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4464)
=> Fix speedlimit matching for 70 and 80 signals

CHANGELOG.md, Util/Docker/Release.Dockerfile
Fixes issue #4498 by adding missing dependency `libomp5` to `Release.Dockerfile`; per [suggestion by @mawi42](https://github.com/carla-simulator/carla/issues/4498#issuecomment-894062648)
* **Platform(s):** ... 18.04.3
* **Python version(s):** ... 3.6.9 
* **Unreal Engine version(s):** ... 4.26
An additional package from the Ubuntu repository has been installed using apt, which means possible introduction of bugs, security vulnerabilities, license issues, etc. relating to the additional package as well as a slightly larger image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4538)
=> add missing libomp5 package to Release.Dockerfile, see issue 4498

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLight.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLight.h
This PR fixes a possible crash on start up related to the UCarlaLight class. This crash was happening in the debug builds and docker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4622)
=> Fix UCarlaLight crash

LibCarla/source/carla/trafficmanager/InMemoryMap.cpp
This PR fixes a bug reading the `is_junction` and `geodesic_grid_id` parameters in the cached InMemoryMap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4642)
=> [TM] Fix bug reading cached InMemoryMap

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorRegistry.cpp
This PR removes a redundant and unnecessary check in actor deletion that caused a crash on the server when using the playback feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4657)
=> Fix editor crash with playback

CHANGELOG.md, PythonAPI/carla/agents/navigation/global_route_planner.py
Ensure waypoint.right_lane_marking/left_lane_marking exist before
accessing
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4676)
=> Fix global route planner python agent

LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/rpc/FloatColor.h, LibCarla/source/carla/rpc/MaterialParameter.cpp, LibCarla/source/carla/rpc/MaterialParameter.h, LibCarla/source/carla/rpc/Texture.h, LibCarla/source/carla/sensor/data/Color.h, PythonAPI/carla/source/libcarla/Blueprint.cpp, PythonAPI/carla/source/libcarla/SensorData.cpp, PythonAPI/carla/source/libcarla/World.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/BoundingBoxCalculator.cpp
This pull request brings to CARLA the capability to change textures of objects in the scene in runtime.
Object are anything in the scene using textures, the following functions have been added to the `World` in order to manage texture updating:
`get_names_of_all_objects`: returns the names of all objects in the scene.
`apply_color_texture_to_object`: Applies an 8bit per channel, RGBA texture to an object (uint8 values).
`apply_float_color_texture_to_object`: Applies an 32bit per channel, RGBA texture to an object (float values).
`apply_textures_to_object`: Applies the full set of textures (Diffuse, Normal, Emissive, ARME) to an object.
The plural versions of these functions allow to apply the same texture to multiple items.
The new enum `MaterialParameter` defines what texture parameter …
=> Runtime texture update

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedComponent.cpp
Quick fix to prevent proxies to generate shadows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4853)
=> Quick fix shadows

PythonAPI/examples/manual_control_steeringwheel.py
It fixes the errors arising due to `map_name` being called which is not an attribute of `world`
Fixes #  
* **Python version(s):** Python 3.6.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4858)
=> Fixed an error caused during map name being called

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp
Packaging of props in custom packages no longer works correctly on linux due to a bug introduced in [d04b4ae29](https://github.com/carla-simulator/carla/commit/4d04b4ae29ab3738ccfb5d3c4d7b7d05680757dc). This PR fixes that bug.
Fixes (https://github.com/carla-simulator/carla/issues/4363#issuecomment-943465782)
* **Python version(s):** 3.7,3.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/4873)
=> fix props not getting packaged on linux

CHANGELOG.md, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/trafficmanager/ALSM.cpp, LibCarla/source/carla/trafficmanager/ALSM.h, LibCarla/source/carla/trafficmanager/AtomicActorSet.h, LibCarla/source/carla/trafficmanager/CollisionStage.cpp, LibCarla/source/carla/trafficmanager/CollisionStage.h, LibCarla/source/carla/trafficmanager/LocalizationStage.cpp, LibCarla/source/carla/trafficmanager/LocalizationStage.h, LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp, LibCarla/source/carla/trafficmanager/MotionPlanStage.h, LibCarla/source/carla/trafficmanager/RandomGenerator.h, LibCarla/source/carla/trafficmanager/TrafficLightStage.cpp, LibCarla/source/carla/trafficmanager/TrafficLightStage.h, LibCarla/source/carla/trafficmanager/TrafficManagerLocal.cpp, LibCarla/source/carla/trafficmanager/TrafficManagerLocal.h, PythonAPI/carla/source/libcarla/Client.cpp, PythonAPI/test/smoke/test_determinism.py
This PR fixes some non-deterministic behaviors that were introduced after 0.9.11. These includes:
- Sorting the vehicles at the *ApplyBatchSync* so that the TM always registers them in the same order, avoiding the need to sort them 
- Changed one variable from *unordered map* to *map*, avoiding having to sort it when looping through its keys.
- TM now uses one global seed for all vehicles, instead of one per vehicle.
- Changing a vehicle's physics is now a synchronous call. Due to its high interaction with other commands, as well as its expensive computations, the async nature of the call was causing other commands called after this one, to sometimes finish earlier, breaking determinism and creating unexpected behaviors 
- Updated the determinism smoke test to also use the hybrid mode
* …
=> TM determinism fixes

LibCarla/source/carla/MsgPackAdaptors.h, LibCarla/source/carla/RecurrentSharedFuture.h, LibCarla/source/carla/client/detail/ActorVariant.cpp, LibCarla/source/carla/client/detail/ActorVariant.h, LibCarla/source/carla/nav/WalkerEvent.h, LibCarla/source/carla/nav/WalkerManager.cpp, LibCarla/source/carla/rpc/Command.h, LibCarla/source/carla/rpc/DebugShape.h, LibCarla/source/carla/rpc/Response.h, LibCarla/source/carla/trafficmanager/VehicleLightStage.cpp, LibCarla/source/test/common/test_msgpack.cpp, PythonAPI/carla/source/libcarla/Client.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Trigger/TriggerFactory.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/BoundingBoxCalculator.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/DebugShapeDrawer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Walker/WalkerController.h, Unreal/CarlaUE4/Source/CarlaUE4.Target.cs
boost::variant only supports up to 20 types (MPL limit). boost::variant2
has no such limit; switch to it.
* **Platform(s):** Linux/ubuntu 18.04, Windows 10
* **Python version(s):** 3.8 (windows and linux)
None known.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5284)
=> Switch to boost::variant2

Docs/requirements.txt
Update mkdocs and jinja to fix readthedocs build failures
mkdocs == 1.2.3
jinja2==3.0.3
Fixes #  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5361)
=> update mkdocs and jinja versions

CHANGELOG.md, LibCarla/source/carla/road/Map.cpp, PythonAPI/carla/agents/navigation/global_route_planner.py
When using the `Map.get_topology`, there is an error that causes lanes with no successors to not be added. This resulted in something like the image below, where the red lines are the lanes part of the topology. As it can be seen, the topology is missing the lane on the left.
This is caused because the topology pairs the start of one lane with the start of the next ones. As such, if no successors are found, the lane's starting point isn't linked with anything. This has been changed and now, if no successors are found, the start of the lane is paired with the its end.
This changes the topology a bit, so there might be some cases where some logic is affected. I don't think this happens …
=> Fix topology with ending lanes

LibCarla/source/carla/client/LightManager.cpp, LibCarla/source/carla/client/LightManager.h, LibCarla/source/carla/client/detail/Episode.cpp
This PR fixes bugs with the lights systems, where the light commands become unresponsive after loading a new map and blocked the client if updating light twice.
Under the hood, the lights were not updating their state when the map changed and a mutex was being locked twice by the same thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5396)
=> Fixing light system bugs

CHANGELOG.md, PythonAPI/carla/agents/navigation/basic_agent.py, PythonAPI/carla/agents/navigation/behavior_agent.py, PythonAPI/carla/agents/navigation/constant_velocity_agent.py, PythonAPI/carla/agents/navigation/local_planner.py
The Python API agents now have two additional optional inputs. *map_inst* is meant to be a **carla.Map** instance while *grp_inst* is an instance of the **GlobalRoutePlanner** class. 
Both of these classes are, by default, computed by the BasicAgent on initialization, but they are a **very expensive call for large maps** (up to several seconds). As these classes only depend on the static topology and, as such, won't be changed during the simulation, these new inputs can speed up the initialization of the agents
None? Nothing is removed and by default it still works the same as before
--- …
=> Extended Python agents initializations

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/SignComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/SignComponent.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/StopSignComponent.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/TrafficLightComponent.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/YieldSignComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Traffic/YieldSignComponent.h
This PR modifies the location and shape of the trigger bounding boxes for the procedural traffic signs. It only affects to traffic lights, stops and yields.
The new algorithm prevents adding trigger boxes inside the intersection. It works in the following way:
1. If the landmark is not located inside an intersection, the center of the trigger box corresponds to the position of the landmark.
2. If the landmark is located inside an intersection it gets a previous waypoint (2m) and checks the number of predecessors. If there is only one possible predecessor we use this location as the center of the bounding box. Otherwise the landmark location is used. 
The shape of the trigger box has been also modified. Previously, the trigger box was a cube with dimension 90% of the lane width. To avoid …
=> Prevent adding trigger boxes inside the intersections

CHANGELOG.md, LibCarla/source/carla/trafficmanager/ALSM.cpp, LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp, LibCarla/source/carla/trafficmanager/MotionPlanStage.h, LibCarla/source/carla/trafficmanager/SimulationState.cpp, LibCarla/source/carla/trafficmanager/SimulationState.h
Fixed a bug that caused the TM to sometimes calculate a vehicle's speed as a ridiculously high number.
The TM calculates the speed of physicsless vehicles as the position difference between ticks. However, this fails if another client teleports the vehicle, creating an insanely high spee , and generally causing the LocalizationStage to try to create a larger waypoint buffer than the map, blocking the simulation.
As such, a new `hybrid_end_location` has been added, which is the location that the TM calculates for that vehicle at the end of its execution, and it's that position, and not the one gottetn by the server, the one that's used to calcualte the speed. For all other purposes, the "normal" position is used.  
* **Unreal …
=> Fix TM blocking the simulation

CHANGELOG.md, LibCarla/source/carla/trafficmanager/Constants.h, LibCarla/source/carla/trafficmanager/DataStructures.h, LibCarla/source/carla/trafficmanager/LocalizationStage.cpp, LibCarla/source/carla/trafficmanager/TrafficLightStage.cpp, LibCarla/source/carla/trafficmanager/TrafficLightStage.h
Improved how the TM vehicles handle the non signalized intersections, resulting in an overall more fluid traffic.
Previously, a series of tickets where issued according to their time of arrival, which dictated the order of the vehicles. However, this approach had some minor bugs that caused vehicles to wait, even though the junction was empty, and overall, their behavior wasn't that intuitive.
The new approach creates a list of all entering vehicles according to their order of arrival. From there, lane priority is given to the first vehicle that arrived, and once its maneuver ends, the next one starts entering the junction. To have a smoother traffic, the maneuver ends when the vehicle has left the center of the intersection behind, and not once it has exited the junction. Note that while …
=> Improved TM's non signalized junctions

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/RayTracer.cpp
Fixed raycasting functions at large maps. While the points sent to these functions were indeed transformed from global to local coordinates (and as such the functions were correctly calculating the raycast hit), the resulting hit location wasn't being transformed back to global coordinates, so the API returned an incorrect location. This PR adds the missing transform.
* **Unreal Engine version(s):** CARLA's 4.26
Theoretically none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5461)
=> Fixed raycasting functions at large maps

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLight.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Lights/CarlaLightSubsystem.cpp
The location of the street lights was incorrect for those that are part of large maps, as the large map transform was missing
EDIT: Additionally, updated the (un)registering of street lights to forcefully update the client, as without it, they were receiving outdated information 
* **Unreal Engine version(s):** CARLA's 4.26
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5465)
=> Fixed street lights at large maps

LibCarla/source/carla/trafficmanager/SimulationState.cpp
This PR disables the notification of the green-yellow state transition to Traffic Manager vehicles. This is done to avoid having vehicles stopped very near the intersection when only the rear part of the vehicle is colliding with the trigger volume of the traffic light.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5596)
=> Avoid notification of green-yellow state to TM vehicles

PythonAPI/carla/agents/navigation/basic_agent.py
The added lane change was breaking if any of its paramters was zero, as they were being used to do a `wp.next()`, so it can't be 0 now
* **Platform(s):** Ubutnu 18.04
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5610)
=> Fixed Agents bug for 0 distance lane change

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.h
When a map is imported, some decals are created over the road to add dirty. Those decals are configured through a .json file and also use the .xodr of the map. But in the import process those files were find in all the content of the project and not only on the content of the package created. That means that if other .json file or .xodr was found, that was used instead of the correct one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5588)
=> Fixed decals when importing a map

CHANGELOG.md, LibCarla/source/carla/road/MapBuilder.cpp
When moving signals out of roads we now compute the desired displacement direction. Instead of moving signals always to the right we now check the right and left lane types.
The algorithm works in the following way:
1. If the right lane is of type `Driving` we move the signal to the left.
2. If the left lane is of type `Driving` we move the signal to the right.
3. If both lanes (right and left) are of type `Driving` we don't move the signal.
* **Python version(s):** 3,7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5673)
=> Compute displacement direction when moving signals

Util/BuildTools/BuildUtilsDocker.sh
When trying to download fbxsdk in Util/BuildTools/BuildUtilsDocker.sh a 403 forbidden error was being raised. This was resolved with the following change.
Fixes #  
* **Platform(s):*Linux 18.04 LTS* ...
* **Python version(s):*3.6.9* ...
* **Unreal Engine version(s):*4.26* ...
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5631)
=> Updating wget when downloading fbxsdk

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/StaticMeshFactory.cpp
Fix  the static mesh prop factory, that allow to load static meshes from resources in real time.
At the same time, we added attributes as **mass** and **scale**.
The attributes are:
- mesh_path: with the path to the resource, as "/Game/..."
- mass: if a mass different of 0 is defined, the asset will be setup as **movable** object, otherwise it will be **static**
- scale: scale for the mesh if any
A simple sniped of how to use it is:
```
client = carla.Client('localhost', 2000)
world = client.get_world()
bp = world.get_blueprint_library().find("static.prop.mesh")
bp.set_attribute('mesh_path', "/Game/Carla/Static/Vehicles/4Wheeled/ParkedVehicles/TeslaM3/SM_TeslaM3_parked.SM_TeslaM3_parked")
bp.set_attribute('mass', "1000")
bp.set_attribute('scale', "0.9")
spawn_point = carla.Transform() …
```
=> Fix the static mesh factory

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp
When a map has no spawn points, automatically several are created (reading the information of the openDRIVE file), and those spawn points are placed at 3m over the road. Now we change that height to only 0.5m, avoiding problems of spawning vehicles over others below.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5754)
=> Fixing spawn points height (from 3m to only 0.5m)

CHANGELOG.md, PythonAPI/carla/agents/navigation/basic_agent.py
Removed a return at the basic agent's vehicle detection algorithm. This was causing the algorithm to prematurely stop after finding a close-by vehicle that wasn't an obstacle, failing to check the rest of the cloes-by vehicles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5824)
=> Fixed bug at agent's vehicle detection

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Trigger/FrictionTrigger.cpp
In case the OtherActor is not a Vehicle just return
Fixes #  
* **Platform(s):** ... Ubuntu 20.04
* **Python version(s):** ... 3.7
* **Unreal Engine version(s):** ... 4.26
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5838)
=> Prevent from segfault OnTriggerEndOverlap

Util/BuildTools/Setup.sh, Util/InstallersWin/install_xercesc.bat
This PR fixes a dependency issue with libxerces-c
* **Platform(s):** Ubuntu 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5848)
=> Fix dependencies

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/VegetationManager.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vegetation/VegetationManager.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.h
The vegetation manager now spawns the elements closer to a distance.
This fixes the problem with the elements being spawned too far and destroyed instantly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5881)
=> Spawn Foliage with distance filter

Util/BuildTools/Package.sh
Fix the Package.sh script that when you use the **--no-zip** option it won't copy the openDrive and binary files into the target package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5908)
=> Fix Package.sh script

CHANGELOG.md, LibCarla/source/carla/client/detail/Episode.cpp, LibCarla/source/carla/client/detail/Episode.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/WalkerNavigation.cpp, LibCarla/source/carla/nav/WalkerManager.cpp
This is a fix for three different problems identified related to the skeleton of a pedestrian:
1. The skeleton of a pedestrian at some points was displaced from the body. That was caused by getting the bones of the pedestrian at the wrong moment. 
2. In function of the network congestion, could happen that the server start to build the frame before all the pedestrian position are updated from the client (pedestrian navigation is managed in the client side). That has been fixed using a synchronous call instead of an asynchronous call. So in synchronous mode now we are sure to update all pedestrian positions before do the tick.
3. When a pedestrian was reaching a point of the path for the route he is following, it was stop by 1 frame, and that was causing an interference of the animation …
=> Fix pedestrian bones displaced from body

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp
We had a double std::move() on the same variable, causing undefined behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5977)
=> Fixing recorder, some data was not properly being recorded

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/StaticMeshFactory.cpp
The retrieval of optional attributes from the definition of the static mesh was wrong
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5982)
=> Fixing the retrieval of optional attributes

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderHelpers.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderHelpers.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderQuery.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderQuery.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderVisualTime.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderVisualTime.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderWalkerBones.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderWalkerBones.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h
The recorder now can store the bone position of the pedestrian skeleton. We need to enable the additional data flag for the recorder. Then the replayer will pose the pedestrians at the exact pose each frame.
Fixes #4980, #4975
Recorder files a bit bigger due to the increment of data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/5987)
=> Recorder with skeleton bones

LibCarla/source/carla/client/ServerSideSensor.cpp, PythonAPI/examples/manual_control_gbuffer.py
This PR adds a type check when using the GBuffer API, to ensure that only sensors of type "sensor.camera.rgb" can use these methods.
* **Unreal Engine version(s):** CarlaUnreal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6001)
=> Add sensor type check.

LibCarla/source/carla/multigpu/primaryCommands.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h
Added the command LOAD_MAP for multi-GPU mode. Now, whenever the primary server loads a new map, the connected secondary servers will load the same map also.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6014)
=> Multi-GPU load map command

CHANGELOG.md, LibCarla/source/carla/trafficmanager/MotionPlanStage.cpp
When the Traffic Manager has the `set_respawn_dormant_vehicles` `parameter activated, it will detected dormant actors and respawn them closer to the ego vehicle.
While this works fine, using this with hybrid mode was causing the simulation to run substantially slower. This is because the teleportation makes the TM bug out and think that the vehicle is moving extremely fast, resulting in a ridiculously long waypoint buffer. 
This PR makes the TM update the saved state of the teleported vehicle,  removing the aforementioned bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulat …
=> Fix TM hybrid respawn bug

LibCarla/source/carla/multigpu/router.cpp, LibCarla/source/carla/multigpu/router.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaEngine.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.h
In multi-GPU, each time a new connection is done (secondary server connecting to the primary server), with the frame data we include all existing actors, so that way all the traffic lights and other actors are sent to all secondary servers (specially the new one).
Will happen that we send actors that already exist on some secondary server. So if the actor with the Id is found, the actor is not created but reused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6058)
=> Multi-GPU synchronization of actors like TrafficLights

Docs/adv_multigpu.md
Minor typo in the Multi-GPU docs...
There should only be one dash before `-nullrhi` argument.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6113)
=> Remove extra dash from -nullrhi in Multi-GPU docs

Docs/core_actors.md
Fixes #  Typo for document at https://carla.readthedocs.io/en/latest/core_actors/#sensors
* **Python version(s):** 3.9.12
* **Unreal Engine version(s):** not needed
Noting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6112)
=> fix document typo for lambda expression section

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Restoring gamma value to 2.2
Fixes #6103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6124)
=> Restore gamma value to 2.2 (instead of 2.4)

CHANGELOG.md, PythonAPI/carla/agents/navigation/basic_agent.py, PythonAPI/carla/agents/navigation/controller.py, PythonAPI/carla/agents/navigation/local_planner.py
While the Python agents could have an offset, this value wasn't exposed so it couldn't be changed in runtime. Well, not anymore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6005)
=> Exposed Python agents' offset

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/UtilActorFactory.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/UtilActorFactory.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/MapGen/LargeMapManager.cpp
Adds a new actor type: util.actor.empty. Which creates an actor with a transform that can be queried.
In addition, it can be used in large maps as the reference actor (the rolename should be set to `hero` or `ego_vehicle`).
This PR requires the content branch `axel/empty_actor`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6136)
=> Empty actor

CHANGELOG.md, LibCarla/source/carla/trafficmanager/ALSM.cpp, LibCarla/source/carla/trafficmanager/ALSM.h
The Traffic Manager has a logic that checks there are no vehicles stuck, removing them after a certain amount of time has passed without them moving. This logic, however, is broken in two ways, which this PR fixes them.
1) When deciding which vehicle is the "most stuck" (aka the one that has been stopped the most time), the logic considered all hero vehicles, regardless of whether or not they were part of the TM. This breaks the logic if an unregistered hero is the one actually stuck.
2) The time needed to be considered stuck is increased for vehicles are red lights / stops, but the differentiation between this and the "normal" case is not done correctly. 
Fixes #6110
- - -
This change …
=> Fixed Traffic Manager's unstuck logic

CHANGELOG.md, LibCarla/source/carla/client/Client.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, PythonAPI/carla/source/libcarla/Client.cpp, PythonAPI/examples/start_replaying.py, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayer.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
When using a package to record and replay a simulation, the spectator can be replayed or not with this new API function/flag.
By default the spectator is ignored when replaying.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6166)
=> Adding --ignore-spectator to the replayer

LibCarla/source/carla/client/ActorAttribute.h, LibCarla/source/carla/client/BlueprintLibrary.cpp, LibCarla/source/carla/client/BlueprintLibrary.h, PythonAPI/carla/source/libcarla/Blueprint.cpp, PythonAPI/docs/blueprint.yml
Extended Python API to be able to filter blueprints by attributes.
Passing non string params will result in pyhton script crash.
Passing bad param will return a empty list.
Tested with generation_traffic.py and manual_control.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6193)
=> added filter by attribute to python api

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/LoadAssetMaterialsCommandlet.cpp
When the import script runs to import a large map, it searches for a TilesInfo.txt file to know where the top,left cell has the center in the world. The problem is that in the destination folder can exist other large maps with that file, and the import script was searching recursively from the base folder (the package folder) and was taking the first TilesInfo.txt found, that could be from another existing map.
That has been fixed, and now the TilesInfo.txt file is searched only in the destination map folder, instead of the destination package folder.
- - - …
=> Fixing import script that can find a TilesInfo.txt from other existing map

PythonAPI/carla/source/libcarla/Client.cpp
Added default values to the *host* and *port* arguments of the carla.Client(), so that now it can initialized directly with 
```py
client = carla.Client()
```
instead of 
```py
client = carla.Client('127.0.0.1', 2000)
```
This now also matches the docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6429)
=> Added default values to carla.Client()

Docs/python_api.md, PythonAPI/docs/client.yml
A typo with the word `maximum`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6440)
=> Fix a typo in Client.set_timeout() documentation

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/Tagger.cpp
This PR enables the ticks of the UTaggedComponent to those representing skeletal meshes. This should improve performace on maps with many static actors.
Instance semantic segmentation should be tested after this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6443)
=> Fixed tagged component ticks

Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Private/EditorCamera.cpp, Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/Public/EditorCamera.h
This PR just adds a utility class to get/set the camera location and rotation (stored as transform).
When combined with a Blueprint, this is useful for capturing screenshots in the editor.
* **Unreal Engine version(s):** Carla (4.26)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6469)
=> Add EditorCameraUtils

LibCarla/source/carla/client/detail/Simulator.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Added the name of the map when the `map not found` error is triggered
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6528)
=> Added map name if not found

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp
When running Carla in multi gpu mode, a bug occurred when requesting the replayer to replay a previously recorded simulation. The code that caused this error has been updated in the AddVehicleWheelsAnimation function of the FrameData.cpp file, and the error has now been resolved.
Fixes #  
* **Platform(s):** Ubuntu 20.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6691)
=> Fixing replayer crash when running in multi gpu mode

CHANGELOG.md, LibCarla/source/carla/client/Client.h, PythonAPI/carla/source/libcarla/Client.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp
A new function called load_world_if_different("map_name") has been added in /carla/PythonAPI/carla/source/libcarla/Client.cpp and /carla/LibCarla/source/carla/client/Client.h. This function loads a map only if the requested map is different from the current map and does nothing if the maps are the same.
By adding this new function, to be used from the PythonAPI, a user can load a map avoiding the reset of the session that occurs when loading a map that is the same as the one currently running (as happens with the function load_world). 
Fixes #  
* **Platform(s):** Ubuntu 20.04.6 LTS
- - - …
=> Adding a new function that loads a map only if it is different

CHANGELOG.md, Docs/build_windows.md, Util/BuildTools/BuildLibCarla.bat, Util/BuildTools/BuildOSM2ODR.bat, Util/BuildTools/Setup.bat, Util/BuildTools/Windows.mk, Util/InstallersWin/install_chrono.bat, Util/InstallersWin/install_gtest.bat, Util/InstallersWin/install_proj.bat, Util/InstallersWin/install_recast.bat, Util/InstallersWin/install_rpclib.bat, Util/InstallersWin/install_xercesc.bat
Fixes #  
The current Windows build system was hard-coded to only work with Visual Studio 2019. This change opens it up to using other visual studio versions and build systems such as Ninja which is already being used for the Linux build. Every build script has an extra "generator" flag that can override the default setting of Visual Studio 16 2019 which is still the default version used. Documentation has also been updated to reflect this. 
* **Python version(s):** N/A
* **Unreal Engine version(s):** N/A
I do not forsee any negative impacts since the default build method is still there (MSVC 2019), this change just makes it easier for others building libcarla to integrate it into their own cmake builds.
- - - …
=> Add VS2022 and Ninja build support for Libcarla and OSM2ODR on Windows

Docs/python_api.md, PythonAPI/docs/map.yml
Hi team, this pr is minor I think, but can be important for better documentation.
While I was reading the python api documentations, I just found a duplicated instance variable is written.
You may see the image below contains two `is_junction`s.
I just updated a document for python api.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6702)
=> Remove duplicated instance variable `is_junction`

CHANGELOG.md, PythonAPI/carla/source/libcarla/Client.cpp, PythonAPI/carla/source/libcarla/libcarla.cpp
When using CARLA with Python 3.10, I'm getting a segfault in GetAvailableMaps. The problem disappears when PyList manipulation does not happen with GIL unlocked, as done in this commit.
The initial part of crash backtrace (from GDB) is below:
Program terminated with signal SIGSEGV, Segmentation fault.
warning: Section `.reg-xstate/49253' in core file too small.
#0  _PyInterpreterState_GET () at ./Include/internal/pycore_pystate.h:117
117	   return tstate->interp;
[Current thread is 1 (Thread 0x7fe6fe48f740 (LWP 49253))]
(gdb) bt
#0  _PyInterpreterState_GET () at ./Include/internal/pycore_pystate.h:117
#1  get_list_state () at Objects/listobject.c:26
#2  PyList_New (size=0) at Objects/listobject.c:159
#3  0x00007fe6fdc0dab0 in boost::python::detail::list_base::list_base() () from …
=> PythonAPI: Fix segfaults due to incorrect GIL locking

CHANGELOG.md, LibCarla/source/carla/trafficmanager/Constants.h, LibCarla/source/carla/trafficmanager/InMemoryMap.cpp
This PR solves a bug that caused the TrafficManager to abnormally control vehicles that where reaching an ending lane, such as when a road changes from 2 to 1 lane.
This was causes by a misslinkage in the TM's InMemoryMap, linking lanes that have no next one with themselves.
None?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6885)
=> Fix tm ending lanes

.readthedocs.yaml
Added .readthedocs.yaml file to address the issue that ReadTheDocs now will not build in the absence of a config file.
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6888)
=> Added readthedocs config file

LibCarla/source/carla/road/MeshFactory.cpp
When generating lanemarks with the digital twin tool, for broken lane lines with lane type None, the length of the unit vector director is 0 because the lane width is 0, resulting in endmarking values of (-nan, -nan, -nan).
Here, first determine whether the lane width is 0. If it is not 0, follow the original logic. If it is 0, use the other lane in the same lane_section to obtain the unit vector director.
* **Python version(s):** Python 3.7.16
* **Unreal Engine version(s):** 4.26-carla
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/6995)
=> Fix GenerateLaneMarksForCenterLine problem

LibCarla/source/carla/road/Map.cpp, LibCarla/source/carla/road/MeshFactory.cpp, LibCarla/source/carla/road/MeshFactory.h
This is a supplement and fix to my last PR: https://github.com/carla-simulator/carla/pull/6995
To calculate the edge points of lane markings, we need to compute the unit vector perpendicular to the lane line. In this process, if the coordinates of the two corners of the lane are equal, it will cause the error of dividing by 0.
The previous PR verifies if the lane width is 0 to avoid this error. However, even if the lane width is not 0, the two points on the edge of the lane may be the same, as in the picture. So I use "**if (edges.first! = edges.second)** "to avoid mistakes.
After testing for several times, it worked well.
In addition, this judgment needs to be made when generating the TreePosition.
* **Platform(s):** Ubuntu 20.04 + Windows 10
* **Python version(s):** Python 3.7.16
* …
=> Fix problems of lanemarking generation and tree generation

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameInstance.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.h
- Created a SensorSpawnerActor class that can be placed on a level and configure the sensors that we want to spawn.
- Added delegate to CarlaGameMode to know when the CarlaEpisode is initialised.
Fixes #  
* **Unreal Engine version(s):** UE 5.3
- Not tested on Ubuntu.
=> Creating SensorSpawnerActor to spawn custom sensors in the editor.

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/SensorSpawnerActor.h
- If enabled in the SensorSpawnerActor configuration, spawned SceneCaptures will save images to disk.
- The images are to be saved in /Saved/SensorSpawnerCaptures folder.
- It is possible to modify the time SceneCaptureCameras are taking captures and how often they are taken.
Fixes #  
* **Platform(s):** Windows 11
* **Unreal Engine version(s):** UE 5.3
Not tested on Ubuntu.
=> Added the option to save SceneCapture images to disk on SensorSpawner.

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Fix windows build broken due uninitialized variable error.
=> Windows build error: Fix uninitalized varaible error on windows build

CMakeLists.txt, Configure.py, LibCarla/cmake/ros2-native/CMakeLists.txt, LibCarla/source/carla/ros2/ROS2CallbackData.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorDispatcher.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs
- Implement ROS2 native build for UE5 Ubuntu.
- Changing ROS2 native build from static library to shared library to prevent mismatch between c++ library versions, as ROS2 is compiled with g++ old abi and Unreal is compiled with clang abi.
- ROS2 native library renamed from `libcarla_fastdds.a` to  `libcarla-ros2-native.so`.
- boost_asio and tinyXML libs are now downloaded and builded by fast-dds cmake internally.
- boost was reintroduced inside ROS2 native code to remove code from newer standards than C++11. Pending to see if it's possible to build ROS2 dependencies with a newer version of the standard.
- Added log for source download step.
=> Implement UE5 ROS2 native build with dynamic linking

Configure.py
ROS2 build fails when ROS2 is already installed on the system due memory vendor library cmake avoids to build when detecting is already present on the system. This causes memory `libfoonathan_memory-0.7.3.so` to not be built and installed.
Fixes #51
* **Platform(s):*Ubuntu 22.04 and 20.04* ...
* **Python version(s):*3.10* ...
* **Unreal Engine version(s):*5.3* ...
=> Ros2: Prevent memory vendor crash when ros2 is installed in the system

CMake/CarlaDependencies.cmake
Dependencies build time improved from 5:30 minutes to 30 seconds.
=> CMake improve boost fetch download speed

CMake/CarlaDependencies.cmake
Changed the way how FetchContent is downloading the source code. Previously was using git clone and now is downloading zip an uncompresing.
- Performance of download improved and cmake configuration step time was reduced 30% as result in average with a 1GB of download internet connection (speedup will be higher with slower connections).
- Theoretically reduced the number of build errors produced due git clone connection failures. Downloading just one file have less chance of error.
* **Platform(s):*Ubuntu 22.04* ...
* **Unreal Engine version(s):*5* ...
=> Cmake migrate FetchContent from git clone to zip download

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
If physics is turned off (with set_simulate_physics) and you call get_physics_control, you previously got a crash (as the PhysXVehicle was destroyed). Fix it so it provides old data instead of crashing
```
~/tmp/c0.9.15/n$ ./CarlaUE4.sh -log
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=131160 LargeMemoryPoolOffset=196744 
Malloc Size=131160 LargeMemoryPoolOffset=327928 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault
```
and 
```
>>> import carla
>>> c = carla.Client("127.0.0.1", 2000)
>>> w = c.get_world()
>>> m = w.get_map()
>>> bpl = w.get_blueprint_library()
>>> a = …
```
=> Allow GetVehiclePhysicsControl to succeed when physics is off

CMake/CarlaDependencies.cmake, Unreal/CMakeLists.txt
This PR reintroduces the launch-only target. Ubuntu testing is pending.
=> Reintroduce launch-only target.

Ros2Native/CMakeLists.txt
Create directory was not working for ROS2 native lib copy destination when need to create more than one level of directories.
* **Platform(s):** Ubuntu 20.0.4
=> Fix create diretory libcarlaros2native

Unreal/CMakeLists.txt
This PR removes boost numpy, as it is deprecated.
See https://github.com/ndarray/Boost.NumPy
=> Remove boost::numpy

Unreal/CMakeLists.txt
Use same package generation command arguments than in CARLA UE4.
This fix package generation that was previously crashing.
* **Platform(s):**Ubuntu 22.04
=> Fix package generation command in Ubuntu

Unreal/CarlaUnreal/Config/DefaultEditor.ini
Disable multiprocess cooking as is causing memory crash on Ubuntu.
Fixes #7429
=> Disable multi process cooking

Setup.sh
For some cases, relative path not works properly for linux toolchain file at cmake configure command.
This change has already been applied to the UE5 build docs, but was still missing to be applied to Setup.sh
=> Setup.sh: Use absolute path for linux toolchan file in cmake configure command

Unreal/CarlaUnreal/Config/DefaultEditorSettings.ini
Desactivate "Use Less CPU when in Background" option to prevent the eidtor get frozen when launching manual control.
https://udn.unrealengine.com/s/question/0D5QP00000BmhxS0AR/is-it-possible-to-have-the-use-less-cpu-when-in-background-disabled-by-default 
=> Activate high cpu on background

Docs/build_docker_unreal.md
Change docs from using Github Password to use Github Access Token
The docs for building Unreal from docker uses a password for authentication
```EPIC_PASS=<GitHubPassword>```
This is outdated since 2021 💀, changing it to 
```EPIC_PASS=<GitHubAccessToken>```
Mentioned in #6632
=>  Use Github Access Token instead of Github Password in build_docker_unreal.md

Unreal/CarlaUE4/Config/DefaultEditorSettings.ini
Desactivate "Use Less CPU when in Background" option to prevent the eidtor get frozen when launching manual control.
https://udn.unrealengine.com/s/question/0D5QP00000BmhxS0AR/is-it-possible-to-have-the-use-less-cpu-when-in-background-disabled-by-default 
=> Disable use less CPU in background

Util/BuildTools/BuildOSM2ODR.bat, Util/BuildTools/BuildOSM2ODR.sh
Retry download when fails for osm2odr.
OSM2ODR was making the build fail randomly and this was causing Jenkins and some contributors to fail on building CARLA.
* **Platform(s):** Windows 10, Ubuntu 22.04
* **Python version(s):** 3.10, 3.8
=> Retry download osm2odr

LibCarla/source/carla/FileSystem.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Two issues:
- If a second argument is not passed to the ValidateFilePath(...), the extension is replaced by an empty string. For this reason I am checking now if it is empty or not. To avoid this replacement
- Same in CarlaServer but for the path. That it adds additional /.
Fixes #  
* **Unreal Engine version(s):** UE5 Carla
=> Checking if path or extension is not empty

.gitignore, CMake/Options.cmake, CMake/Util.cmake, CMakeLists.txt, Examples/CppClient/CMakeLists.txt, LibCarla/CMakeLists.txt, PythonAPI/CMakeLists.txt, Ros2Native/CMakeLists.txt, Ros2Native/LibCarlaRos2Native/CMakeLists.txt, Unreal/CMakeLists.txt, osm-world-renderer/CMakeLists.txt
This PR introduces the following helper macros:
- carla_add_executable
- carla_add_library
- carla_add_custom_target
These all wrap the corresponding CMake commands, with the goal being to add extra documentation code in a similar fashion than seen in carla_option and carla_string_option.
This PR also adds two new options to print all relevant targets and options at configure time and to save it to /Help.md.
=> Introduce several helper macros and utilities for improved usability.

Util/BuildTools/Setup.sh
Fixes  #7633
The `sha256sum` check on the boost file returns a string in the format `<hash> <filename>` in the build script the string comparison fails because it only is checked against <hash>.
Applied solution and problem description see: https://unix.stackexchange.com/questions/265740/suppress-filename-from-output-of-sha512sum
Also prevents duplication of multiple boost tar files due to automatic renaming with numbers Credit to @MarcelPiNacy-CVC
---
* **Unreal Engine version(s):** 22.04
=> Fix double dowload of boost backup due to wrong string comparision with sha256sum

Util/BuildTools/Setup.sh
Going back to `patchelf` `0.12`. `patchelf` `0.14` is using `c++17` which is no compatible with CARLA build system.
=> Revert upgrade patchelf version

PythonAPI/test/smoke/test_sensor_tick_time.py
Not allow v2x sensor go through  tick tests. 
Fixes #  
=> Not tests V2X tick

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp
Lidar was not working with vehicles and walkers in replayer mode.
Manually tested in Ubuntu 22
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7733)
=> Fix lidar in replayer mode

Unreal/CarlaUnreal/Plugins/CarlaTools/Source/CarlaTools/Private/ProceduralBuildingUtilities.cpp, Unreal/CarlaUnreal/Plugins/CarlaTools/Source/CarlaTools/Public/ProceduralBuildingUtilities.h
-Creates function that lets the user creates an actor with the hierarchichal meshes that are currently set in the BP_ProceduralBuilding.
-Function done because when moving the building it quickly updates, making it impossible to maintain a setting the user is happy with
-Function takes the name of the static mesh used by the passed Hierarchichal mesh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7760)
=> Added extra functionality to the Procedural Building class

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderAnimVehicleWheels.cpp
**Description**
This pull request fix a bug about incorrect number of wheels on vehicles in multi-gpu mode.
WheelValues.reserve  will keep the wheels from all the vehicles before that one. 
Fixes #
**Where has this been tested?**
- Platform(s): Windows 11
- Python version(s): 3.10.14
- Unreal Engine version(s): 4.26
**Possible Drawbacks**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7800)
=> Fix incorrect number of wheels on vehicles

PythonAPI/carla/agents/navigation/basic_agent.py
Addresses #7341:   
[`set_destination`](https://github.com/carla-simulator/carla/blob/cead6d1b05e89ad84df80984f62daba57bb50e55/PythonAPI/carla/agents/navigation/basic_agent.py#L141) does not really use the `start_location`, only for boolean evaluation instead of allowing users to pass a location.
In my experiments this sometimes creates troubles when passing a starting point, e.g. for [tailgating](https://github.com/carla-simulator/carla/blob/cead6d1b05e89ad84df80984f62daba57bb50e55/PythonAPI/carla/agents/navigation/behavior_agent.py#L119-L120) the agent performs U-Turns to an old way point.
Note: Python code only
* **Python version(s):** 3.7, 3.10
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Agent's `set_destination` needs update in their logic and fix broken tailgating, but how?

CMake/Options.cmake
This PR fixes a configure-time error whenever BUILD_CARLA_UNREAL=OFF and the UE5 path is not set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7875)
=> Fix configure error when BUILD_CARLA_UNREAL=OFF

LibCarla/source/carla/trafficmanager/Constants.h
With the change to UE5, the TM's control was too soft, taking much longer to correct small deviations. This was causing the vehicles to do the turns at the outmost part of the lane, and very slowly correcting the deviations afterwards.
By increasing the PID constants and the target waypoint distance, the vehicles are now back to their correct behavior
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7922)
=> Fixed TM control in UE5

requirements.txt
With the release of numpy 2.0, the numpy version now has to be fixed to avoid installing it, as it has conflict with some libraries such as boost
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7941)
=> Fixed numpy version

Unreal/CarlaUnreal/Config/DefaultGame.ini
Removed all but Town10 from the package
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7944)
=> Removed all but Town10 from the package

README.md
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7988)
=> Update README.md with new TinyURL links

PythonAPI/carla/source/libcarla/Geom.cpp
Exposed the C++ InverseTransformPoint() into the API. Docs are missing
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/7999)
=> Added inverse transform

Docs/adv_digital_twin.md
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8090)
=> Added digital twins video

PythonAPI/CMakeLists.txt, PythonAPI/carla/pyproject.toml.in
This PR adds a minor modification to the PythonAPI CMakeLists.txt to make scikit-build-core use the same generator as the invoking cmake instance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8110)
=> Propagate CMake generator to scikit-build-core.

.clangd.in, CMakeLists.txt, LibCarla/source/carla/streaming/detail/tcp/Client.cpp, LibCarla/source/carla/streaming/detail/tcp/ServerSession.cpp, PythonAPI/examples/.gitignore, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp
This PR adds a workaround for the memory blowup issue when using save_to_disk within a listen callback.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8098)
=> Add temporary workaround for the memory blowup issue

.gitignore, CMake/Dependencies.cmake, CMake/Util.cmake, CMakePresets.json, LibCarla/CMakeLists.txt, Unreal/CMakeLists.txt
This PR applies the following changes:
- Rename the package targets to lower case for consistency. Example: from `package-DebugGame` to `package-debuggame`.
- Update top .gitignore to account for generated .clangd files.
- Fix the displayed option values of carla-help. Previously they were showing the default values instead of the ones being passed by the user.
- Remove multiple project statements from the libcarla CMakeLists.txt.
- Moves the body of the CMake macro carla_dependency_add into two functions: one for git clones and one for downloads. This will be useful for future refactors of how dependencies are handled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/car …
=> Multiple minor fixes related to build and docs.

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/WorldObserver.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
This PR adds some minor code cleanup to marcel/get-name. Unused code has been removed and the error handling in get_actor_name and get_actor_class_name have changed to return and empty string if anything goes wrong.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8166)
=> Remove unused code and change error handling in marcel/get-name.

CMake/Options.cmake
This PR sets the Fast-CDR back to its previous value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8172)
=> Fix incorrectly set ROS2 dependency tag.

Util/BuildTools/Linux.mk
A typo has been found on the Linux makefile, line 141: "setup" target is supposed to call "downloadplugins" target, but the column misplacement implies "downloadplugins" is the same target as "setup". However, "downloadplugins" target is already defined below (line 162). This leads to a warning:
```
Util/BuildTools/Linux.mk:162: warning: overriding commands for target « downloadplugins »
Util/BuildTools/Linux.mk:141: warning: ignoring old commands for target « downloadplugins »
```
This second definition overrides the first one, justifying the fact that the first one is a typo.
Changed column location to avoid override warning and have a correct "setup" target.
Nothing to my knowledge.
- - - …
=> Correcting makefile typo to avoid override warning for target "downloadplugins"

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Recorder/CarlaRecorderQuery.cpp
This PR removes std::format unless explicitly requested. This is because while <format> may exist, std::format may not be defined.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8178)
=> Disable std::format unless ENABLE_STD_FORMAT is defined.

Unreal/CMakeLists.txt
This PR adds a missing target dependency, which is responsible for packaged builds sometimes not containing the PythonAPI whl.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8193)
=> Add missing package target dependency.

CMake/Common.cmake, CMakePresets.json
This PR makes the toolchain path absolute (if relative to the CARLA workspace). This addresses some build issues with the Python API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8200)
=> Make toolchain paths absolute.

Unreal/CMakeLists.txt
This PR fixes an incorrect .def path and adds a missing dependency to carla-unreal-editor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8215)
=> Fix Unreal CMake typo. Add missing dependency.

Util/InstallersWin/install_gtest.bat
I updated the `install_gtest.bat` script to reflect what I believe to be the correct behavior. While installing Carla-0.9.15, I encountered a crash related to the Boost library installation (unrelated to this issue). Rerunning the `make PythonAPI` command resulted in the following error:
```
-[install_gtest]: [Batch params]: --build-dir "D:\Apps\carla\carla-dev\Build\" --generator "Visual Studio 16 2019"
The system cannot find the batch label specified - already_build
```
This issue is mentioned here:
- https://discord.com/channels/444206285647380482/445494135990779915/1232033672857780324
- https://github.com/carla-simulator/carla/issues/5088#issuecomment-1954561903
I resolved the issue by updating the errorlevel string to use the `%errorlevel%` variable.
* **Platform(s):** Tested on …
=> Updated install_gtest.bat

PythonAPI/examples/manual_control_with_traffic.py
Fixed the _manual_control_with_traffic_ script, which was crashing due to a missing argument
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8339)
=> Fix new script

LibCarla/source/carla/client/World.cpp, LibCarla/source/carla/client/World.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.h, LibCarla/source/carla/trafficmanager/VehicleLightStage.cpp, LibCarla/source/carla/trafficmanager/VehicleLightStage.h, PythonAPI/carla/src/World.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
Added a `world.is_weather_enabled()` function to differentiate between towns that have their weather API enabled and those that haven't (like Town10HD)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8373)
=> Add is_weather_enabled function

Docs/build_linux_ue5.md, Docs/build_windows_ue5.md
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8377)
=> Update UE5 build setup script name

PythonAPI/examples/manual_control.py, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp
Fixed the way the semantic LIDAR gets the object tag, to match the new implementation (old one was returning always 0)
Also, added the semantic LIDAR to the manual control
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8423)
=> Fixed semantic LIDAR

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp
This PR temporarily disables motion blur whenever a sensor is running under 1080p. This is to mitigate some motion blur artifacts that appear as dither trails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8421)
=> Disable motion blur when under resolutions 1080p.

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [CARLA Simulator Guru](https://gurubase.io/g/carla-simulator) to Gurubase. CARLA Simulator Guru uses the data from this repo and data from the [docs](http://carla.readthedocs.io) to answer questions by leveraging the LLM.
In this PR, I showcased the "CARLA Simulator Guru", which highlights that CARLA Simulator now has an AI assistant available to help users with their questions. Please let me know your thoughts on this …
=> Introducing CARLA Simulator Guru on Gurubase.io

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
Document changed: ActorBlueprintFunctionLibrary.cpp
Adjust the Highlight Contrast Scale value for the RGB sensor to resolve the black halo around the sun. From 0.3 to 0.7
Fixes: https://github.com/carla-simulator/carla/issues/8371
* **Platform(s): Ubuntu 22
* **Python version(s): 3.10
* **Unreal Engine version(s):UE5.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8445)
=> Adjust the Highlight Contrast Scale value

Docs/tuto_G_bounding_boxes.md
Spawn points were used before being defined in the example code for setting up the simulation, this PR fixed that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8461)
=> Change order of spawn points getter

Unreal/Package/CopyCarlaAdditionalFiles.cmake
This PR changes which files are copied to the package. Missing PythonAPI files like interpolation.xml and the ros2 folder are copied, while folders like rss are excluded for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8464)
=> Update which files are copied during packaging.

Docs/tuto_G_bounding_boxes.md
Spawn points were used before being defined in the example code for setting up the simulation, this PR fixed that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8462)
=> Fix mistakes in bounding boxes docs

PythonAPI/examples/requirements.txt
- Update and unify numpy requirement
- Remove numpy for python 2
- Remove open3d requirement for python 3.12 since that package does not officially support python 3.12
- Remove matplotlib requirement, since it is installed with open3d and only used in open3d codes
- Tested that requirements are correctly installed in environments with python versions from 3.8 to 3.12
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8467)
=> Update requirements for python versions 3.8-3.12

CMake/Options.cmake, Unreal/CMakeLists.txt
This PR changes what UE build configuration the `package` target defaults to. Previously it was always set to shipping, now it defaults to the UE equivalent of the current CMake configuration:
- Debug -> Debug
- RelWithDebInfo -> Development
- Release -> Shipping
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8472)
=> Change conterintuitive package and editor build configuration rules.

requirements.txt
setuptools required version in python >3.8 was too low and led to issues of the form:
`C:\Users\TDA\Desktop\CARLA\Carla-0.10.0-Win64-Development\PythonAPI\examples`
Allowing it to be higher avoids that issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8483)
=> Update setuptools in requirements to avoid problems in higher python versions

Unreal/Package/CopyCarlaAdditionalFiles.cmake
This PR fixes a typo in CopyCarlaAdditionalFiles.cmake. It also expands the pattern list to include more files in the ROS2 example folder of the Python API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8519)
=> Fix missing files in the Python API ROS2 examples folder.

CarlaSetup.sh
This PR fixes CarlaSetup.sh flooding bashrc with the downloaded cmake path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8541)
=> Fix CarlaSetup flooding bashrc with the downloaded cmake path.

CarlaSetup.sh, Util/SetupUtils/InstallPrerequisites.sh
This PR modifies the default behavior for the CarlaSetup.sh script.
To recover the old behavior use: `CarlaSetup.sh --interactive`
The new behavior assumes a headless environment by default, which requires the user to provide git credentials in their environment and to run the script as sudo (pass the -E flag to sudo to preserve the environment!). Alternatively you can install the prerequisites separately using Util/SetupUtils/InstallPrerequisites.sh, at which point you stop needing to use sudo for the main script: `CarlaSetup.sh --skip-prerequisites`.
Additionally, automatically launching of the editor has been disabled, unless you pass `--launch`.
- - - …
=> Modify default CarlaSetup.sh behavior.

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp
As stated by [this issue](https://github.com/carla-simulator/carla/issues/8529), activating the semantic lidar in the Mine map in Carla UE5 led to a crash in the server. This was due to the landscapes lacking tags. Hence, when the semantic lidar sensor tried to access the tag of the object, it got a null value, leading to a crash.
In order to fix that, this PR includes a condition to check whether the actor is a landscape, and in that case, asign on the fly a terrain tag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8568)
=> Fix crash in Mine map when activating semantic lidar

Makefile
- Fixes Makefile target 'CarlaUnrealEditor' given more than once in the same rule
Not needed.
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8580)
=> build: fix Makefile target given more than once & force execute

CHANGELOG.md, PythonAPI/carla/source/carla/__init__.py, PythonAPI/carla/source/carla/command.py, PythonAPI/carla/source/libcarla/Commands.cpp
Fixes  #6414  
Currently `import carla.command` or `from carla.command import ...` is not possible.
This will raise:
```python
7 # pylint: disable=W0401
----> 8 from .libcarla.command import *
ModuleNotFoundError: No module named 'carla.libcarla.command'
```
This is because the `command` module is registered as `libcarla.command` in `sys.modules`. This is not really correct.
---
This PR adjusts this:
- renames the module to `carla.libcarla.command` 
- provides a duplicate `carla.command` that can be imported.
Note / Up to discussion:
This PR deletes `command.py` as otherwise `carla.command is not carla.libcarla.command`. Both modules would be equivalent but not the same. I think this is the cleaner option.
This PR:
- PRO: Compatibility is granted and extended to be more user friendly
- …
=> Correct "libcarla.command" namespace and allow `from carla.command import ...`

PythonAPI/examples/generate_traffic.py, PythonAPI/examples/invertedai_traffic.py, PythonAPI/examples/start_recording.py
[Previous commit](https://github.com/carla-simulator/carla/commit/aeeff9907eb1b64f66dddbc1a0de9d7379a566a8) allows to import methods directly from `carla.command` without a workaround, as required previously. This PR updates 3 example scripts simplifying the code and making it more user friendly to account for that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8587)
=> Simplify importing methods from carla.command in example scripts

CHANGELOG.md, PythonAPI/carla/source/carla/__init__.py, PythonAPI/carla/source/libcarla/AdRss.cpp
Fixes #8093
This is a hack that fixes the messy import namespacing of the `ad_rss` library. Importing `carla` which in turns imports `ad_rss as ad` puts all its subpackages as top-level pckages/modules.
For example this is currently valid:
```py
import carla
import ad
import core # ad.rss.core
import world 
...
```
This raises an ImportError
```py
import carla.ad
```
Also it creates ambiguous import behavior where the order of imports matter, e.g. if I had a subpackage/module names like *any* of ad_rss subpackages the following code will also fail as it imports the wrong module
```py
import carla  # assume with RSS
import world, core  # This imports ad subpackages instead of mine.
```
This is non-standard and confusing behavior.
See also: https://github.com/intel/ad-rss-lib/issues/258
--- …
=> Hack to fix ad_rss's import namespaces

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.h, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveActor.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveActor.h
Added a new attribute to the OpenDriveActor called 'CustomPath'. This results in two behaviours:
- If empty (default case), the behaviour won't change from the current implementation, and it will make use the loaded map's xodr.
- If not, the OpenDriveActor will make use of the specified path, understanding it as a full path.
* **Unreal Engine version(s):** CARLA's 5.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8602)
=> Custom path at OpenDriveActor

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveActor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveActor.h
Added a new attribute to the OpenDriveActor called 'CustomPath'. This results in two behaviours:
- If empty (default case), the behaviour won't change from the current implementation, and it will make use the loaded map's xodr.
- If not, the OpenDriveActor will make use of the specified path, understanding it as a full path.
* **Unreal Engine version(s):** CARLA's UE4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8603)
=> Custom path at OpenDriveActor (UE4)

LibCarla/source/carla/image/CityScapesPalette.h, LibCarla/source/carla/rpc/ObjectLabel.h, PythonAPI/carla/src/World.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Game/Tagger.cpp
Fixes
Add Rock/Stone asset tag, so anymap with the rock/stone assets will visible on segementation camera, including Mine01, related isseue:
https://github.com/carla-simulator/carla/issues/8559
* **Platform(s):Linux 22.04.1-Ubuntu GNU/Linux
* **Python version(s):Python 3.8.19
* **Unreal Engine version(s):5.5.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8598)
=> add rock/stone tag

CHANGELOG.md, PythonAPI/examples/rss/rss_sensor.py, PythonAPI/examples/rss/rss_visualization.py
This PR addresses some string comparisons in the *rss_visualization.py* that are written like:  
`ad.rss.state.RssStateEvaluator.LongitudinalDistanceOppositeDirection == "LongitudinalDistanceOppositeDirection"` which is always `False` as the enum is an int and has no support for string comparison.
In the example some arrows on the HUD were therefore always or never printed.
---
For verification try this statement which **returns `False` but is intended to be `True`**.
```python
from carla import ad
print(ad.rss.state.RssStateEvaluator.LongitudinalDistanceOppositeDirection == "LongitudinalDistanceOppositeDirection")
```
* **Python version(s):** Python 3.10
- - - …
=> Fix invalid comparisions with string literals in RSS example

CMake/Options.cmake, CMake/Toolchain.cmake, CMakePresets.json, CarlaSetup.bat, CarlaSetup.sh, Util/SetupUtils/InstallPrerequisites.bat, Util/SetupUtils/InstallPrerequisites.sh
This PR adds the following:
- Simplify CMake configure commands: now all systems can just pass --toolchain=CMake/Toolchain.cmake.
- The CMake presets are now just Debug/Development/Release, instead of having the system prefixed to the name.
- The setup script now accepts the parameter -pyroot or --python-root to specify the path of an existing python installation.
- Removed the CMake options GCC_COMPILER and GXX_COMPILER, since they are no longer needed.
- Removed the (apt) dependencies on gcc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8616)
=> Minor setup script and build system upgrade.

CMakePresets.json
This PR changes the declaration order to force Visual Studio to pick the Development preset by default (as Debug will fail to build Unreal targets). It also activates CMAKE_EXPORT_COMPILE_COMMANDS by default, which is useful for VS Code development purposes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8625)
=> Minor CMakePresets.json improvements.

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
This PR fixes color_saturation and highlights_gamma being incorrectly marked as floating point attributes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8618)
=> Fix color_saturation's and highlights_gamma's type.

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedComponent.h
* Requires one minor change to UnrealCarla: https://github.com/CarlaUnreal/UnrealEngine/pull/38
* For the latest UE4.26 CARLA version
I noticed that spline meshes (e.g. the cables on PowerPoles) appear invisible in the instance segmentation (showing the decoded R channel of the instance segmentation):
This PR extends the implementation in TaggedCommponent to explicitly handle SplineMeshSceneProxies. SplineMeshComponents are derived from StaticMeshComponents, thus the components are technically already handled by the existing tagging code. But without explicitly deriving a FTaggedSplineMeshSceneProxy from FSplineMeshSceneProxy, they seem to not be rendered correctly. FSplineMeshSceneProxy is currently not public in UE4, thus a minor modification to UnrealCarla is required: …
=> [Fix] Invisible spline meshes in instance segmentation (UE4)

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/FrameData.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaRecorder.h
Fix the recording & replaying issue introduced by this pull request https://github.com/carla-simulator/carla/pull/6922 
- The vehicle door animation event was introduced by pull 6922 and introduced two issues
- The recorder starts to look for CarlaActors before they are registered and ends up with an accessing null pointers crash
- The VehicleDoor enum is not appended at the end of the CarlaRecorderPacketId and thus makes the old log file screw up when replaying by latest runtime built from the ue4-dev branch.  e.g. a uint8_t value of 21 in an old log file should be interpreted as an AnimVehicleWheels even but is no incorrectly interpreted as a VehicleDoor event.  This leads to a hang. 
Fixes #  
- - - …
=> fix a recorder crash and replay hang for 0.9.15 log issue 

CHANGELOG.md, Docs/build_windows.md, Util/BuildTools/BuildLibCarla.bat, Util/BuildTools/BuildOSM2ODR.bat, Util/BuildTools/BuildOSMRenderer.bat, Util/BuildTools/Setup.bat, Util/InstallersWin/install_boost.bat, Util/InstallersWin/install_chrono.bat, Util/InstallersWin/install_fastDDS.bat, Util/InstallersWin/install_gtest.bat, Util/InstallersWin/install_proj.bat, Util/InstallersWin/install_recast.bat, Util/InstallersWin/install_rpclib.bat, Util/InstallersWin/install_xercesc.bat
This PR aims to upgrade default VS used in windows to compile Windows version for ue4-dev
Fixes #  
* **Platform(s):** Windows11
Documentation is not updated properly
You will need to do a clean setup of the project to be able to compile properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8815)
=> Set visual studio 2022 to default generator in windows

CMake/Options.cmake
This PR adds the CMake option CARLA_UNREAL_LOG_WINDOW (ON by default). This makes UE show a separate terminal window with the output log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8828)
=> Add CARLA_UNREAL_LOG_WINDOW.

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
The server call "get_actor_bounding_box" seems to be bugged sometimes the server to try to act on a destroyed actor, crashing the simulation. This PR comments it out to temporarily avoid it but a fix is required
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8832)
=> Commented "get_actor_bounding_box" out due to a bug

CHANGELOG.md, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Actor/ActorRegistry.cpp
This PR adds support for assigning custom tags to Unreal actors based on their CARLA description.
The new logic sets the `Tags` array of each actor using the description variations, allowing them to be queried or filtered directly from the Unreal Editor or via gameplay logic.
For instance, ego vehicles will now include the tag role_name:hero
Other roles or attributes can be added similarly using key-value combinations from the description dictionary.
This helps with debugging, editor filtering, and future logic that relies on actor metadata.
Fixes # 
* **Python version(s):** N/A
Setting too many tags or overly complex key-value structures could slightly impact performance if used heavily in gameplay queries. However, for …
=>  Added actor description as Actor TAGs

LibCarla/source/carla/client/DebugHelper.cpp, LibCarla/source/carla/client/DebugHelper.h, LibCarla/source/carla/client/detail/Client.cpp, LibCarla/source/carla/client/detail/Client.h, LibCarla/source/carla/client/detail/Simulator.cpp, LibCarla/source/carla/client/detail/Simulator.h, PythonAPI/carla/source/libcarla/World.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/DebugShapeDrawer.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/DebugShapeDrawer.h
Adds the ability to clear debug shapes without having to reload the simulator. Using World.PersistentLineBatcher->Flush() .
In PythonAPI called by:
```
world = client.get_world()
debug_helper = world.debug
debug_helper.clear_debug_shape()
```
Fixes #1999 
* **Platform(s):** Windows 10 x64
* **Python version(s):** 3.7.0
* **Unreal Engine version(s):** 4.26.2
If `PersistentLineBatcher` is used elsewhere in the code apart from `FDebugShapeDrawer ` class then flushing it using this method might remove other things apart from debug shapes. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8855)
=> Added ability to clear debug shapes without reloading simulator UE4

Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Carla.Build.cs, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Game/CarlaEpisode.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Game/CarlaStatics.cpp, Unreal/CarlaUnreal/Plugins/Carla/Source/Carla/Game/CarlaStatics.h
This PR aims to expand the map loading funcitonality to enable people  to load maps from other plugins. 
Fixes #  
* **Unreal Engine version(s):** 5.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8862)
=> Map loading expansion

PythonAPI/carla/source/libcarla/Control.cpp
Add missing conversion class from vector of WheelTelemetryData to Python list
This adds a missing conversion from vector of WheelTelemetryData to a Python list. When trying to access the "wheels" attribute of the VehicleTelemetryData without this, this exception will occur:
TypError: No to_python (by-value) converter found for C++ type: std::vector<carla::rpc::WheelTelemetryData, std::allocator<carla::rpc::WheelTelemetryData>>
This addition fixes this issue to make the usage in line with similar classes such as "VehiclePhysicsControl" and "WheelPhysicsControl".
This is a fixed PR from #8560 for the UE4 branch.
Checklist:
* **Python version(s):** 3.10.12
* **Unreal Engine version(s):** 4.26.2.0
- - - …
=> Add missing conversion class from vector of WheelTelemetryData to Python list (UE4)

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp
Add the wheels into the check of physics being enabled because physics state of wheels are destroyed while deactivating vehicles physics
Fixes #8884   
* **Unreal Engine version(s):**4.26
As expected while getting physics control while physics are deactivated it will return properly the last physics control for the wheels
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8887)
=> Fix get_physics_control while physics are not being simulated

LibCarla/source/carla/client/Actor.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Server/CarlaServer.cpp
This PR aims to get a proper bounding box from the actor. if the actor exist in the server, it uses the one on the server. if not it uses the latest in the client. 
Fixes #  
* **Python version(s):** Python 3.8.10
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8882)
=> Fix the bounding box call

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Content/PostProcessingMaterials/TaggedMaterials/.gitignore, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/GenerateTaggedMaterialsRegistry.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/GenerateTaggedMaterialsRegistry.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Commandlet/PrepareAssetsForCookingCommandlet.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/CarlaGameModeBase.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedComponent.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedComponent.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedMaterials.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/TaggedMaterials.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/Tagger.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Game/Tagger.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.cpp, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/InertialMeasurementUnit.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/CaService.cpp, Util/BuildTools/Package.bat, Util/BuildTools/Package.sh
Currently, the instance segmentation replaces all materials on all meshes simply using an opaque material, which can be colorized with an RGB encoding of the type and the object ID. Secondary SceneProxies of all meshes are then rendered with these tagged materials resulting in the instance segmentation output. The current solution has the drawback, that masked materials are simply ignored. Thus, partial transparent surfaces in the RGB image appear fully opaque in the instance segmentation, resulting in very coarse annotations, which also do not match to the semantic segmentation.
This PR addresses this issue by introducing additional logic, that tackles masked materials for the instance segmentation. The following images show a before/after comparison of the semantic channel in the …
=> [Feature] Support of masked materials in instance segmentation (UE4)

Docs/python_api.md, Docs/requirements.txt
mkdocs version 1.2.3 => 1.6.1
jinja2 version3.0.3 => 3.1.6
Fixed malformed links in python_api.md
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8910)
=> Updated mkdocs and jinja and fixed links

.readthedocs.yaml, Docs/python_api.md, Docs/requirements.txt
Fixes #  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8912)
=> Update readthedocs.yml Python version from 3.7 to 3.8 for compatibility

Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Recorder/CarlaReplayerHelper.cpp
This bugfix prevent reusing actors on playback. If during a playback new actors are spawned the ID translating mechanism from recorded data and current playback becomes unstable and the server doesn't know what actors has been created by the playback mechanism and what not. When this happens it's possible that the playback tries to reuse a previous created actor by him, creating an alias in the ID translating mechanism.
Fixes #  
* **Unreal Engine version(s):** UE4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8960)
=> avoid car aliasing due to a bad car reutilisation

Docs/build_windows_ue5.md
Fixes two typos in the UE5-version build instructions for windows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/8959)
=> Fix typos in UE5 build instructions

CHANGELOG.md, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/AsyncDataStream.h, Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/PixelReader.h
After migrating an internal tool from CARLA 0.9.13 to 0.9.15, I noticed that there is an issue with the metadata, that comes with `SensorData` in 0.9.15.
For camera-based sensors, the `frame`, `timestamp` and `transform` do not correspond to the actual image, which is a quite severe issue for things like sensor fusion (since we cannot reliably synchronize different sensors) or for 3D reconstruction (where accurate transforms are necessary).
I created a minimal script [sensor_metadata_test.zip](https://github.com/user-attachments/files/20405558/sensor_metadata_test.zip) , that showcases this problem. It spawns a camera and moves it along the x-axis by one meter per tick for ten ticks. It then logs the frame, timestamp and x-position of the sensor according to the `WorldSnapshot` and …
=> [Bugfix, UE4] SensorData's frame, timestamp and transform are wrong for camera sensors

.github/workflows/ue4_content.yml, .github/workflows/ue4_dev.yml
This PR adds dummy workflows to the default branch (`ue5-dev`) for the UE4 workflows. GitHub Actions only allows manually dispatched workflows to be triggered via the Web UI if they reside in the default branch. Since the actual workflows live in the `ue4-dev` branch, they are not directly accessible for manual dispatch. To work around this, a placeholder workflow has been added in the default branch. **Make sure to update the ref input to target the correct branch (i.e., `ue4-dev`) before triggering the workflow.**
* **Python version(s):** 3.10,3.11,3.12
We have to manually set the ref branch to `ue4-dev` before running the workflows. If this is not done, the workflow will run on the default `ue5-dev` branch, and …
=> [CI/CD] Add placeholder UE4 workdlows to allow manual dispatch

LibCarla/source/carla/road/Map.cpp
Relax conditions of asserts when getting road predecessors and successors to avoid crashes in Largemaps.
Fixes #  
* **Platform(s):** Windows/Ubuntu22
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/9095)
=> Relax asserts

Co-Simulation/Sumo/sumo_integration/sumo_simulation.py
This PR avoids the SUMO Co-simulation warning and updated the deprecated call to the lxml library.
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/carla/9106)
=> Fix SUMO Co-simulation warning deprecated call to lxml
